### ISSUE TITLE
多集影片nfo处理有误，jellyfin无法识别

### ISSUE THREAD

**Issue by shadow0622** [yoshiko2/AV_Data_Capture#100]
正常识别"*-CD1.mp4"及"*-CD2.mp4"两个文件，然而分别生成了不含"-CDn"的nfo文件导致发生覆盖(不确定是否为作者意图)，nfo内title带了 "-CDn"(同样不确定是否为作者意图)。最终结果为jellyfin无法正确识别

**Comment by yoshiko2** [comment]
资料太杂，多集难做

**Comment by RuyiXP** [comment]
目前可以这样操作:
1. 文件名保持a.mp4 a_B.mp4或者a-1.mp4 a-2.mp4之类的默认顺序即可，不要以-cd#结尾。
2. 使用ADC处理，第一集自动命名为a.mp4并生成a.nfo a.jpg等文件，后续mp4提示重复。
3. 将后续mp4复制到a.mp4的文件夹，分别改名-cd2 -cd3等，确保jellyfin正确识别。
4. 将a.mp4及a.nfo改名a-cd1.mp4及a-cd1.nfo，图片文件不改名。
5. 这样可以正确分集并显示元数据，并且不涉及文件内容编辑，方便NAS等远程操作。

**Comment by yoshiko2** [comment]
建议用视频合并

**Comment by eromoe** [comment]
想问一下无法识别的原因是什么，我看 .nfo 里  <poster> 这项有值，且图片文件存在
知道原因的话我可以帮忙调整一下
