### ISSUE TITLE
我转码了很多webm文件，不能识别

### ISSUE THREAD

**Issue by vicnoah** [yoshiko2/AV_Data_Capture#104]
我转码了很多webm文件，不能识别。转码初衷是因为webm编码高效，并且文件大小只有h264的mp4的一半，可以大幅节省空间。emby播放等都是正常的。不过我发现刮削器不能识别webm文件，对python不是很熟，看着有四处定义文件扩展名的地方改了改，在我这能够使用了。希望可以看看我的提交，并增加此格式的支持。
另外存在一个共演的演员过多时，如:ATKD-286-C.webm会出现文件名过长报错问题，我运行的环境是linux x64，希望作者能够处理一下。
非常感谢。

**Comment by yoshiko2** [comment]
可以，下个版本添加

**Comment by nukewarrior** [comment]
@vicnoah 你用的什么参数转码的啊，工具是ffmpeg么

**Comment by vicnoah** [comment]
> @vicnoah 你用的什么参数转码的啊，工具是ffmpeg么
我自己写的小工具，暂时没文档，基于docker的ffmpeg使用显卡转码的，暂时支持sftp与local（本地）转码模式，会自动将目录中文件转码为目标格式，暂时没有转码错误处理可能会因为文件原因发生ffmpeg本身转码失败退出的情况，但基本没啥大问题了。
https://github.com/vicnoah/vts
