### ISSUE TITLE
关于自定义目录和影片重命名规则的建议

### ISSUE THREAD

**Issue by Senjusama** [yoshiko2/AV_Data_Capture#107]
首先感谢作者的无私奉献,这个软件对于我们这些松鼠症患者来说绝对是巨大的福音.希望自定义影片目录和重命名规则的时候可以加一项命名参数即"(中文字幕)".如果能实现的话对于整理影片还是很有帮助的.最后祝大家新的一年身体健康,心想事成 : )

**Comment by PHCSJC** [comment]
目前好像是这样的：
当文件名包含:中文，字幕，-c., -C., 处理元数据时会加上中文字幕标签

**Comment by yoshiko2** [comment]
就像楼上所说
