### ISSUE TITLE
2.5版本在windows环境下似乎不能正常提取元数据

### ISSUE THREAD

**Issue by xinyo** [yoshiko2/AV_Data_Capture#110]
![image](https://user-images.githubusercontent.com/5722044/74089959-87de6580-4afa-11ea-8c97-d3965250fc49.png)

ini设置如下:
`[common]
main_mode=1
failed_output_folder=failed
success_output_folder=JAV_output
soft_link=0

[proxy]
proxy=
timeout=10
retry=3

[Name_Rule]
location_rule = '#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule = title

[update]
update_check=1

[media]
media_warehouse=emby
#emby or plex or kodi ,emby=jellyfin

[escape]
literals=\()

[movie_location]
path=
`

**Comment by yoshiko2** [comment]
暂时不要加year参数
