### ISSUE TITLE
请问目前对plex是不怎么支持吗

### ISSUE THREAD

**Issue by picarbaba** [yoshiko2/AV_Data_Capture#112]
我选emby的时候在jellyfin可以加入元数据
选plex的时候在plex里面就演员 tag都显示不出来了

**Comment by yoshiko2** [comment]
很久没维护plex

**Comment by zj9495** [comment]
希望能够更新对plex的支持👍

**Comment by zj9495** [comment]
plex需要安装插件XBMCnfoMoviesImporter
