### ISSUE TITLE
[功能请求]增加多集影片识别方法、番号识别适配

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#116]
https://github.com/yoshiko2/AV_Data_Capture#多集影片处理
据我实际体验来看，公网上的JAV资源有很多分集是加后缀`A` `B` `C`来区分的，反倒是`CD1 CD2`这种形式后缀见的不太多，希望能增加`-A` `-B`的分集识别。为了避免与-C中文字幕混淆可以加一个判断是否有多个同番号媒体文件存在的逻辑，或者简单一点只识别AB，-C依然作为中字处理，这样也能覆盖大部分AB分集的情况。
另外，存在一些形如`zmen00038`的番号目前不能被正确识别，也希望能适配一下。

**Comment by Mosney** [comment]
似乎sht出品的-C都会把两个分集合并到一个里面去，看起来不太需要考虑-C兼容性了

**Comment by moyy996** [comment]
但是EMBY只会识别-CD 不认-A -B -1 -2

**Comment by Mosney** [comment]
adc改名就是了，我指的识别是最开始的元数据文件名

**Comment by tyhunter** [comment]
自己用renamer pro批量改名就行了
