### ISSUE TITLE
[Bug] failed_output_folder= 使用非默认值会出问题

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#117]
`failed_output_folder= 0FAILED` 或任何非默认的路径时，`0FAILED`文件夹正常创建，但是实测失败的项目并不会移动到这里，而是以一种奇怪的方式变成了名称为`failed`的文件，且此文件也不是简单的更改名字，实测原来的文件已经被破坏，16进制打开会发现此文件时大部分由0组成。应该可以稳定复现，算是比较严重的bug。

**Comment by yoshiko2** [comment]
现在还有吗
