### ISSUE TITLE
抓取DVAJ的影片时，女优名字会变成中文字符

### ISSUE THREAD

**Issue by rxia24** [yoshiko2/AV_Data_Capture#118]
不知道是不是触发了什么地方。
![image](https://user-images.githubusercontent.com/22437401/74531392-7b796300-4f67-11ea-9e43-33048626eea7.png)

![image](https://user-images.githubusercontent.com/22437401/74531395-7ddbbd00-4f67-11ea-8c2c-af07cd931eac.png)

**Comment by yoshiko2** [comment]
正常
