### ISSUE TITLE
大佬有考虑更改目录结构吗

### ISSUE THREAD

**Issue by orangeff** [yoshiko2/AV_Data_Capture#12]
直接根据番号创建文件夹，二级目录包括视频文件、海报、背景。即：
-ABP-108
------ABP-108.mp4
------ABP-108.nfo
------fanart.jpg
------poster.jpg
另外这个削刮出来的结果在plex中会将背景识别为海报造成图片放缩。
大佬可以修改成这种效果吗https://www.sehuatuchuang.com/tupian/forum/201906/29/182315iichxg2b21pc0xhu.jpg
https://www.sehuatuchuang.com/tupian/forum/201906/29/182313a2e6gr6mxh5xu7cm.jpg
目前使用的JAVMovieScraper
https://github.com/DoctorD1501/JAVMovieScraper
主要的问题有削刮速度慢，不支持luxu等系列，所削刮的演员图片无法被读取。
大佬你的工具削刮速度好评

**Comment by wenead99** [comment]
你能给PLEX的截图看看么，我没用PLEX
@orangeff

**Comment by orangeff** [comment]
![BaiduShurufa_2019-6-29_19-11-0](https://user-images.githubusercontent.com/42274972/60383373-3b31a700-9aa2-11e9-88b6-6ce7778c3978.jpg)
![BaiduShurufa_2019-6-29_18-21-19](https://user-images.githubusercontent.com/42274972/60383376-408ef180-9aa2-11e9-91bf-012149ea2407.jpg)

**Comment by orangeff** [comment]
这是用大佬的工具
![BaiduShurufa_2019-6-29_19-16-46](https://user-images.githubusercontent.com/42274972/60383391-8ba90480-9aa2-11e9-983b-22b72f26e05a.jpg)

**Comment by wenead99** [comment]
你可以提供一下javcrawel生成的nfo文件内容和我的软件生成的nfo文件内容吗。。。P

**Comment by orangeff** [comment]
[nfo.zip](https://github.com/wenead99/AV_Data_Capture/files/3341791/nfo.zip)

**Comment by wenead99** [comment]
建议使用emby......plex难搞 @orangeff

**Comment by NJCCJohnWason** [comment]
建议使用Emby吧，Plex很蛋疼的。

**Comment by biaji** [comment]
> 直接根据番号创建文件夹，二级目录包括视频文件、海报、背景。即：
> -ABP-108
> ------ABP-108.mp4
> ------ABP-108.nfo
> ------fanart.jpg
> ------poster.jpg
> 另外这个削刮出来的结果在plex中会将背景识别为海报造成图片放缩。
> 大佬可以修改成这种效果吗https://www.sehuatuchuang.com/tupian/forum/201906/29/182315iichxg2b21pc0xhu.jpg
> https://www.sehuatuchuang.com/tupian/forum/201906/29/182313a2e6gr6mxh5xu7cm.jpg
> 目前使用的JAVMovieScraper
> https://github.com/DoctorD1501/JAVMovieScraper
> 主要的问题有削刮速度慢，不支持luxu等系列，所削刮的演员图片无法被读取。
> 大佬你的工具削刮速度好评

我计划用这样的结构

A-ABP-ABP-108。我回头改改代码试试看

**Comment by icedrain0611** [comment]
为什么不用
-prestage
-ABP
----ABP-567.mp4
这样的目录，方便找厂家和女优

**Comment by yoshiko2** [comment]
https://github.com/yoshiko2/AV_Data_Capture/blob/master/README.md#%E5%8F%AF%E9%80%89%E8%AE%BE%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9B%AE%E5%BD%95%E5%92%8C%E5%BD%B1%E7%89%87%E9%87%8D%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99 @icedrain0611
