### ISSUE TITLE
增加对jav321的支持

### ISSUE THREAD

**Issue by mengx8** [yoshiko2/AV_Data_Capture#125]
理由如下：
1. jav321有不少老片信息
如松岛老师这部[wmc-002](https://www.jav321.com/video/41wmc00002)，只有jav321有信息，其他已支持的所有站点如均没有该片信息，而且注意`https://www.jav321.com/video/41wmc00002`这个查询地址，jav321是支持根据dmm cid查询的，而且更为强大的是也同时支持wmc-002这样的pid查询

2. jav321支持大量素人车牌，LUXU、MIUM、GANA、NTK、ARA、DCV、MAAN、HOI、NAMA、SWEET、SIRO、SCUTE、CUTE、SQB、JKZ、URF、SIMM、KHY、HAMEDAI等

**Comment by AngeloEyez** [comment]
支持，JAV321的確可以補上很多javbus搜不到的訊息，而且也相當完整
