### ISSUE TITLE
能否增加 log 功能？

### ISSUE THREAD

**Issue by 1an8r0wn** [yoshiko2/AV_Data_Capture#133]
RT.
经常遇到程序闪退的问题，但是程序都是一闪而过，根本来不及截图，又因为没有 log 也没办法发出来 debug，是否能够增加 log 输出的功能？

**Comment by hzmabin** [comment]
支持 。。。

**Comment by yoshiko2** [comment]
难搞。。。

**Comment by yoshiko2** [comment]
可以powershell运行 AV_Data_capture.exe | tee avdc.log
