### ISSUE TITLE
Beta 11.4版windows下仍然无法使用命名规则

### ISSUE THREAD

**Issue by funison** [yoshiko2/AV_Data_Capture#14]
WIN10系统，修改config.ini的命名规则后，输出文件名不受控制。

**Comment by yoshiko2** [comment]
无图言屌

**Comment by Mosney** [comment]
![image](https://user-images.githubusercontent.com/22477230/61110622-3a454000-a4ba-11e9-9746-366a54c3387f.png)
0.11.5 Windows版 同样的问题 naming_rule不生效 输出名字总是只剩number

**Comment by yoshiko2** [comment]
naming_rule用于在媒体库中显示标题，在nfo文件里 @Mosney

**Comment by Mosney** [comment]
> naming_rule用于在媒体库中显示标题，在nfo文件里 @Mosney

原来是这样，明白了。  
另外建议添加视频文件命名规则，之前用JavMovieScraper习惯把文件命名为番号+公司+演员+发售日

**Comment by yoshiko2** [comment]
可以在location rule里改，但是不建议，有时超长标题会导致超出api限制无法写入文件和新建文件夹 @Mosney

**Comment by Mosney** [comment]
> 可以在location rule里改，但是不建议，有时超长标题会导致超出api限制无法写入文件和新建文件夹 @Mosney

你这么一说我才发现 
是我疏忽 完全忘记上面哪个location_rule了 
另外你说的API限制是特指Windows操作系统层面的255字符长度限制么

**Comment by yoshiko2** [comment]
是的，特别是素人系列，标题有多长有多长@ @Mosney

**Comment by Mosney** [comment]
> 可以在location rule里改，但是不建议，有时超长标题会导致超出api限制无法写入文件和新建文件夹 @Mosney

刚才试了一下 
location_rule只能设定目录名称，而我上面提到的是想重命名**视频文件名**为番号+公司+演员+发售日。  
比如：   
`\ABP-499\ABP-499 プレステージ あやみ旬果 2016-07-22.mp4`    
而设定`location_rule=number+'/'+number+' '+studio+' '+actor+' '+release`
的结果是`\ABP-499\ABP-499 プレステージ あやみ旬果 2016-07-22\ABP-499.mp4`    
  
还是希望能加入**视频文件**重命名规则
