### ISSUE TITLE
kodi下能否增加cover.jpg文件？

### ISSUE THREAD

**Issue by StoneForests** [yoshiko2/AV_Data_Capture#141]
目前如果设置输出环境为kodi，在文件目录下会生成xxx.xxx-poster.jpg，但群晖video station只能将cover.jpg设置成为封面，因此能否再单独生成一个cover.jpg？内容就跟xxx.xxx-poster.jpg一致即可。

![image](https://user-images.githubusercontent.com/5436513/75618800-2b78de00-5bae-11ea-87da-f821a246cc48.png)

**Comment by RuyiXP** [comment]
搞个批量重命名软件处理一下就行了



发自我的小米手机
在 austin1000 <notifications@github.com<mailto:notifications@github.com>>，2020年3月1日 11:18写道：


目前如果设置输出环境为kodi，在文件目录下会生成xxx.xxx<http://xxx.xxx>-poster.jpg，但群晖video station只能将poster.jpg设置成为封面，因此能否再单独生成一个poster.jpg？内容就跟xxx.xxx<http://xxx.xxx>-poster.jpg一致即可。
[https://user-images.githubusercontent.com/5436513/75618800-2b78de00-5bae-11ea-87da-f821a246cc48.png]
