### ISSUE TITLE
1为普通模式，依然被分类到女优名称的文件夹下

### ISSUE THREAD

**Issue by ntgeralt** [yoshiko2/AV_Data_Capture#142]
你好，我反馈下刚接触遇到的问题：

1为普通模式，
2为整理模式：仅根据女优把电影命名为番号并分类到女优名称的文件夹下

我全默认选择的1。但看到JAV_output里，有番号为文件夹，也有演员为文件夹。

我看了config，感觉1默认是“女优把电影命名为番号并分类到女优名称的文件夹下”

另外代理建议默认留空。这里玩的应该大部分都走全局代理了。

另外plex其实不读nfo.

还有个问题，比较正规的命名也不识别

![1583068266(1)](https://user-images.githubusercontent.com/8230651/75626303-6a844f00-5c01-11ea-8da5-d696c067c278.png)

**Comment by yoshiko2** [comment]
ppy去掉
