### ISSUE TITLE
抓取的文件名超过群晖限制时，会显示写入失败。

### ISSUE THREAD

**Issue by dogcao** [yoshiko2/AV_Data_Capture#143]
例如：
LUXU-1119 ラグジュTV 1110 瑞々しい美乳にキュッとクビレた腰回りに丸みを帯びた美尻。抜群のプロポーションは相も変わらず、リズミカルな腰使いで男根を締め上げる妖艶な騎乗位に、世の男性は一瞬で彼女の虜にさせる…

群晖的限制：
单个文件大小上限：16 TiB
文件名长度上限：255 字节（请参阅限制 5）
路径名称长度上限：4,096 字节（请参阅限制 5）
符号链接深度上限：40
单个存储空间大小上限：200 TiB（请参阅限制 2）
相同级别中每个文件夹的建议文件数量上限：100,000（请参阅限制 3）

**Comment by yoshiko2** [comment]
ini暂时去掉title
