### ISSUE TITLE
抓取的title只有番号，没有标题

### ISSUE THREAD

**Issue by dakkor** [yoshiko2/AV_Data_Capture#144]
nfo文件里面是这样的
<movie>
 <title>ipx438</title>
  <set>
  </set>
………………
在代码里面切换成用JAVBUS抓取也是这样

**Comment by dogcao** [comment]
在设置里，本地文件名要改成"number-title"而不是“number",如果网站title过长或有非法字符，会导入失败。请自行查看日志。
