### ISSUE TITLE
标题中含有非法字符，例如'/'导致写title目录失败。

### ISSUE THREAD

**Issue by dogcao** [yoshiko2/AV_Data_Capture#146]
VRVR-076 【VR】HQ超高画質！結婚初夜に童貞喪失！デカ乳新妻が優しくエッチを教えてくれた…初体験のキス/オッパイ揉み/パイズリ/フェラで大暴発！肌が触れ合う濃厚密着SEXで何度も膣内射精！ 稲場るか

**Comment by yoshiko2** [comment]
ini中title先去掉
