### ISSUE TITLE
[WinError 123] 文件名、目录名或卷标语法不正确。

### ISSUE THREAD

**Issue by siyiye** [yoshiko2/AV_Data_Capture#153]
[-]Error in creatFolder: [WinError 123] 文件名、目录名或卷标语法不正确。: 'JAV_output/有村えりか/2019-10-19 [CAWD-024] [kawaii*新人デビュ→]'
[-]Move to Failed output folder
[-]Error in AVDC_Main: can only concatenate str (not "NoneType") to str
[-]Error in AVDC_Main: Destination path 'failed/CAWD-024-C.MP4' already exists

**Comment by yoshiko2** [comment]
请去GUI项目页面反馈
