### ISSUE TITLE
番号数字相同识别问题

### ISSUE THREAD

**Issue by ricky-q7** [yoshiko2/AV_Data_Capture#156]
像 1pondo_022020_001_FHD.mp4 与 Carib_022020-001_FHD.mp4 这种的番号，如果我自己把文件名前缀去掉再识别怕弄混淆且重命名之后无法区分。
希望添加heydouga 4030-962 ， H0930_ori1561 这种类型番号识别

**Comment by ricky-q7** [comment]
javbus 好像是用'_'下划线和'-'横杠来区分1pondo和Carib的，但是软件把下划线全替换成横杆，希望解决这个问题

**Comment by ricky-q7** [comment]
[*]                  * New update 2.8.2 *
[*]                     ↓ Download ↓
[*] https://github.com/yoshiko2/AV_Data_Capture/releases
[*]======================================================
[+]Find 2 movies
[!] - 50.0% [1/2] -
[!]Making Data for   [./Carib 022020-001_FHD.mp4], the number is [022020-001]
|DNS-request| avsox.host 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| avsox.host is 104.26.13.205
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.13.205:443-<><>-OK
|DNS-request| avsox.host 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| avsox.host is 104.26.13.205
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.13.205:443-<><>-OK
|DNS-request| us.netcdn.space 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| us.netcdn.space is 104.26.9.86
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.9.86:443-<><>-OK
|DNS-request| us.netcdn.space 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| us.netcdn.space is 104.26.9.86
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.9.86:443-<><>-OK
|DNS-request| us.netcdn.space 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| us.netcdn.space is 104.26.9.86
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.9.86:443-<><>-OK
[+]Image Downloaded! JAV_output/@YOU/022020_001/022020_001.jpg
[+]Writeed!          JAV_output/@YOU/022020_001/022020_001.nfo
[*]======================================================
[!] - 100.% [2/2] -
[!]Making Data for   [./1pondo 022020_001_FHD.mp4], the number is [022020-001]
|DNS-request| avsox.host 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| avsox.host is 104.26.13.205
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.13.205:443-<><>-OK
|DNS-request| avsox.host 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| avsox.host is 104.26.12.205
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.12.205:443-<><>-OK
|DNS-request| us.netcdn.space 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| us.netcdn.space is 104.26.8.86
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.8.86:443-<><>-OK
|DNS-request| us.netcdn.space 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| us.netcdn.space is 104.26.9.86
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.9.86:443-<><>-OK
|DNS-request| us.netcdn.space 
|S-chain|-<>-127.0.0.1:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| us.netcdn.space is 104.26.9.86
|S-chain|-<>-127.0.0.1:1080-<><>-104.26.9.86:443-<><>-OK
[+]Image Downloaded! JAV_output/@YOU/022020_001/022020_001.jpg
[+]Writeed!          JAV_output/@YOU/022020_001/022020_001.nfo
[*]======================================================
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.

**Comment by ricky-q7** [comment]
我尝试了一下，直接覆盖掉了

**Comment by ricky-q7** [comment]
但这是两部完全不同的电影

**Comment by yoshiko2** [comment]
暂时无解
