### ISSUE TITLE
nfo 檔中沒有包含 actor 資訊

### ISSUE THREAD

**Issue by badd1976** [yoshiko2/AV_Data_Capture#157]

**Comment by fanssow** [comment]
刮削成功率没话说，呱呱叫，对比了NFO，多了TAG，单少了关键的ACTOR  EMBY里不能按照演员索引
<actor>
    <name>      </name>
  </actor>

**Comment by s0urcelab** [comment]
之前是有演员信息的，前面某个版本开始就没了

**Comment by lhiqwj173** [comment]
![image](https://user-images.githubusercontent.com/51277202/76808887-04641280-6824-11ea-9af9-fce659c6b744.png)
![image](https://user-images.githubusercontent.com/51277202/76808939-26f62b80-6824-11ea-8e53-ee4d801c5a6e.png)

**Comment by yoshiko2** [comment]
已修复
