### ISSUE TITLE
功能请求：增加待处理数据路径的设置项

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#16]
直接在当前目录下寻找待处理片源过于凌乱，使用Windows打包版还好只有2个exe1个ini，要是用linux版本一堆*.py跟视频文件混在一起既不方便也不优雅  
建议增加一个路径设置项    

**例如**  
```
[directory]  
/sample/dir/  
/sample2/dir2/
```
release中给出的配置文件可以注释掉示例路径，此时路径配置项为空，还是按照之前的逻辑默认在当前目录下查找待处理数据，也能避免版本迭代提高用户学习成本

**Comment by RRRRRm** [comment]
同样的请求，强迫症不把软件安装在/opt或者/usr好难受的。可不可以自定义抓取目录，最好可以是一个列表。感谢！

**Comment by RRRRRm** [comment]
> 直接在当前目录下寻找待处理片源过于凌乱，使用Windows打包版还好只有2个exe1个ini，要是用linux版本一堆*.py跟视频文件混在一起既不方便也不优雅
> 建议增加一个路径设置项
> 
> **例如**
> 
> ```
> [directory]  
> /sample/dir/  
> /sample2/dir2/
> ```
> 
> release中给出的配置文件可以注释掉示例路径，此时路径配置项为空，还是按照之前的逻辑默认在当前目录下查找待处理数据，也能避免版本迭代提高用户学习成本

突然想到可以把片源文件夹链接在项目文件夹下, 再使用配置文件中的[directory_capture]指定

**Comment by yoshiko2** [comment]
11.7有了
