### ISSUE TITLE
无法正确的建立输出目录，基于SMB服务的情况下。

### ISSUE THREAD

**Issue by dogcao** [yoshiko2/AV_Data_Capture#164]
当指定目录为本地网络上的地址时，输出目录会建立到本地电脑上来而不是网络的视频目录下的子目录。

![Snipaste_2020-03-23_11-32-06](https://user-images.githubusercontent.com/49425423/77278543-8fe51400-6cfa-11ea-98ab-48cff8cbe1bb.png)
![Snipaste_2020-03-23_11-33-13](https://user-images.githubusercontent.com/49425423/77278546-91164100-6cfa-11ea-946e-9ad912d4e404.png)
![Snipaste_2020-03-23_11-33-42](https://user-images.githubusercontent.com/49425423/77278547-91aed780-6cfa-11ea-9b63-9206b3ad486d.png)

**Comment by yoshiko2** [comment]
请映射为本地磁盘
