### ISSUE TITLE
Red Hot Fetish Collection 的作品如何搜刮（RED-XXX）？

### ISSUE THREAD

**Issue by kx001001** [yoshiko2/AV_Data_Capture#170]
如题， 通常这些作品的文件命名以RED-xxx形式。譬如： RED-114， 使用库主人的工具搜出来的照片和信息对不上或者干脆搜不出来。现在只有这类作品有问题，是我哪里做的不对吗？
我传图不会被杀吧。。。
![image](https://user-images.githubusercontent.com/48275131/77528367-c7a1b680-6ec8-11ea-9aad-7af7ced7daeb.png)

**Comment by yoshiko2** [comment]
![image](https://user-images.githubusercontent.com/42309414/77752682-fc497580-7062-11ea-84a2-0d1d4878c5e8.png)
暂无发现问题
