### ISSUE TITLE
有些骑兵篇读取不了，直接闪关

### ISSUE THREAD

**Issue by jyogyou** [yoshiko2/AV_Data_Capture#173]
例如YMDD开头的番号无法识别，直接关掉，建议识别到骑兵的片子在这里查找更为准确http://www.javlibrary.com/cn/vl_searchbyid.php?keyword=### 这里###是番号的意思，javlibrary骑兵篇几乎无错误。

**Comment by yoshiko2** [comment]
看2.9修复没
