### ISSUE TITLE
女优是片假名开头的程序会报错

### ISSUE THREAD

**Issue by jyogyou** [yoshiko2/AV_Data_Capture#174]
外国女优是片假名，程序报错 例如：ymdd-031 ymdd-173 ymdd-177
 File "AV_Data_Capture.py", line 137, in <module>
  File "AV_Data_Capture.py", line 89, in getNumber
AttributeError: 'NoneType' object has no attribute 'group'
[12780] Failed to execute script AV_Data_Capture

**Comment by yoshiko2** [comment]
![image](https://user-images.githubusercontent.com/42309414/77749445-ff416780-705c-11ea-8ea0-e936f33c8bd3.png)
![image](https://user-images.githubusercontent.com/42309414/77749486-12ecce00-705d-11ea-9510-9fcdb18b10c8.png)
我无问题。。。
