### ISSUE TITLE
AKA与PRED系列无法识别

### ISSUE THREAD

**Issue by jaord** [yoshiko2/AV_Data_Capture#184]
番号AKA与PRED开头的无法识别，看了下BUS上的搜索结果，大概因为这两个番号的系列搜索结果指向多个系列？
尝试过番号改成大写或者小写，均无法识别。

**Comment by yoshiko2** [comment]
提供下失败的番号？可能是冲突

**Comment by jaord** [comment]
> 
> 
> 提供下失败的番号？可能是冲突

aka-022 aka-068 pred-003

**Comment by simon1092002** [comment]
=

> 
> 
> > 提供下失败的番号？可能是冲突
> 
> aka-022 aka-068 pred-003
aka系列改成118aka00022 這樣fanza撈得到
