### ISSUE TITLE
希望增加javstore.net支持

### ISSUE THREAD

**Issue by ken7ry** [yoshiko2/AV_Data_Capture#185]
http://javstore.net/
这网站资料比较齐全希望能添加上

**Comment by yoshiko2** [comment]
网站已经够多了。。。

**Comment by ken7ry** [comment]
> 网站已经够多了。。。

但是还有一堆素人番号移到failed文件夹去了。。。不知道是不是梯子问题(╥﹏╥)

**Comment by yoshiko2** [comment]
给些失败的番号看看

**Comment by ken7ry** [comment]
> 给些失败的番号看看
 
大佬 看看哪里出问题了。。

[*]================== AV Data Capture ===================
[*]                     Version 3.2
[*]======================================================
[+]Find 7 movies
[!] - 14.2% [1/7] -
[!]Making Data for   [.\1\200GANA-2245.mp4], the number is [200GANA-2245]
[-].\1\200GANA-2245.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\200GANA-2245.mp4 to failed folder
[!] - 28.5% [2/7] -
[!]Making Data for   [.\1\326SCP-014.mp4], the number is [326SCP-014]
[-].\1\326SCP-014.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\326SCP-014.mp4 to failed folder
[!] - 42.8% [3/7] -
[!]Making Data for   [.\1\390JAC-009.mp4], the number is [390JAC-009]
[-].\1\390JAC-009.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\390JAC-009.mp4 to failed folder
[!] - 57.1% [4/7] -
[!]Making Data for   [.\1\390JAC-028.mp4], the number is [390JAC-028]
[-].\1\390JAC-028.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\390JAC-028.mp4 to failed folder
[!] - 71.4% [5/7] -
[!]Making Data for   [.\1\GEKI-023.mp4], the number is [GEKI-023]
[-].\1\GEKI-023.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\GEKI-023.mp4 to failed folder
[!] - 85.7% [6/7] -
[!]Making Data for   [.\1\ORETD-612.mp4], the number is [ORETD-612]
[-].\1\ORETD-612.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\ORETD-612.mp4 to failed folder
[!] - 100.% [7/7] -
[!]Making Data for   [.\1\ORETD-615.mp4], the number is [ORETD-615]
[-].\1\ORETD-615.mp4 ERROR :
[-] 'NoneType' object has no attribute 'xpath'
[-]Move .\1\ORETD-615.mp4 to failed folder
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.
