### ISSUE TITLE
程序不断报错闪退

### ISSUE THREAD

**Issue by CainXie41** [yoshiko2/AV_Data_Capture#186]
![93d242a4eb6977608d99fbee0466621](https://user-images.githubusercontent.com/62974793/78092968-01b9ff00-7386-11ea-9657-ed2852881eb8.png)
前几天用的2.9还能顺利地分辨了不少影片，今天无论是2.9还是3.0都出现了图上的错误，点开程序直接闪退，这还是我手快截图下来的，究竟是哪里出了问题呢

**Comment by zx5155zx** [comment]
咱俩一样

**Comment by 8hundred** [comment]
same problem

**Comment by wzzqq** [comment]
都一样😂😂😂

**Comment by J3n5en** [comment]
Duplicate of #187 
@CainXie41 @zx5155zx @8hundred @wzzqq 
参考我在另一issues中的回复。

**Comment by zx5155zx** [comment]
> Duplicate of #187
> @CainXie41 @zx5155zx @8hundred @wzzqq
> 参考我在另一issues中的回复。

好的，感谢，临时关闭更新

**Comment by CainXie41** [comment]
> Duplicate of #187
> @CainXie41 @zx5155zx @8hundred @wzzqq
> 参考我在另一issues中的回复。

感谢，关闭了之后确实就不再出错了

**Comment by yoshiko2** [comment]
由于 ```update_check.json``` 语法错误，4.3晚已修复
