### ISSUE TITLE
个别影片“标题名过长或存在不正确字符”导致输出失败

### ISSUE THREAD

**Issue by Delodevo** [yoshiko2/AV_Data_Capture#192]
具体运行情况如下

[!]Making Data for   [.\SSNI-436.mp4], the number is [SSNI-436]
[+] ---Debug info---
[+]  - actor       : 橋本ありな
[+]  - cover       : https://pics.javbus.com/cover/7094_b.jpg
[+]  - director    : 前田文豪
[+]  - imagecut    : 1
[+]  - label       :
[+]  - number      : SSNI-436
[+]  - outline     : 232 characters
[+]  - release     : 2019-03-16
[+]  - runtime     :  160分鐘
[+]  - source      : javbus.py
[+]  - studio      : エスワンナンバーワンスタイル
[+]  - tag         : ['高中女生', '單體作品', 'DMM獨家', '第一人稱攝影', '制服', '薄馬賽克', '主觀視角', '高畫質', '汗だく']
[+]  - title       : 制服美少女と湿気の籠る6畳一間で淫猥セックス-清閑な昼下がり…授業を抜け出し畳と汗と愛液の匂いが漂う 狭い部屋で不安と情欲と羞恥心に揉まれながら危険でスリルな関係に心酔していく…-橋本ありな
[+]  - website     : https://www.javbus.com/SSNI-436
[+]  - cover_small :
[+]  - naming_rule : 制服美少女と湿気の籠る6畳一間で淫猥セックス-清閑な昼下がり…授業を抜け出し畳と汗と愛液の匂いが漂う 狭い部屋で不安と情欲と羞恥心に揉まれながら危険でスリルな関係に心酔していく…-橋本ありな
[+]  - location_rule : 橋本ありな/[2019] 制服美少女と湿気の籠る6畳一間で淫猥セックス-清閑な昼下がり…授業を抜け出し畳と 汗と愛液の匂いが漂う狭い部屋で不安と情欲と羞恥心に揉まれながら危険でスリルな関係に心酔していく…-橋本ありな [SSNI-436]
[+]  - actor_list  : ['橋本ありな']
[+] ---Debug info---
[-].\SSNI-436.mp4 ERRPR :
[-] [WinError 123] 文件名、目录名或卷标语法不正确。: 'JAV_output/橋本ありな/[2019] 制服美少女と湿気の籠る6畳一間で淫猥セックス-清閑な昼下がり…授業を抜け出し畳と汗と愛液の匂いが漂う狭い部屋で不安と情欲と羞恥心に揉まれながら危険でスリルな関 係に心酔していく…-橋本ありな [SSNI-436]'
[-]Move .\SSNI-436.mp4 to failed folder
[+]All finished!!!

**Comment by yoshiko2** [comment]
如果有条件就运行源码，在```core.py```中于134, 137行把100改为50即可
