### ISSUE TITLE
请教一下，为什么总是Connect Failed! Please check your Proxy or Network!

### ISSUE THREAD

**Issue by skypapapa** [yoshiko2/AV_Data_Capture#202]
请教一下，为什么总是Connect Failed! Please check your Proxy or Network! 我GFW list 模式，删除了config.ini里面的proxy后面的地址。

**Comment by yoshiko2** [comment]
要全局

**Comment by asdf1319964f** [comment]
我直接vps  删除这句 可以直接用吧
