### ISSUE TITLE
识别到信息却输出失败 [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by Ayler-Lee** [yoshiko2/AV_Data_Capture#203]
图片链接可以打开, 但是提示 [Errno 2] No such file or directory

[*]================== AV Data Capture ===================
[*]                     Version 3.0                      
[*]======================================================
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for   [./122713-508.mp4], the number is [122713-508]
[+] ---Debug info---
[+]  - actor       : 波多野結衣,吉美さあや
[+]  - cover       : https://us.netcdn.space/storage/caribbeancom/moviepages/122713-508/images/l_l.jpg
[+]  - cover_small : https://us.netcdn.space/storage/caribbeancom/moviepages/122713-508/images/jacket.jpg
[+]  - director    : 
[+]  - imagecut    : 3
[+]  - label       : 大人の日曜劇場
[+]  - number      : 122713-508
[+]  - outline     : 0 characters
[+]  - release     : 2013-12-27
[+]  - runtime     : 63
[+]  - source      : avsox.py
[+]  - studio      : カリビアンコム ( Caribbeancom )
[+]  - tag         : ['乱交', '颜射', '舔阴', '手淫', '内射', '巨乳', '美乳', '痴女', '乳交', '69', '口内射精', '美腿', '白领', '打飞机', '美臀', '淫語', '凌辱', '颜射']
[+]  - title       :  半沢直美 〜痴女の10倍返し！ 前編〜
[+]  - website     : https://avsox.host/cn/movie/b3ddd3dd6d4b6139
[+]  - naming_rule : 122713-508- 半沢直美 〜痴女の10倍返し！ 前編〜
[+]  - location_rule : 波多野結衣,吉美さあや/122713-508
[+]  - actor_list  : ['波多野結衣', ' 吉美さあや']
[+] ---Debug info---
[-]./122713-508.mp4 ERRPR :
[-] [Errno 2] No such file or directory: 'JAV_output/波多野結衣,吉美さあや/122713-508/JAV_output/波多野結衣,吉美さあや/122713-508/122713-508-poster.jpg'
[-]Move ./122713-508.mp4 to failed folder
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.

**Comment by litanid** [comment]
我也出现这个错误，目前为止发现全部数字的番号都会出现这个问题，同求解。

**Comment by 68cdrBxM8YdoJ** [comment]
Maybe it's fixed in this commit (https://github.com/yoshiko2/AV_Data_Capture/commit/a0eba2272f8fc3641f687f5c020c3aa14c560f48).
It hasn't been released yet, but you can download it [here](https://github.com/yoshiko2/AV_Data_Capture/actions/runs/75155650) to try it out.
