### ISSUE TITLE
Movies with "xxx-av" are not correctly recogenized

### ISSUE THREAD

**Issue by vamfish** [yoshiko2/AV_Data_Capture#209]
Your work is almost perfect for me. However the code of `xxx-av` movie is not correctly recogenized, could you pls fix it?
Here is the log for version `3.1.2`: 
```
[!]Making Data for   [.\xxx-av-24296.mp4], the number is [xxx-av]
[-].\xxx-av-24296.mp4 ERRPR :
[-] 'title'
[-]Move .\xxx-av-24296.mp4 to failed folder
```

**Comment by yoshiko2** [comment]
You can try to use [this](https://github.com/yoshiko2/AV_Data_Capture#%E6%8B%96%E5%8A%A8%E6%B3%95).

Where is the meta data for this number?

**Comment by vamfish** [comment]
> You can try to use [this](https://github.com/yoshiko2/AV_Data_Capture#%E6%8B%96%E5%8A%A8%E6%B3%95). Where is the meta data for this number?

You mean where I found this movie? The movie is from **javdb**.
And I run the program in PowerShell, resulted another error message...
```
PS D:\AV_Data_Capture_3.1.2> .\AV_Data_Capture.exe xxx-av-24296.mp4
[*]================== AV Data Capture ===================
[*]                    Version 3.1.2
[*]======================================================
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 124, in <module>
TypeError: can only concatenate str (not "NoneType") to str
[9488] Failed to execute script AV_Data_Capture
```
