### ISSUE TITLE
一反饋一些問題與建議

### ISSUE THREAD

**Issue by changyipai** [yoshiko2/AV_Data_Capture#21]
作者如果願意，我願意小額贊助您，但前提是您如果願意修改這個軟體讓他變得強大，我相信這種軟體未來一定是必要的商機。
我建議如下：
1. 建議加入下列品番搜尋
LUXU or 259LUXU完整品番：259LUXU-1046
300MAAN  完整品番：300MAAN-423
300MIUM  完整品番：300MIUM-424
XXX-AV  完整品番：XXX-AV-2243
2. 命名問題與自行命名設定
   A. 狼友(就是使用者)可自定義的取名，不用去預設他們要怎麼命名，多長。像是我就只是單存的 [品番]名稱
   B. 一本道( Ipon)、FC2、Carib 這種，我發現命名後這種字眼都會消失，但我命名就是需要他，像是 [Ipon-XXXXXX-XX] or [Ipon-XXXXXX_XX]
   C. 品番突變，像 Carib 就還有另一種 Caribbean、CARIBPR，一本道(IPON)有時候抓到像是 n1287_2006sp01_dcban_ne，建議也可以抓到後重新命名。

個人建議命名可以已讓狼友分自行在 INI 分別設定，當然有些人不會設定就有預設的統一規則，但不建議寫死在程式碼，命名過長也直接在 INI 設定，看是要無條件捨去後面的名稱，還是只顯示什麼。

3. 圖片下載需求
不是每個人都要下載那麼多圖片還有NFO檔案，我周遭很多人就只要一張圖片和影片，建議可以在讓狼友 INI 設定是否要下載 poster、thumb、還有另外2張我不知道你的命名規則(我今天才開原始碼看)

4.功能完整，您也可以發售可以賣也何嘗不可(但要低調)

**Comment by yoshiko2** [comment]
@changyipai 你说的第二条的B有点难度，可能要整个程序源码改动，发售的话有法律问题，我可能会被查水表，即使用加密货币也非常麻烦

**Comment by changyipai** [comment]
我自定義影片的命名，naming_rule 這個的title 真的不起作用

**Comment by yoshiko2** [comment]
@changyipai 你可以在本地媒体库重新刷新元数据，或者你给个naming_rule更改前后生成的nfo文件截图看看

**Comment by changyipai** [comment]
我沒有要NFO，我只需要他幫我重新命名我的影片喔~~~，因為NFO對我而言是沒有用的

**Comment by yoshiko2** [comment]
naming rule 是更改nfo文件title的内容，关于更多看文档 @changyipai

**Comment by changyipai** [comment]
所以影片就是無法更改就是了，就只有品番?

**Comment by changyipai** [comment]
您的文檔我全看過了(包含如何設定)，所以我才會發文。
感謝

**Comment by yoshiko2** [comment]
https://github.com/yoshiko2/AV_Data_Capture/blob/master/README.md#%E4%BE%8B%E5%AD%90 是这里吗 我改了一下你再看看 @changyipai

**Comment by changyipai** [comment]
好的，你是我見過最熱心的工程師~~

**Comment by changyipai** [comment]
README.MD

**Comment by changyipai** [comment]
![Image 087](https://user-images.githubusercontent.com/53221858/61716142-1246be00-ad91-11e9-9f33-8125140cac08.png)
![Image 088](https://user-images.githubusercontent.com/53221858/61716143-1377eb00-ad91-11e9-9e8b-9d2f6bbed999.png)
![Image 089](https://user-images.githubusercontent.com/53221858/61716147-14a91800-ad91-11e9-85b5-b97923c72a76.png)

**Comment by changyipai** [comment]
再麻煩您可以的話讓影片可以成功自定義更名，過長的話我會自己上網截短名稱，但大部分都不會過長的~~

**Comment by changyipai** [comment]
只有Windows 的255 限制= =

**Comment by yoshiko2** [comment]
影片自定义命名没必要吧。。。毕竟最终效果还是在媒体库中展示，如果想赞助我可以进文档结尾的telegram群组私聊赞助我，谢谢！ @changyipai

**Comment by EmbleXue** [comment]
想要实现自定义重命名的效果，需要修改源码中的**pasteFileToFolder**方法
将
>
    os.rename(filepath, number + houzhui)
    shutil.move(number + houzhui, path)

改为
>
    os.rename(filepath, naming_rule + houzhui)
    shutil.move(naming_rule + houzhui, path)

即可实现视频文件的重命名

**Comment by yoshiko2** [comment]
你可以通过pull requests来提交代码

**Comment by yoshiko2** [comment]
naming_rule可以按照个人喜好设置，我提供了默认设置和模板

**Comment by yoshiko2** [comment]
@EmbleXue

**Comment by changyipai** [comment]
很感謝，另外我自己也在撰寫，我發現 CARIBPR-090316-002、Caribbeancom-081714-669 (屬於同一家公司的)，n1332_2008sp02_uj_dcb(TokeyHot)的，這種都會找錯，有人可以有想過正規表示式來修正嗎?
另外 CARIB、CARIBPR、Caribbeancom 應該是同一家公司，但影片就會真的，找不到

**Comment by changyipai** [comment]
另外 JAVDB.py JAVBUS.py 這個是自己寫的還是網路上找的，如果是作者自己寫的，我想請教您一些問題，弄寫一個 Carib 專用的，並放上來給大家使用。
因為我發現真的很多影片其實在這兩個網頁是找不到的。

**Comment by yoshiko2** [comment]
我现在没时间时间搞carib专用的，你可以自己搞 @changyipai

**Comment by changyipai** [comment]
努力中，搞出來我會分享給大家
