### ISSUE TITLE
The Size of Thumb is Error

### ISSUE THREAD

**Issue by HuangShun** [yoshiko2/AV_Data_Capture#211]
[!]Making Data for   [E:/刮削/EVDV-51004.avi], the number is [EVDV-51004]
[!]Please Wait Three Seconds！
[+] ---Debug info---
   [+]-actor        : 恵けい
   [+]-cover        : https://pics.dmm.co.jp/mono/movie/adult/n_700evdv51004/n_700evdv51004pl.jpg
   [+]-imagecut     : 1
   [+]-number       : EVDV-51004
   [+]-publisher    : 心交社
   [+]-release      : 2008-03-14
   [+]-runtime      : 60
   [+]-source       : javdb.py
   [+]-studio       : 心交社
   [+]-tag          : 介绍影片
   [+]-title        : プチ・ディーバ,恵けい
   [+]-website      : https://javdb.com/v/RdGwK
   [+]-year         : 2008
   [+]-naming_media : number-title
   [+]-naming_file  : number
   [+]-folder_name  : actor/number-title-release
[+] ---Debug info---
[+]Folder : E:/刮削/JAV_output/恵けい/EVDV-51004-プチ・ディーバ,恵けい-2008-03-14
[+]From   : https://javdb.com/v/RdGwK
[-]Error in select_file_thread: The Size of Thumb is Error! Deleted EVDV-51004-thumb.jpg!
[*]======================================================

**Comment by 68cdrBxM8YdoJ** [comment]
What version are you using?

**Comment by HuangShun** [comment]
> What version are you using?

  Version 3.93

**Comment by yoshiko2** [comment]
3.93 is GUI version. Please post in GUI version's issue borad.
