### ISSUE TITLE
挂载移动硬盘，在移动硬盘内启动直接闪退

### ISSUE THREAD

**Issue by baq982** [yoshiko2/AV_Data_Capture#215]
挂载硬盘盒，在硬盘盒内启动软件直接闪退。

测试了几遍，换了几台电脑，只要是在外接硬盘内操作都会闪退，移到电脑内置硬盘就正常，好奇怪

**Comment by baq982** [comment]
[*]================== AV Data Capture ===================
[*]                     Version 3.2
[*]======================================================
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 116, in <module>
  File "AV_Data_Capture.py", line 18, in check_update
  File "json\__init__.py", line 341, in loads
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
[99224] Failed to execute script AV_Data_Capture


这是cmd内的报错，但实则网络正常，在本地硬盘都可以正常归档

**Comment by yoshiko2** [comment]
看看是不是Ini文件问题

**Comment by tinywii** [comment]
遇到同样的问题，使用版本为最新3.3

ini配置如下：

[common]
main_mode=1
failed_output_folder=failed
success_output_folder=JAV_output
soft_link=0

[proxy]
proxy=
timeout=10
retry=3

[Name_Rule]
location_rule = '#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule = title

[update]
update_check=1

[priority]
website=javbus,javdb,fanza,xcity,mgstage,fc2,avsox,jav321

[escape]
literals=\()/
folders=failed,JAV_output

[debug_mode]
switch=0

只修改命名规则，在本地硬盘中则能正常削刮

**Comment by tinywii** [comment]
已解决，出现这个问题的原因在于移动硬盘根目录下System Volume Information文件夹读取权限的问题，将此文件夹删除掉就可以避免出现该问题，@yoshiko2 大大看看能不能下下个版本修复这个问题！

**Comment by Zebra233** [comment]
[escape]
literals=\()/
folders=failed,JAV_output,System Volume Information

把System Volume Information排除
