### ISSUE TITLE
能增加个javlibrary的源吗

### ISSUE THREAD

**Issue by baq982** [yoshiko2/AV_Data_Capture#217]
能增加个javlibrary的源吗，有些片只有这个上面有数据，其他站上面没有

**Comment by yoshiko2** [comment]
例如

**Comment by baq982** [comment]
这些大部分在javlibrary有，其他站都搜不到
DVMC-003
GS-0167
JKREZ-001
KMHRS-010
KNSD-023
MDB-127k
NMS-031
PMP-023
PMS-055
RGD-051
PSB-006
RGD-140
SAND-065
STAR-1024
akiba-07
DAI-014
DL-777
DAI-115
DL-778
DSK8082-3
DVDPS-202
GDMQ-09
GKD-08
Gqd-027
HDI-004
HDI-005
HELL-203
Iadd-011
IBW-410
IBW-478Z
IBW-683Z
iros-005
IROS-031
LALS-06
LALS-07
MANQ-005
MUM-064
MUSO-0190
NMS-003
NMS-001
NMS-007
RGD-037
RDG-134
RDG-045
RGD-042
RGD-039
RGD-044
RGD-046
RGD-049
RGD-054
RGD-057
RGD-060
RGD-061
RGD-063
RGD-069
RGD-072
RGD-067
RGD-081
RGD-082
RGD-084
RGD-090
RGD-094
RGD-097
RGD-098
RGD-102
RGD-103
YOJI-021
RGD-105
RGD-108
RGD-146
s-278
STAR-3063
YOJI-017
yyg-001
Svn-039
TBTB-037
UNKB-313
VERY-4006
UNKB-315
