### ISSUE TITLE
一些改进的建议

### ISSUE THREAD

**Issue by MeetWq** [yoshiko2/AV_Data_Capture#219]
1、建议增加硬链接模式，这样在emby上也能播放
2、建议在 config.ini 中添加电影路径，这样就不用把软件和电影放在同一目录了，同时success_output_folder和failed_output_folder可以改成绝对路径
3、建议增加“记录处理过的电影”的功能，方便下完想继续上传的仓鼠党

**Comment by yoshiko2** [comment]
嗯。。。有点难搞尽力吧
