### ISSUE TITLE
linux使用问题

### ISSUE THREAD

**Issue by lingwangchao** [yoshiko2/AV_Data_Capture#23]
本来我就随便下载点视频，然后发现了Emby觉得还不错，那个人还发了这个东西，然后下载测试了一下，很不错还可以弄到Linux上，Linux我也弄上了Emby，配合这个，然后呢？启动没教程我对python这个软件也就知道还没去玩过，然后查找怎么使用，./AV_Data_Capture.py 就可以运行了，和shell一样，执行发现库文件没指向，要在文件内定义路径，觉得很麻烦，然后继续查找，python AV_Data_Capture.py就不用指向库文件了，运行，报错了，报错原因使用了ascll以外的编码(自然是因为中文)，文件开头添加# -*- coding: utf-8 -*-解决了，然后又遇上了一个问题，with open("config.ini", "wt", encoding='UTF-8') as code:(报这行的错误，打开个文件也能出错)，突然想把python版本更新一下这次用3.7.4，之前是2.7，然后执行直接缺少模块，刚安装没模块也很正常，这次ascll的错误也消失了，打开文件报错也消失了真神奇，这件报JSON错误，看了教程，想起了昨晚刚装代理，我端口不是1080，改一下就好了，然后又一个错误if config['directory_capture']['switch'] == '0' or config['directory_capture']['switch'] == '':一个if语句也能报错，各种查找，都找不到解决方法，然后没办法靠自己，（我觉得是这里出问题config['directory_capture']['switch']），这好像一个数组，config又是怎么来的 config = ConfigParser()调用了一个类，from configparser import ConfigParser 类产于这里，调用了内置的模块，但是如果内容是出于文件本身根本就不可能出错，然后盯上了directory_capture，因为KeyError:“directory_capture”，我又不知道代表什么意思，最后去搜索KeyErrot的信息，得出了一个结果就是config['directory_capture']不存在，根本就没定义，虽然if语句判断了config['directory_capture']['switch'] =空，但是这个变量根本就不存在，最后查找这个变量的来源，来源于ADC_function.py中的print("[directory_capture]", file=code)，而数值来自config.ini文件的定义，我打开看了里面就只有[proxy][Name_Rule][update]，三个，而window那个exe执行的里面有[proxy][Name_Rule][update][media][directory_capture]，五个，然后我复制了进去，运行成功，罪魁祸首就是你，害我浪费了6个小时，我本来就是下载点东西，结果好了，变成了学习python,最后测试是成功的了但是Linux却无法从网上下载到内容，没有任何的错误信息直接
[root@localhost HEYZO]# python AV_Data_Capture.py
[*]===========AV Data Capture===========
[*]           Version 0.11.6
[*]=====================================
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.
[+][+]按回车键结束，你可以在结束之前查看和错误信息。
而window却是可以获取到内容，有没有人在Linux上可以获取内容的，突然一个想法就是2.7运行会不会成功？
没想到又给我报了一个错误，恩，挺好的
[root@localhost AV_Data_Capture-0.11.6]# python2.7 AV_Data_Capture.py
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 7, in <module>
    from ADC_function import *
  File "/data/video/AV_Data_Capture-0.11.6/ADC_function.py", line 20
    print("[proxy]",file=code)
                        ^
SyntaxError: invalid syntax

**Comment by lingwangchao** [comment]
为什么Linux会直拿不到东西呢？问题和我猜想的一样就是路径，在window的路径是\，但是到了Linux的路径是/，改掉就可以了，我就知道作者自己在window测试好了就弄上来了，Linux自己摸索去吧

**Comment by yoshiko2** [comment]
你可以linux装smb，在win下挂载smb为磁盘再用软件 @lingwangchao

**Comment by yoshiko2** [comment]
或者你pull requests来修复代码 @lingwangchao

**Comment by yoshiko2** [comment]
11.7修复了
