### ISSUE TITLE
Mac上运行问题

### ISSUE THREAD

**Issue by maruihhy** [yoshiko2/AV_Data_Capture#231]
请教一下，Mac上打包程序如何运行？AV_Data_Capture 这个文件也没后缀，该如何运行？

**Comment by 68cdrBxM8YdoJ** [comment]
You can run the downloaded binary from the terminal.
Or just double click binary from finder (probably need execution privileges).

something like this in terminal.

```bash
$ curl -LO -H 'Accept: application/octet-stream' https://github.com/yoshiko2/AV_Data_Capture/releases/download/3.3/AV_Data_Capture-CLI-MacOS-3.3.zip
$ unzip AV_Data_Capture-CLI-MacOS-3.3.zip
$ chmod +x AV_Data_Capture
$ ./AV_Data_Capture
```

**Comment by maruihhy** [comment]
还有个问题，mac上无论是源码还是打包程序，配置如下时：

> [Name_Rule]
location_rule = '#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule = title

好像命名不正确 文件夹命名为：[2019] HUNTA-590 [HUNTA-590]
中间是番号但配置应该是名称

终端调试模式输出时数据是扒下来了的，调试数据如下：

> [+] ---Debug info---
[+]  - actor       :
[+]  - cover       : https://pics.javbus.com/cover/72qx_b.jpg
[+]  - director    : ボルボ中野
[+]  - imagecut    : 1
[+]  - label       :
[+]  - number      : HUNTA-590
[+]  - outline     : 305 characters
[+]  - release     : 2019-05-04
[+]  - runtime     :  240分鐘
[+]  - source      : javbus.py
[+]  - studio      : Hunter
[+]  - tag         : ['中出', 'DMM獨家', '和服・喪服', '姐妹', '4小時以上作品', '高畫質', '旅行']
[+]  - title       : 超美尻がボクの目の前3センチ！！えっ！？そのプルンと突き出した綺麗すぎるお尻はボクを誘っているの？ボクに突然、可愛くて優しくてしかも美尻の義姉ができたんです！！義姉はとにかくお尻が綺麗でスタイル抜群のドスケベな体をした女性です！！家族になって初めての…
[+]  - website     : https://www.javbus.com/HUNTA-590
[+]  - cover_small :
[+]  - naming_rule : 超美尻がボクの目の前3センチ！！えっ！？そのプルンと突き出した綺麗すぎるお尻はボクを誘っているの？ボクに突然、可愛くて優しくてしかも美尻の義姉ができたんです！！義姉はとにかくお尻が綺麗でスタイル抜群のドスケベな体をした女性です！！家族になって初めての…
[+]  - location_rule : #/[2019] HUNTA-590 [HUNTA-590]
[+]  - actor_list  : ['']
[+] ---Debug info---

在windows下的CLI和GUI都没这个问题，且配置一样。

**Comment by 68cdrBxM8YdoJ** [comment]
Can you download the binary here and try it out?
https://github.com/yoshiko2/AV_Data_Capture/actions/runs/92790548

**Comment by maruihhy** [comment]
刚刚测试了，新版已经解决了命名的问题！

但是搜索番号的时候像HUNTA740.mp4，番号会识别成HUNTA740而不是HUNTA-740，命名是也会用HUNTA740，windows版本好像没这个问题，感觉番号不统一。

> [+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [./HUNTA740/HUNTA740.mp4], the number is [HUNTA740]
[+] ---Debug info---
[+]  - actor       :
[+]  - cover       : https://pics.dmm.co.jp/mono/movie/adult/hunta740/hunta740pl.jpg
[+]  - director    : モリキ
[+]  - imagecut    : 1
[+]  - label       : ----
[+]  - number      : hunta740
[+]  - outline     : 200 characters
[+]  - release     : 2020-03-19
[+]  - runtime     : 240
[+]  - source      : fanza.py
[+]  - studio      : Hunter
[+]  - tag         : ['ランジェリー', '淫乱・ハード系', '中出し', 'ハーレム', '4時間以上作品', 'サンプル動画', '35％OFFセール']
[+]  - title       : 『やだ～最悪！濡れちゃった…』『ウケる！下着透けてるんだけど！』『自分もじゃん！！』お姉ちゃんと女友達たちが酔っ払ってビショ濡れ下着スケ…
[+]  - website     : https://www.dmm.co.jp/mono/dvd/-/detail/=/cid=hunta740
[+]  - cover_small :
[+]  - naming_rule : 『やだ～最悪！濡れちゃった…』『ウケる！下着透けてるんだけど！』『自分もじゃん！！』お姉ちゃんと女友達たちが酔っ払ってビショ濡れ下着スケ…
[+]  - location_rule : #/[2020] 『やだ～最悪！濡れちゃった…』『ウケる！下着透けてるんだけど！』『自分もじゃん！！』お姉ちゃんと女友達たちが酔っ払ってビショ濡れ下着スケ… [hunta740]
[+]  - actor_list  : ['']
[+] ---Debug info---
[+]Image Downloaded! JAV_output/#/[2020] 『やだ～最悪！濡れちゃった…』『ウケる！下着透けてるんだけど！』『自分もじゃん！！』お姉ちゃんと女友達たちが酔っ払ってビショ濡れ下着スケ… [hunta740]/hunta740-fanart.jpg
[+]Image Cutted!     JAV_output/#/[2020] 『やだ～最悪！濡れちゃった…』『ウケる！下着透けてるんだけど！』『自分もじゃん！！』お姉ちゃんと女友達たちが酔っ払ってビショ濡れ下着スケ… [hunta740]/hunta740-poster.jpg
[+]Wrote!            JAV_output/#/[2020] 『やだ～最悪！濡れちゃった…』『ウケる！下着透けてるんだけど！』『自分もじゃん！！』お姉ちゃんと女友達たちが酔っ払ってビショ濡れ下着スケ… [hunta740]/hunta740.nfo
[*]======================================================

**Comment by 68cdrBxM8YdoJ** [comment]
It's weird, the numbers are supposed to be parsed the same, regardless of the OS.
