### ISSUE TITLE
JAVDB download is fail

### ISSUE THREAD

**Issue by LeoNg628** [yoshiko2/AV_Data_Capture#233]
[!]Making Data for [.\ARA-331.mp4], the number is [ARA-331]
[-] [.\ARA-331.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\ARA-331.mp4] to failed folder

It could be found in JAVDB site, but the program could not recognize it....please help.

JAVDB result:
https://javdb.com/v/qOAAe

**Comment by 68cdrBxM8YdoJ** [comment]
Are you using the latest version?
I can't reproduce the problem.

**Comment by LeoNg628** [comment]
> Are you using the latest version?
> I can't reproduce the problem.

Yes, I've download "AV_Data_Capture-CLI-Windows-3.3.zip"

and here is my config setting:
`[common]
main_mode=1
failed_output_folder=failed
success_output_folder=JAV_output
soft_link=0

[proxy]
proxy=
timeout=10
retry=3

[Name_Rule]
location_rule = '#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule= title

[update]
update_check=1

[priority]
website=javbus,javdb,fanza,xcity,mgstage,fc2,avsox,jav321

[escape]
literals=\()/
folders=failed,JAV_output

[debug_mode]
switch=0`

**Comment by 68cdrBxM8YdoJ** [comment]
I can't reproduce it :(
A new version has been released, can I try it out?
https://github.com/yoshiko2/AV_Data_Capture/releases/tag/3.4

**Comment by LeoNg628** [comment]
> I can't reproduce it :(
> A new version has been released, can I try it out?
> https://github.com/yoshiko2/AV_Data_Capture/releases/tag/3.4

hi thanks for your update, I've downloaded and tried, here is the result:

`[*]================== AV Data Capture ===================
[*]                     Version 3.4
[*]======================================================
[+]Find 11 movies
[!] - 9.09% [1/11] -
[!]Making Data for [.\ARA-331.mp4], the number is [ARA-331]
[-] [.\ARA-331.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\ARA-331.mp4] to failed folder
[!] - 18.1% [2/11] -
[!]Making Data for [.\ARA-393.mp4], the number is [ARA-393]
[-] [.\ARA-393.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\ARA-393.mp4] to failed folder
[!] - 27.2% [3/11] -
[!]Making Data for [.\ARA-398.mp4], the number is [ARA-398]
[-] [.\ARA-398.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\ARA-398.mp4] to failed folder
[!] - 36.3% [4/11] -
[!]Making Data for [.\HND-776.mp4], the number is [HND-776]
[-] [.\HND-776.mp4] ERROR:
[-] [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'JAV_output/#神宮寺ナオ/[2020] 相部屋×NTR報告-1年ぶりに再会した片想いの幼馴染とお酒を飲んで一人暮らしの部屋で二人きり-まさか…！を期待していたら今彼とのイチャラブ中出し話を朝まで 赤裸々告白されて鬱勃起した僕。-神宮寺ナオ [HND-776]'
[-]Move [.\HND-776.mp4] to failed folder
[!] - 45.4% [5/11] -
[!]Making Data for [.\HUNTA-320.mp4], the number is [HUNTA-320]
[-] [.\HUNTA-320.mp4] ERROR:
[-] [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'JAV_output/#蓮実クレア,吉川あいみ,桃瀬ゆり,日比乃さとみ,三島奈津子/[2017] 真面目な私たち夫婦が妹夫婦と旦那を交換してセックス？姉妹夫婦スワッピング！超遊び人の妹夫婦に乗せられて真面目な私の旦那と妹の旦那を交換してエッチしちゃいました！ [HUNTA-320]'
[-]Move [.\HUNTA-320.mp4] to failed folder
[!] - 54.5% [6/11] -
[!]Making Data for [.\HUNTA-494 cd2.mp4], the number is [HUNTA-494]
[+]Image Downloaded! JAV_output/#羽月希,枢木みかん,小川桃果,桜ちなみ,天野弥生,水嶋アリス,真白ここ,沖田里緒,宮川ありさ,皆瀬杏樹/[2018] バツイチアラサー女子しかいないシェアハウスに男はボク1人だけ！2-彼女が欲しい！出会いを求めてボクが入居した シェアハウスは、バツイチの… [HUNTA-494]/HUNTA-494-fanart.jpg
[+]Image Cutted!     JAV_output/#羽月希,枢木みかん,小川桃果,桜ちなみ,天野弥生,水嶋アリス,真白ここ,沖田里緒,宮川ありさ,皆瀬杏樹/[2018] バツイチアラサー女子しかいないシェアハウスに男はボク1人だけ！2-彼女が欲しい！出会いを求めてボクが入居した シェアハウスは、バツイチの… [HUNTA-494]/HUNTA-494-poster.jpg
[+]Wrote!            JAV_output/#羽月希,枢木みかん,小川桃果,桜ちなみ,天野弥生,水嶋アリス,真白ここ,沖田里緒,宮川ありさ,皆瀬杏樹/[2018] バツイチアラサー女子しかいないシェアハウスに男はボク1人だけ！2-彼女が欲しい！出会いを求めてボクが入居した シェアハウスは、バツイチの… [HUNTA-494]/HUNTA-494.nfo
[*]======================================================
[!] - 63.6% [7/11] -
[!]Making Data for [.\LUXU-1136.mp4], the number is [LUXU-1136]
[-] [.\LUXU-1136.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\LUXU-1136.mp4] to failed folder
[!] - 72.7% [8/11] -
[!]Making Data for [.\SIRO-4052.mp4], the number is [SIRO-4052]
[-] [.\SIRO-4052.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\SIRO-4052.mp4] to failed folder
[!] - 81.8% [9/11] -
[!]Making Data for [.\SIRO-4107.mp4], the number is [SIRO-4107]
[-] [.\SIRO-4107.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\SIRO-4107.mp4] to failed folder
[!] - 90.9% [10/11] -
[!]Making Data for [.\SIRO-4149.mp4], the number is [SIRO-4149]
[-] [.\SIRO-4149.mp4] ERROR:
[-] 'NoneType' object has no attribute 'xpath'
[-]Move [.\SIRO-4149.mp4] to failed folder
[!] - 100.% [11/11] -
[!]Making Data for [.\SW-544.mp4], the number is [SW-544]
[-] [.\SW-544.mp4] ERROR:
[-] [WinError 123] 檔案名稱、目錄名稱或磁碟區標籤語法錯誤。: 'JAV_output/#推川ゆうり,君島みお/[2018] 兄貴の嫁さん達のゴ ージャス大人ボインが目の前に！独身の僕の下の世話まで焼いてくれるのは、兄貴のチ○ポじゃ満足できず、オナニーばかりして頑丈になりすぎた僕のチ○ポを根元まで挿し込みたいからです [SW-544]'
[-]Move [.\SW-544.mp4] to failed folder
[+]Deleting empty folder JAV_output/#推川ゆうり,君島みお
[+]Deleting empty folder JAV_output/#神宮寺ナオ
[+]All finished!!!
[+][+]Press enter key exit, you can check the error message before you exit.`
