### ISSUE TITLE
修改config.in文件不生效

### ISSUE THREAD

**Issue by pkr5277** [yoshiko2/AV_Data_Capture#241]
运行一直Connect Failed! Please check your Proxy or Network! ，即使删掉proxy后面的地址，ssr开全局模式也是这样，把重试次数设置成5，终端仍然显示重试3次，我是mac系统

**Comment by pkr5277** [comment]
提示我找不到config.ini文件，我明明把执行程序和ini文件放在一个文件夹了

**Comment by laoyang945** [comment]
因为作者这里写错了
