### ISSUE TITLE
软件打开闪退或无法连接

### ISSUE THREAD

**Issue by wangyangwazi** [yoshiko2/AV_Data_Capture#246]
开了ssr能正常连接外网，软件连接的几个网站也能正常访问，软件也重装过，请问怎么解决

**Comment by wangyangwazi** [comment]
使用路由器翻墙的时候显示是AttributeError:'NoneType' object has no attribute 'group'
Failed to execute script AV_Data_Capture
pc上就是连不上

**Comment by wangyangwazi** [comment]
以下为完整的错误信息
[*]================== AV Data Capture ===================
[*]                     Version 3.4
[*]======================================================
[+]Find 5 movies
[!] - 20.0% [1/5] -
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 133, in <module>
  File "AV_Data_Capture.py", line 72, in create_data_and_move
  File "number_parser.py", line 38, in get_number
AttributeError: 'NoneType' object has no attribute 'group'
[24648] Failed to execute script AV_Data_Capture

**Comment by wangyangwazi** [comment]
换到v3.3问题解决了。。。。

**Comment by xingfanxia** [comment]
@wangyangwazi 我也遇到这个 `NoneType` 问题。。
