### ISSUE TITLE
在使用Python2作为默认版本的某些系统中, 使用os.system()调用core.py会导致错误

### ISSUE THREAD

**Issue by RRRRRm** [yoshiko2/AV_Data_Capture#25]
`RunCore()` 函数中用 `os.system()` 调用 `core.py`, 会使用Python2. 
导致 `print("<movie>", file=code)`出错

**Comment by yoshiko2** [comment]
现在是python3时代了，怎么还用python2，汗。。。 @RRRRRm

**Comment by RRRRRm** [comment]
> 现在是python3时代了，怎么还用python2，汗。。。 @RRRRRm

我想部署在一个NAS系统  [OpenMediaVault](https://www.openmediavault.org/) 上面. 它默认就是Python2, 而且改了好像会出问题 (大哭.jpg)

**Comment by RRRRRm** [comment]
> 现在是python3时代了，怎么还用python2，汗。。。 @RRRRRm

这个项目好好玩啊, 接受提交吗

**Comment by yoshiko2** [comment]
那当然接受提交，🍺🍺那么多不如pull request好 @RRRRRm

**Comment by RRRRRm** [comment]
已经提交过啦 @yoshiko2

**Comment by yoshiko2** [comment]
代码有点问题，明天我回退一下 @RRRRRm

**Comment by RRRRRm** [comment]
抱歉抱歉, 把开发中的功能也提交上去了. 分支还不太会用...
指定Python3环境和异步调用那段应该是没问题的, 然后我想继续加一个指定任意文件夹的, 结果一并提交上去了😅.

> 代码有点问题，明天我回退一下 @RRRRRm

**Comment by yoshiko2** [comment]
> 抱歉抱歉, 把开发中的功能也提交上去了. 分支还不太会用...
> 指定Python3环境和异步调用那段应该是没问题的, 然后我想继续加一个指定任意文件夹的, 结果一并提交上去了😅.
> 
> > 代码有点问题，明天我回退一下 @RRRRRm

最好不要用异步处理，速度过快容易封IP，我的代码本身就是抓取完一部片休眠三秒，现在就暂时先修复好Linux和macoos环境下运行的BUG @RRRRRm
