### ISSUE TITLE
FC2系列番号解析问题

### ISSUE THREAD

**Issue by Apocalypsor** [yoshiko2/AV_Data_Capture#250]
命名格式若为`FC2PPV-1231231`

```filename = filename.replace('-PPV', '').replace('PPV-', '').replace('FC2PPV-', 'FC2-').replace('FC2PPV_', 'FC2-')```
会导致中间的短横线被`.replace('PPV-', '')`替换掉而识别错误

**Comment by yoshiko2** [comment]
批量把PPV去掉

**Comment by Apocalypsor** [comment]
建议改成
```
filename = filename.replace('FC2PPV-', 'FC2-').replace('-PPV', '').replace('PPV-', '')
filename = filename.replace('FC2PPV-', 'FC2-').replace('-ppv', '').replace('ppv-', '')
```
即可
