### ISSUE TITLE
window 3.4 版本无法运行

### ISSUE THREAD

**Issue by chyaww** [yoshiko2/AV_Data_Capture#252]
感谢@yoshiko2辛苦付出
不懂编程，做个伸手党，3.4版本地运行出错，确认代理没有问题，具体报错信息如下：
[*]================== AV Data Capture ===================
[*]                     Version 3.4
[*]======================================================
[-] Check update failed! Skipped.
[+]Find 4 movies
[!] - 25.0% [1/4] -
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 133, in <module>
  File "AV_Data_Capture.py", line 72, in create_data_and_move
  File "number_parser.py", line 38, in get_number
AttributeError: 'NoneType' object has no attribute 'group'
[1136] Failed to execute script AV_Data_Capture

**Comment by 68cdrBxM8YdoJ** [comment]
Tell me the number that will fail.

**Comment by LeoNg628** [comment]
![2020-06-22 23_28_40-LeoVivoPC](https://user-images.githubusercontent.com/64629978/85305898-45815800-b4e0-11ea-9763-0460c645c945.png)
same issue here, even I've upgrade to 3.5....could you help? Thanks a lot.

**Comment by LeoNg628** [comment]
I may found the problem cause, when I try to capture below video, the program will get sucks.......
- AP-027
- DANDY series
- ATOM series
- DVDES series

Also it show me below error when the title name is too long?
![2020-06-23 01_26_34-LeoVivoPC](https://user-images.githubusercontent.com/64629978/85317245-a87aeb00-b4f0-11ea-91f3-e9abad6e01d9.png)

**Comment by yoshiko2** [comment]
The locaition rule may be too long

**Comment by LeoNg628** [comment]
> The locaition rule may be too long

Thanks, I've remove the title and it works.
