### ISSUE TITLE
关于识别xxx-av-000000(6位数字)和javdb的解析问题

### ISSUE THREAD

**Issue by oury-fln** [yoshiko2/AV_Data_Capture#253]
1. 类型的番号无法正确识别，只能识别为xxx-av，从而造成识别错误；
2. 该类型番号可通过javdb找到；
3. javdb的数据抓取部分存在错误（可能是网页变化/代理导致的语言问题？），如actor抓取失败，xpath解析改为 html.xpath('//strong[contains(text(),"演員")]/../span/a/text()')则可以成功，类似还有studio、runtime、tag等；getTag() 中的定位文字”类别“应为繁体”類別“；getRuntime() 中，网页上的时间单位为”分鐘“，可以使用filter去除非数字部分；getCover_small() 中的div class定位内容，应改为 "//div[@class='item-image ']/img/@src"
4. 感谢员原作者（们）的付出！

**Comment by yoshiko2** [comment]
用拖动法

**Comment by chopinsun** [comment]
建议作者搞一个番号字典，通过字典做名称识别和名称修正，再去抓取就会更加准确，字典可以在每次启动时从服务端更新。将字典放在社区，由社区aver们完善就好
