### ISSUE TITLE
命名参数请增加 series

### ISSUE THREAD

**Issue by marcushsu** [yoshiko2/AV_Data_Capture#261]
很多影片都是以系列为卖点，目录命名参数少了 series 的话，整理起来不方便。

**Comment by yoshiko2** [comment]
label或者studio参数

**Comment by marcushsu** [comment]
> label或者studio参数

不太一样。譬如，想把【マジックミラー号】这个系列的整理在一个文件夹下，用label或者studio参数就做不到。

**Comment by marcushsu** [comment]
虽然我不会写Python，但是我还是好奇看了下代码，发现我们的落差了。
![image](https://user-images.githubusercontent.com/11764515/85104667-8efd4900-b23b-11ea-8169-022b610b31e8.png)
按照这段代码，Label这个参数爬的是影片页面上シリーズ后面的值，但是シリーズ是Series的意思，レーベル才是Label呀。
![image](https://user-images.githubusercontent.com/11764515/85104803-daaff280-b23b-11ea-82bf-d10cf6cebdbe.png)

可是，就算我先将错就错把Label当做シリーズ来用，我却发现所有片子nfo的Label怎么都是空的。譬如118abp00933（ABP-033）的搜刮结果：
![image](https://user-images.githubusercontent.com/11764515/85105143-83f6e880-b23c-11ea-97ea-36126048eabf.png)
