### ISSUE TITLE
文件名称识别问题

### ISSUE THREAD

**Issue by lbbboy** [yoshiko2/AV_Data_Capture#262]
Making Data for [.\CARIB-xxxx-xxxx.mp4], the number is [CARIB-xxxx]

这个只能手动重命名在爬吗？

**Comment by yoshiko2** [comment]
类似命名要删掉前面片商名，变成xxx-xxxxx

**Comment by LeoNg628** [comment]
> Making Data for [.\CARIB-xxxx-xxxx.mp4], the number is [CARIB-xxxx]
> 
> 这个只能手动重命名在爬吗？

你番號好像對不上？
該是這樣：caribbean-100318-765

**Comment by yoshiko2** [comment]
100318-765
