### ISSUE TITLE
OKP-001/002的錯誤

### ISSUE THREAD

**Issue by marcushsu** [yoshiko2/AV_Data_Capture#265]
![image](https://user-images.githubusercontent.com/11764515/84770652-8540cf00-b00a-11ea-9e04-02519b95da6d.png)

配置：
![image](https://user-images.githubusercontent.com/11764515/84770729-a99cab80-b00a-11ea-9c1e-80ec999bcfb8.png)

**Comment by LeoNg628** [comment]
你刮檔網站的排序改一下就好，除非你比較多fanza xcity和fc2的片子，不然把jav321 javdb和javbus放最前效果最好

**Comment by marcushsu** [comment]
我比较喜欢原文的说名，所以顺序这样排。不过，我也试过把javbus/javdb放前面，但是没用。其实程序自动按顺序一个个搜刮下去，影响的只是整体速度，对有没有搜刮到内容的结果影响不大。
后来我直接上dmm官网发现还是得用cid 1okp001才能搜寻到，把档名改成1okp001就可以正常搜刮到了。
