### ISSUE TITLE
Connect Failed! Please check your Proxy or Network!

### ISSUE THREAD

**Issue by ZhaoqiangCn** [yoshiko2/AV_Data_Capture#268]
每刮削一个文件就提示一次，按下回车又可以正常刮，，

**Comment by ZhaoqiangCn** [comment]
[*]======================================================
[!] - 87.5% [7/8] -
[!]Making Data for [.\jbd240.mp4], the number is [jbd240]
[-]Connect retry 1/1
[-]Connect Failed! Please check your Proxy or Network!
Press ENTER to exit!
[+]Image Downloaded! JAV_output/松下紗栄子/jbd240/jbd240-fanart.jpg
[+]Image Cutted!     JAV_output/松下紗栄子/jbd240/jbd240-poster.jpg
[+]Wrote!            JAV_output/松下紗栄子/jbd240/jbd240.nfo
[*]======================================================

**Comment by LeoNg628** [comment]
我有試過這問題，原因是新版本的config檔跟之前不一樣，你要手動改一下，proxy欄位要清空，然後存檔

**Comment by ZhaoqiangCn** [comment]
> 我有試過這問題，原因是新版本的config檔跟之前不一樣，你要手動改一下，proxy欄位要清空，然後存檔

Proxy已经清空=号后面的内容了，似乎还是不行
