### ISSUE TITLE
0.11.7-win下siro系列使用release参数导致目录创建错误

### ISSUE THREAD

**Issue by oweaF** [yoshiko2/AV_Data_Capture#27]
config中的name rule
`location_rule='JAV_output/'+actor+'/'+'['+release+']'+' '+number`
`naming_rule=number+'-'+title`
siro获得的release里面有'/'，会出现创建多级目录的情况。

**Comment by yoshiko2** [comment]
截图 @oweaF

**Comment by oweaF** [comment]
![image](https://user-images.githubusercontent.com/25154231/62617534-a9d90e80-b944-11e9-864a-621226f5b3f5.png)
一层：[2018
二层：09
三层：29] SIRO-3607
