### ISSUE TITLE
只想获取nfo信息和图片，不想移动文件夹，有没有办法实现？

### ISSUE THREAD

**Issue by yhf7952** [yoshiko2/AV_Data_Capture#270]
如题。使用整理方式或开启软链接，下载的文件都会归到“success_output_folder”

有没有一个选项，或者方法，让下载到的nfo和图片，直接放到原始影片目录？

**Comment by tianqiawuhui** [comment]
配置里 soft_link=1  但作者快捷路径指向 写的有问题 得自己修改core.py

**Comment by tianqiawuhui** [comment]
> 如题。使用整理方式或开启软链接，下载的文件都会归到“success_output_folder”
> 
> 有没有一个选项，或者方法，让下载到的nfo和图片，直接放到原始影片目录？

配置里 soft_link=1 但作者快捷路径指向 写的有问题 得自己修改core.py
