### ISSUE TITLE
3.5版本地运行出错，运行之后闪退

### ISSUE THREAD

**Issue by virtue050** [yoshiko2/AV_Data_Capture#273]
再次感谢@yoshiko2辛苦付出
不懂编程，3.5版本地运行出错，确认代理没有问题，具体报错信息如下：
![image](https://user-images.githubusercontent.com/49637668/86504770-68204480-bdef-11ea-822d-641c00db6c0f.png)

**Comment by yoshiko2** [comment]
番号问题
