### ISSUE TITLE
番号提取/文件名识别报错 line 37 in get_number 请在本帖发出文件名

### ISSUE THREAD

**Issue by yoshiko2** [yoshiko2/AV_Data_Capture#274]

**Comment by walthack** [comment]
3.52版本貌似修正了直接闪退的问题，APB985显示 list index out of range.

**Comment by gydisme** [comment]
如果是非數字title閃退也要回報嗎?
找不到數字是否應該是要跳過該影片? 如果是的話我有遇到一片XD

[教學]加籐鷹-秘技傳授（潮吹之入門）.rmvb

**Comment by rwrwrrrr** [comment]
010413_507           020412_270

**Comment by lijian12345** [comment]
050520-001 被识别成了 050520_001

**Comment by marshalliu** [comment]
n0047-cd1无法识别出n0047

**Comment by PlayerYao** [comment]
番号WHY系列,例如WHY-58,识别出来是空的,所有why似乎都识别不出来

**Comment by shashamajie** [comment]
SIRO-3759 这种番号无法识别

**Comment by shashamajie** [comment]
yrz-004 这个番号死活识别不到

**Comment by dizzycatz** [comment]
x-art.xx.xx.xx這類型的會被視為成[x-art]
改成xart.xx.xx.xx雖可以抓到number，但總是movie data not found 
已確認javdb上有資料
