### ISSUE TITLE
功能请求：自定义视频文件名

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#28]
目前的版本11.7视频文件名不能自定义，只能是 
 ` CJOD-182.mp4  `
希望可以加入一个自定义视频文件名的设置项，可以输出如下所示的文件名
`  CJOD-182 痴女ヘブン 深田えいみ 2019-04-25.mp4  `
  > 之前一直用JavHelper格式化文件名，使用的规则是 番号+制作公司+女优名字+发行时间
> `%ProductNumber%` %Maker% %Name% %ReleaseDate%

**Comment by yoshiko2** [comment]
https://github.com/yoshiko2/AV_Data_Capture#%E5%8F%AF%E9%80%89%E8%AE%BE%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9B%AE%E5%BD%95%E5%92%8C%E5%BD%B1%E7%89%87%E9%87%8D%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99 @Mosney 不支持自定义命名MP4，而且没必要
