### ISSUE TITLE
希望在ini文件中提供更多的自定义功能

### ISSUE THREAD

**Issue by markawonge** [yoshiko2/AV_Data_Capture#282]
1. [Name_Rule]中似乎只能自定义文件夹名称，不能自定义生成的文件名，如[ABC123] XXXXX.mp4/nfo/jpg；
2.目前抓取的图片文件后缀(-poster.jpg -fanart.jpg -thumb.jpg)为自动生成，无法自定义，比如增加一个无后缀的jpg。

**Comment by gydisme** [comment]
支持第一點, 刷完才發現檔名沒有被重新命名, 建議增加選項"file_renaming_rule"

**Comment by zaaazaa** [comment]
同支持第一点，这样命名时更灵活
