### ISSUE TITLE
希望支持 iso 格式的原盘影片

### ISSUE THREAD

**Issue by qianxu2001** [yoshiko2/AV_Data_Capture#294]

**Comment by qianxu2001** [comment]
我自己试一下

**Comment by qianxu2001** [comment]
失败了，报错`'NoneType' object has no attribute 'group'`，我还是等开发者做支持吧

**Comment by qiqiandfei** [comment]
你直接新建一个txt文档，然后用iso的番号重命名，在然后修改txt后缀为mp4，执行削刮，削刮完成后删掉mp4文件，把iso文件挪过来就好了

**Comment by qianxu2001** [comment]
> 你直接新建一个txt文档，然后用iso的番号重命名，在然后修改txt后缀为mp4，执行削刮，削刮完成后删掉mp4文件，把iso文件挪过来就好了

那我直接照我这样改也行，虽然电影会进 faith 文件夹，不过 av 文件夹也能生成对应的文件夹，我自己放进去了

**Comment by qianxu2001** [comment]
> 你直接新建一个txt文档，然后用iso的番号重命名，在然后修改txt后缀为mp4，执行削刮，削刮完成后删掉mp4文件，把iso文件挪过来就好了

已经有新的 commit 支持了，close 了

**Comment by qianxu2001** [comment]
已经有新的 commit 支持了，close 了
