### ISSUE TITLE
010110-258-carib-whole_hd2可以识别番号，但是刮削信息失败

### ISSUE THREAD

**Issue by jimaojun** [yoshiko2/AV_Data_Capture#298]
010110-258-carib-whole_hd2可以识别番号，但是刮削信息失败
![image](https://user-images.githubusercontent.com/63762052/90350782-c425ec00-e070-11ea-8c3b-38d119633b12.png)

**Comment by LucQin** [comment]
我也有同样的问题

**Comment by LucQin** [comment]
这个GUI版本的（https://github.com/moyy996/AVDC）好像可以。我成功了
