### ISSUE TITLE
对于影片分类感觉按演员分，还是有一些值得讨论的点。

### ISSUE THREAD

**Issue by NJCCJohnWason** [yoshiko2/AV_Data_Capture#3]
单个作品之间其实没有关系，我觉得就以单独的番号，作为文件夹结构就好。
比如出演的演员，制作方，发行方，导演，系列，都是一个番号的**属性**，直接的关系是弱连接、多对多的，如果以上所说的都不知道，那是这个番号也存在，比如JUFE还是URE有个蒙脸PLAY的项目，出演的是谁只能靠猜，女优如果未知，就没法分了。
就实际的模型来说，其他的属性都可以实际加到NFO中，能够看到他的这些信息，就可以了。
刚从 https://pockies.github.io/2019/03/25/everaver-emby-kodi/ 里看到您的git库，觉得非常好！
大赞！
期望能够对你的项目有些用处

**Comment by wenead99** [comment]
感谢你的提议，我在Beta 10当中添加了自定义目录功能和自定义命名功能。

**Comment by NJCCJohnWason** [comment]
不好意思，没看完全。修改Locationrule 只能在.py里修改吗？
还有就是遇到 PT-174这个番号 存在两个分集的影片，就直接FAIL了
是不是可以加入 -CD1 CD2 01 02 的分集识别功能呢
PT-174 
magnet:?xt=urn:btih:dbdaa7037e0f080240cb51448844f6318ebe4973&dn=Airi%20Mashiro%20(PT-174)%20%5b1080p%5d&tr=udp%3a%2f%2fexodus.desync.com%3a6969&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.open-internet.nl%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=http%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce&tr=http%3a%2f%2ftracker.internetwarriors.net%3a1337%2fannounce&tr=udp%3a%2f%2f9.rarbg.to%3a2710%2fannounce&tr=udp%3a%2f%2f9.rarbg.me%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80%2fannounce&tr=udp%3a%2f%2fexodus.desync.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.tiny-vps.com%3a6969%2fannounce&tr=udp%3a%2f%2fthetracker.org%3a80%2fannounce&tr=udp%3a%2f%2fretracker.lanta-net.ru%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.torrent.eu.org%3a451%2fannounce&tr=udp%3a%2f%2fdenis.stalker.upeer.me%3a6969%2fannounce&tr=udp%3a%2f%2fbt.xxx-tracker.com%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.cyberia.is%3a6969%2fannounce&tr=http%3a%2f%2fopen.acgnxtracker.com%3a80%2fannounce&tr=udp%3a%2f%2fopen.stealth.si%3a80%2fannounce&tr=udp%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=http%3a%2f%2fexplodie.org%3a6969%2fannounce&tr=udp%3a%2f%2fipv4.tracker.harry.lu%3a80%2fannounce&tr=udp%3a%2f%2ftracker.uw0.xyz%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.iamhansen.xyz%3a2000%2fannounce&tr=udp%3a%2f%2ftracker.filepit.to%3a6969%2fannounce&tr=udp%3a%2f%2fretracker.baikal-telecom.net%3a2710%2fannounce&tr=http%3a%2f%2ftracker.bz%3a80%2fannounce&tr=udp%3a%2f%2ftracker.nyaa.uk%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.filemail.com%3a6969%2fannounce&tr=http%3a%2f%2ft.nyaatracker.com%3a80%2fannounce&tr=http%3a%2f%2fgwp2-v19.rinet.ru%3a80%2fannounce&tr=udp%3a%2f%2fzephir.monocul.us%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.tvunderground.org.ru%3a3218%2fannounce&tr=udp%3a%2f%2ftracker.trackton.ga%3a7070%2fannounce&tr=udp%3a%2f%2ftracker.swateam.org.uk%3a2710%2fannounce&tr=udp%3a%2f%2ftracker.supertracker.net%3a1337%2fannounce&tr=udp%3a%2f%2ftracker.msm8916.com%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.moeking.me%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.fixr.pro%3a6969%2fannounce&tr=udp%3a%2f%2ftracker-udp.gbitt.info%3a80%2fannounce&tr=udp%3a%2f%2ftorrentclub.tech%3a6969%2fannounce&tr=udp%3a%2f%2fretracker.sevstar.net%3a2710%2fannounce&tr=udp%3a%2f%2fretracker.netbynet.ru%3a2710%2fannounce&tr=udp%3a%2f%2fretracker.maxnet.ua%3a80%2fannounce&tr=udp%3a%2f%2fretracker.akado-ural.ru%3a80%2fannounce&tr=udp%3a%2f%2fhome.penza.com.ru%3a6969%2fannounce&tr=udp%3a%2f%2fchihaya.toss.li%3a9696%2fannounce&tr=udp%3a%2f%2fcarapax.net%3a6969%2fannounce&tr=udp%3a%2f%2fbt.dy20188.com%3a80%2fannounce&tr=https%3a%2f%2ftracker.publictorrent.net%3a443%2fannounce&tr=https%3a%2f%2ftracker.gbitt.info%3a443%2fannounce&tr=https%3a%2f%2ftracker.fastdownload.xyz%3a443%2fannounce&tr=https%3a%2f%2ft.quic.ws%3a443%2fannounce&tr=http%3a%2f%2fweb4.obit.ru%3a80%2fannounce&tr=http%3a%2f%2fvps02.net.orel.ru%3a80%2fannounce&tr=http%3a%2f%2ftracker.tvunderground.org.ru%3a3218%2fannounce&tr=http%3a%2f%2ftracker.torrentyorg.pl%3a80%2fannounce&tr=http%3a%2f%2ftracker.publictorrent.net%3a80%2fannounce&tr=http%3a%2f%2ftracker.openzim.org%3a80%2fannounce&tr=http%3a%2f%2ftracker.gbitt.info%3a80%2fannounce&tr=http%3a%2f%2ftracker.bt4g.com%3a2095%2fannounce&tr=http%3a%2f%2ftorrent.nwps.ws%3a80%2fannounce&tr=http%3a%2f%2fretracker.sevstar.net%3a2710%2fannounce&tr=http%3a%2f%2fretracker.joxnet.ru%3a80%2fannounce&tr=http%3a%2f%2fopen.trackerlist.xyz%3a80%2fannounce&tr=http%3a%2f%2fcarapax.net%3a6969%2fannounce&tr=udp%3a%2f%2ftracker.justseed.it%3a1337%2fannounce&tr=https%3a%2f%2ftracker.vectahosting.eu%3a2053%2fannounce&tr=https%3a%2f%2ftracker.parrotsec.org%3a443%2fannounce&tr=https%3a%2f%2f1337.abcvg.info%3a443%2fannounce&tr=http%3a%2f%2ft.acg.rip%3a6699%2fannounce&tr=http%3a%2f%2fshare.camoe.cn%3a8080%2fannounce&tr=http%3a%2f%2fmail2.zelenaya.net%3a80%2fannounce&tr=http%3a%2f%2fbt-tracker.gamexp.ru%3a2710%2fannounce&tr=udp%3a%2f%2ftracker4.itzmx.com%3a2710%2fannounce&tr=http%3a%2f%2ftracker4.itzmx.com%3a2710%2fannounce&tr=http%3a%2f%2ftracker3.itzmx.com%3a6961%2fannounce&tr=http%3a%2f%2ftracker2.itzmx.com%3a6961%2fannounce&tr=http%3a%2f%2ftracker1.itzmx.com%3a8080%2fannounce&tr=udp%3a%2f%2f62.138.0.158%3a6969%2fannounce&tr=udp%3a%2f%2f188.241.58.209%3a6969%2fannounce&tr=udp%3a%2f%2f93.158.213.92%3a1337%2fannounce&tr=udp%3a%2f%2f185.225.17.100%3a1337%2fannounce&tr=http%3a%2f%2f93.158.213.92%3a1337%2fannounce&tr=http%3a%2f%2f185.225.17.100%3a1337%2fannounce&tr=udp%3a%2f%2f151.80.120.114%3a2710%2fannounce&tr=udp%3a%2f%2f151.80.120.113%3a2710%2fannounce&tr=udp%3a%2f%2f185.19.107.254%3a80%2fannounce&tr=udp%3a%2f%2f208.83.20.20%3a6969%2fannounce&tr=udp%3a%2f%2f5.206.27.172%3a6969%2fannounce&tr=udp%3a%2f%2f176.31.241.153%3a80%2fannounce&tr=udp%3a%2f%2f37.235.174.46%3a2710%2fannounce&tr=udp%3a%2f%2f91.216.110.52%3a451%2fannounce&tr=udp%3a%2f%2f5.2.79.22%3a6969%2fannounce&tr=udp%3a%2f%2f95.211.168.204%3a2710%2fannounce&tr=udp%3a%2f%2f159.100.245.181%3a6969%2fannounce&tr=http%3a%2f%2f51.68.122.172%3a80%2fannounce&tr=udp%3a%2f%2f195.154.52.99%3a80%2fannounce&tr=udp%3a%2f%2f184.105.151.164%3a6969%2fannounce&tr=http%3a%2f%2f184.105.151.164%3a6969%2fannounce&tr=udp%3a%2f%2f51.15.40.114%3a80%2fannounce&tr=udp%3a%2f%2f185.83.215.123%3a6969%2fannounce&tr=udp%3a%2f%2f207.246.121.172%3a2000%2fannounce&tr=udp%3a%2f%2f109.248.43.36%3a6969%2fannounce&tr=udp%3a%2f%2f194.143.148.21%3a2710%2fannounce&tr=http%3a%2f%2f193.148.69.107%3a80%2fannounce&tr=udp%3a%2f%2f52.29.11.73%3a6969%2fannounce&tr=udp%3a%2f%2f52.58.128.163%3a6969%2fannounce&tr=http%3a%2f%2f54.39.98.124%3a80%2fannounce&tr=http%3a%2f%2f86.62.124.78%3a80%2fannounce&tr=udp%3a%2f%2f212.47.227.58%3a6969%2fannounce&tr=udp%3a%2f%2f91.217.91.21%3a3218%2fannounce&tr=udp%3a%2f%2f190.146.242.80%3a7070%2fannounce&tr=udp%3a%2f%2f75.127.14.224%3a2710%2fannounce&tr=udp%3a%2f%2f89.35.39.197%3a1337%2fannounce&tr=udp%3a%2f%2f99.238.163.236%3a6969%2fannounce&tr=udp%3a%2f%2f52.28.76.37%3a6969%2fannounce&tr=udp%3a%2f%2f51.38.178.211%3a6969%2fannounce&tr=udp%3a%2f%2f194.40.242.11%3a80%2fannounce&tr=udp%3a%2f%2f45.56.74.11%3a6969%2fannounce&tr=udp%3a%2f%2f78.30.254.12%3a2710%2fannounce&tr=udp%3a%2f%2f212.1.226.176%3a2710%2fannounce&tr=udp%3a%2f%2f178.165.81.45%3a80%2fannounce&tr=udp%3a%2f%2f217.76.183.53%3a80%2fannounce&tr=udp%3a%2f%2f81.200.240.19%3a6969%2fannounce&tr=udp%3a%2f%2f80.211.26.119%3a9696%2fannounce&tr=udp%3a%2f%2f199.247.2.19%3a6969%2fannounce&tr=udp%3a%2f%2f198.177.123.165%3a80%2fannounce&tr=https%3a%2f%2f104.27.138.209%3a443%2fannounce&tr=https%3a%2f%2f104.27.168.146%3a443%2fannounce&tr=https%3a%2f%2f104.31.84.189%3a443%2fannounce&tr=https%3a%2f%2f104.28.1.175%3a443%2fannounce&tr=http%3a%2f%2f85.114.2.27%3a80%2fannounce&tr=http%3a%2f%2f95.107.48.115%3a80%2fannounce&tr=http%3a%2f%2f91.217.91.21%3a3218%2fannounce&tr=http%3a%2f%2f62.210.202.61%3a80%2fannounce&tr=http%3a%2f%2f104.27.139.209%3a80%2fannounce&tr=http%3a%2f%2f51.158.126.33%3a80%2fannounce&tr=http%3a%2f%2f104.27.169.146%3a80%2fannounce&tr=http%3a%2f%2f104.28.27.45%3a2095%2fannounce&tr=http%3a%2f%2f104.31.254.6%3a80%2fannounce&tr=http%3a%2f%2f78.30.254.12%3a2710%2fannounce&tr=http%3a%2f%2f93.88.129.16%3a80%2fannounce&tr=http%3a%2f%2f104.31.85.249%3a80%2fannounce&tr=http%3a%2f%2f199.247.2.19%3a6969%2fannounce&tr=udp%3a%2f%2f94.23.217.90%3a1337%2fannounce&tr=https%3a%2f%2f104.27.177.131%3a2053%2fannounce&tr=https%3a%2f%2f104.24.125.114%3a443%2fannounce&tr=https%3a%2f%2f104.24.127.56%3a443%2fannounce&tr=http%3a%2f%2f198.251.81.243%3a6699%2fannounce&tr=http%3a%2f%2f198.251.81.243%3a8080%2fannounce&tr=http%3a%2f%2f91.207.136.85%3a80%2fannounce&tr=http%3a%2f%2f51.68.41.25%3a2710%2fannounce&tr=http%3a%2f%2f176.113.71.19%3a6961%2fannounce&tr=http%3a%2f%2f176.113.68.66%3a6961%2fannounce&tr=http%3a%2f%2f104.24.104.127%3a8080%2fannounce&tr=udp%3a%2f%2fopen.demonii.com%3a1337&tr=udp%3a%2f%2ftracker.ccc.de%3a80&tr=udp%3a%2f%2ftracker.coppersurfer.tk%3a6969&tr=udp%3a%2f%2ftracker.istole.it%3a6969&tr=udp%3a%2f%2ftracker.leechers-paradise.org%3a6969&tr=udp%3a%2f%2ftracker.openbittorrent.com%3a80&tr=udp%3a%2f%2ftracker.publicbt.com%3a80&tr=udp%3a%2f%2fzer0day.ch%3a1337
 晕 ~这么长
doge

**Comment by wenead99** [comment]
额。。。。对于内容分集的电影可以用Everaver补救，这个功能日后会考虑添加

**Comment by NJCCJohnWason** [comment]
我从RELEASE里下的是0.8的 没有看到更新，现在已经会用规则了，很好用。
分集的话，现在是用你的AV Data_Capture 之后再手动复制更改为 CD1 CD2 ，在EMBY会智能识别分集。
我可以修改一下您的代码吗？或者我自己用C# 或者JAVA实现一下

**Comment by wenead99** [comment]
可以，欢迎提交代码，感谢
