### ISSUE TITLE
docker的部署教程是不是有问题？

### ISSUE THREAD

**Issue by christdl** [yoshiko2/AV_Data_Capture#307]
按照教程没法部署在docker上，能不能麻烦写的详细点。我打算把这个装到群晖的docker上，但是一直不成功，希望能得到你的指导。谢谢

**Comment by yoshiko2** [comment]
@SayNothingToday

**Comment by SayNothingToday** [comment]
@christdl 具体是什么问题？ docker配置是4个月以前的了，现在用大概率要修修补补一下才行

**Comment by christdl** [comment]
谢谢你的回复。我的环境是群晖的ds918+。按照教程操作，第一步，可以执行；第二部，可以执行，会生成两个镜像；第三步，执行这句命令：
JAVUID=$(id -u) JAVGID=$(id -g) JAV_PATH=<FullPathToLibrary> sudo docker up -d jav，我修改了<FullPathToLibrary>，把它改成了我媒体库的地址，其他没修改，执行以后，出现错误，无法继续。不知道是不是我哪里没有操作对。请多指教。

**Comment by chanh0** [comment]
高手們大家好，
我也想用在vps docker 上設avdc，執行 第一，二步 後 生成了兩個鏡像(image) 好像一個是python，另一個是avdc ，但之後就不知道怎樣生成container 了。 請指教。

**Comment by VergilGao** [comment]
> @christdl 具体是什么问题？ docker配置是4个月以前的了，现在用大概率要修修补补一下才行

>.< 等假期结束我上班摸鱼的时候试着修一下吧，你这个dockerfile写的有点问题……dockerfile里的run语句最好只写一个，此外可以写一个ci让repo主发release的时候自动传一份去docker hub

**Comment by VergilGao** [comment]
> > @christdl 具体是什么问题？ docker配置是4个月以前的了，现在用大概率要修修补补一下才行

等假期结束我上班摸鱼的时候试着修一下吧，你这个dockerfile写的有点问题……dockerfile里的run语句最好只写一个，此外可以写一个ci让repo主发release的时候自动传一份去docker hub

**Comment by wwter12** [comment]
> @SayNothingToday 等假期结束我上班摸鱼的时候试着修一下吧
> 此外可以写一个ci让repo主发release的时候自动传一份去docker hub
> 
> 已经在我的nas上测试通过，有时间我写一个自动化发布到docker hub上的ci
> 下面是源码，具体编译参数我还没写所以对不懂docker的人来说还做不到开箱即用。
> https://github.com/VergilGao/docker-avdc/tree/3.9.1

感谢大佬，大佬有空摸鱼了嘛

**Comment by wwter12** [comment]
> > > @SayNothingToday 等假期结束我上班摸鱼的时候试着修一下吧
> > > 此外可以写一个ci让repo主发release的时候自动传一份去docker hub
> > > 已经在我的nas上测试通过，有时间我写一个自动化发布到docker hub上的ci
> > > 下面是源码，具体编译参数我还没写所以对不懂docker的人来说还做不到开箱即用。
> > > https://github.com/VergilGao/docker-avdc/tree/3.9.1
> > 
> > 
> > 感谢大佬，大佬有空摸鱼了嘛
> 
> 在写测试用例ing
> 摸鱼的时间还要干别的，下周差不多能完事吧。
> ——————
> https://github.com/VergilGao/docker-avdc/runs/1248431771?check_suite_focus=true
> 测试跑通了，明天晚上写个ci提交到docker hub就好了。

感谢大佬，祝约炮成功

**Comment by christdl** [comment]
已经测试成功，感谢各位大佬，也感谢GitHub！
