### ISSUE TITLE
3.8版本更新后无法连接服务器

### ISSUE THREAD

**Issue by windalike** [yoshiko2/AV_Data_Capture#311]
同一天，同一网络环境下，本来用3.4的正常，更新到3.8后显示无法连接
DNS缓存清理过了

[*]================== AV Data Capture ===================
[*]                     Version 3.8
[*]======================================================
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
Press ENTER to exit!

**Comment by windalike** [comment]
然后重新下载老版本后也同样连接不上。。

**Comment by luciferseraph** [comment]
https://github.com/yoshiko2/AV_Data_Capture/wiki/AV-Data-Capture-CLI#%E7%BD%91%E7%BB%9C%E8%AE%BE%E7%BD%AE
如果遇到tineout错误，可以把文件的proxy=后面的地址和端口删除，并开启代理软件全局模式，或者重启电脑，代理软件，网卡
