### ISSUE TITLE
javbus源无码影片，nfo文件没有作者信息，网站是正常的

### ISSUE THREAD

**Issue by 8281529** [yoshiko2/AV_Data_Capture#32]
非常感谢作者，作出了如此神器，让我们彻底解放双手飙车。几点反馈：1、如题，无码影片无法获取女友信息。2、javbus、javdb都有免翻墙的可用ip，建议增加ip设置功能，目前通过hosts大法，暂时解决，但不稳定。3、接上一条，程序在某个目录下测试可用，但将三个程序文件一起复制到其他文件夹就不可用了，不确定是否是host的问题，按说不应该的。4、之前有色友反馈，建议增加自定义文件名，您认为没有必要，文件名太长容易冲突。请问能否给出个文件夹及文件名自定义的入口，从txt文件中读取，用户自行编辑txt文件。比如色花等论坛的标题，诸如"070417-455 必须要求无套肉棒的淫荡美熟女朝桐光"，就很简洁大方，一目了然。
非常感谢。

**Comment by yoshiko2** [comment]
* 网站本身数据不完整
* 墙会不断墙掉IP，建议挂代理
* 认真看文档
* 本身就可以自己修改nfo文件
