### ISSUE TITLE
mac 版执行报错 configparser.NoSectionError: No section: 'update'

### ISSUE THREAD

**Issue by zoomyale** [yoshiko2/AV_Data_Capture#344]
报错信息：

[*]================== AV Data Capture ===================
[*]                    Version 3.9.2
[*]======================================================
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 132, in <module>
  File "config.py", line 75, in update_check
  File "configparser.py", line 828, in getboolean
  File "configparser.py", line 808, in _get_conv
  File "configparser.py", line 803, in _get
  File "configparser.py", line 781, in get
  File "configparser.py", line 1149, in _unify_values
configparser.NoSectionError: No section: 'update'
[86549] Failed to execute script AV_Data_Capture

**Comment by 68cdrBxM8YdoJ** [comment]
Can you share your `config.ini` ?

**Comment by zoomyale** [comment]
I barely modified the original `.ini` file. It's listed below. 

```
[common]
main_mode=1
failed_output_folder=failed
success_output_folder=JAV_output
soft_link=0
failed_move=1
auto_exit=0
transalte_to_sc=1

[proxy]
;proxytype: http or socks5 or socks5h
type=socks5
proxy=127.0.0.1:8889
timeout=10
retry=3

[Name_Rule]
location_rule = '#'+actor+'/'+'['+year+'] '+title+' ['+number+']'
naming_rule = title
max_title_len= 100

[update]
update_check=1

[priority]
website=javbus,javdb,fanza,xcity,mgstage,fc2,avsox,jav321,javlib,dlsite

[escape]
literals=\()/
folders=failed,JAV_output

[debug_mode]
switch=0
```

**Comment by 68cdrBxM8YdoJ** [comment]
I used the same config but unable to reproduce the error.
Still experiencing error?

**Comment by ChenKuiHan** [comment]
在windows下，使用cmd运行这个工具是需要cd到文件所在目录的，否则就会报这个错。mac上可能也有类似的问题。

**Comment by zoomyale** [comment]
> 在 windows 下，使用 cmd 运行这个工具是需要 cd 到文件所在目录的，否则就会报这个错。mac 上可能也有类似的问题。

确实是这个原因
