### ISSUE TITLE
发现一个多集处理的坑，望作者处理

### ISSUE THREAD

**Issue by skypjsfly** [yoshiko2/AV_Data_Capture#347]
如果一个片有多个文件，有一种命名方式是XXX-XXX.cd1.mp4 XXX-XXX.cd2.mp4
如果是这样的话，刮削后会重命名文件为XXX-XXX.mp4，然后cd2会覆盖掉cd1，文件夹中最后只剩一个视频文件
如果是XXX-XXX-cd1.mp4则不会有这个问题，而emby的默认分集规则就是.cdn

**Comment by mcdullmedia** [comment]
https://support.emby.media/support/solutions/articles/44001159102-movie-naming

emby 的命名也是 -cdn 的.

**Comment by yoshiko2** [comment]
批量把.cd改-cd不就好了
