### ISSUE TITLE
dmm获取信息错误，番号格式有问题

### ISSUE THREAD

**Issue by zheolls** [yoshiko2/AV_Data_Capture#35]
很多番号诸如蚊香社abp是81abpxxx而不是abpxxx。
公共网址前缀直接加简写番号会获取不到片子介绍信息。

另外建议封面使用amazon.co.jp的高清图源，基本都是1054x1500的， 不过需要动态爬虫。

**Comment by yoshiko2** [comment]
文档说清楚了，番号问题自行解决，动态爬虫我考虑考虑
