### ISSUE TITLE
windows版本开启翻译功能错误

### ISSUE THREAD

**Issue by JohnGodzilla** [yoshiko2/AV_Data_Capture#351]
编译版本4.0.1
开启翻译功能配置如下:
[common]
transalte_to_sc=1
[transalte]
#是否开启翻译功能
switch=1
#需要翻译的变量
values=title,outline

运行刮削器后
NFO文件中
title保存为
<title>{src}-[NKKD-123]</title>

**Comment by Leung36** [comment]
把注释删了就可以了
