### ISSUE TITLE
最新版一直触发代理错误，然而本地代理并没有异常

### ISSUE THREAD

**Issue by lijian12345** [yoshiko2/AV_Data_Capture#357]
`HTTPSConnectionPool(host='www.javbus.com', port=443): Max retries exceeded with url: /ja/mxgs-783 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x0000022CFC7FFE80>, 'Connection to www.javbus.com timed out. (connect timeout=5)'))`

**Comment by WadeChenn** [comment]
你解决了吗 我也有一样的问题

**Comment by lijian12345** [comment]
> 你解决了吗 我也有一样的问题

我这个问题是因为javbus上搜不到那个片子。。
