### ISSUE TITLE
功能建议 - 多线程

### ISSUE THREAD

**Issue by firstwillzhang** [yoshiko2/AV_Data_Capture#363]
处理大量影片时，是否可以多线程同时进行，以节约时间？
建议增加一个参数，每X部影片建立一个线程，最高线程数Y。
比如X=10 Y=20时
如果有80部影片要处理，那么就建立8个线程同时进行
如果有1000部影片要处理，那么就建立20个线程同时进行

**Comment by yoshiko2** [comment]
多线程容易触发网站反爬，以前实现过
