### ISSUE TITLE
可否多加一個模式, 不移動檔案, 只把所有資料夾內的影片補上 nfo 和圖片?

### ISSUE THREAD

**Issue by mcdull** [yoshiko2/AV_Data_Capture#371]
有些影片 metadata 被 jellyfin 給清空了, 或者當時未能抓取到 nfo/jpg.
但目錄已經弄好, 希望有簡單補回的方法.  謝謝

**Comment by yhf7952** [comment]
同求啊，不想改变原影片目录，只想补充nfo

**Comment by Feng4** [comment]
已添加

**Comment by yhf7952** [comment]
> 已添加

感谢大佬，大佬NB。
现在的问题是，每次重启进程，所有影片都会重新刮削，能不能加个判定，只刮削新增影片？

**Comment by Ercsion** [comment]
> > 已添加
> 
> 感谢大佬，大佬NB。
> 现在的问题是，每次重启进程，所有影片都会重新刮削，能不能加个判定，只刮削新增影片？

可以使用sqlite将所有数据存入数据库，多线程多源削刮，但是工程量可不小

**Comment by mcdull** [comment]
> 已添加

謝謝... 但如何使用呢?
