### ISSUE TITLE
4.0版本以后点开就闪退，没改过任何config

### ISSUE THREAD

**Issue by huoranxuanyuan** [yoshiko2/AV_Data_Capture#376]
![image](https://user-images.githubusercontent.com/67738326/102703963-d62eca00-42b0-11eb-8225-edcb71481e00.png)

**Comment by ddtyjmyjm** [comment]
config.ini  里面[proxy]底下加一行switch=0

**Comment by huoranxuanyuan** [comment]
> config.ini 里面[proxy]底下加一行switch=0

![image](https://user-images.githubusercontent.com/67738326/102848665-4cb5fe00-4450-11eb-8eef-3efdddf947e2.png)
一样的
![image](https://user-images.githubusercontent.com/67738326/102848683-56d7fc80-4450-11eb-88fd-14f04679bc3a.png)

**Comment by ddtyjmyjm** [comment]
现在的错误好像是因为网络问题无法直连github。如果用到proxy的话switch是1。

**Comment by huoranxuanyuan** [comment]
> 现在的错误好像是因为网络问题无法直连github。如果用到proxy的话switch是1。

我填1也一样。
![image](https://user-images.githubusercontent.com/67738326/102857428-5e54d100-4463-11eb-82e4-9101f3997cfa.png)
主要是3.9.2就能用，4开始直接闪退

**Comment by zheyiyuezhuo** [comment]
我也是这样
