### ISSUE TITLE
点击演员头像后无法显示该演员作品列表

### ISSUE THREAD

**Issue by playmsg** [yoshiko2/AV_Data_Capture#379]
环境Jellyfin10.6.4，以docker方式安装在centos8下，avdc4.02。
用普通的电影呢没什么问题，如果是AV这种电影呢，点击演员头像后显示载入圆环……就没动静了。在PC端移动端均是如此。不知道是产生的NFO有问题还是什么其他的原因？（比如目录里含有日文等等，虽然这个不应该）。另外附议，支持NFO里加入演员头像，虽然这个我估计数据源很难找。

**Comment by nukewarrior** [comment]
1、载入转圈和nfo没关系，点击演员头像后，jellyfin会去在线搜寻信息，忘了具体那个地址，反正是被墙的，基本路由器挂了梯子也会转圈，很慢
2、既然你用jellyfin，演员头像建议用使用[Gfriends Inputer 一键导入工具](https://github.com/xinxin8816/gfriends/releases)

**Comment by playmsg** [comment]
受教了，我就没想到那个转圈圈是去读外网了……以为在读什么莫名其妙的NFO数据库之类的。这样的话我研究研究屏蔽host之类的说不定就好了。gfriends inputer，一看名字就是神器啊，没想到现在这个产业这么发达。

**Comment by nxy1999** [comment]
> 受教了，我就没想到那个转圈圈是去读外网了……以为在读什么莫名其妙的NFO数据库之类的。这样的话我研究研究屏蔽host之类的说不定就好了。gfriends inputer，一看名字就是神器啊，没想到现在这个产业这么发达。

**Comment by nxy1999** [comment]
> 环境Jellyfin10.6.4，以docker方式安装在centos8下，avdc4.02。 用普通的电影呢没什么问题，如果是AV这种电影呢，点击演员头像后显示载入圆环……就没动静了。在PC端移动端均是如此。不知道是产生的NFO有问题还是什么其他的原因？（比如目录里含有日文等等，虽然这个不应该）。另外附议，支持NFO里加入演员头像，虽然这个我估计数据源很难找。



> 受教了，我就没想到那个转圈圈是去读外网了……以为在读什么莫名其妙的NFO数据库之类的。这样的话我研究研究屏蔽host之类的说不定就好了。gfriends inputer，一看名字就是神器啊，没想到现在这个产业这么发达。

解决了吗，兄弟，我也遇到这个问题了，一直转圈。不过我是Windows。

**Comment by nxy1999** [comment]
> 受教了，我就没想到那个转圈圈是去读外网了……以为在读什么莫名其妙的NFO数据库之类的。这样的话我研究研究屏蔽host之类的说不定就好了。gfriends inputer，一看名字就是神器啊，没想到现在这个产业这么发达。

解决了吗，兄弟，我也遇到这个问题了，一直转圈。不过我是Windows。
