### ISSUE TITLE
4.2.2版本输出文件夹有变，感觉麻烦了点，不知道是不是bug

### ISSUE THREAD

**Issue by EnnawYang** [yoshiko2/AV_Data_Capture#383]
环境：Windows 10
之前版本输出的文件夹是 ` .\JAV_output `
而4.2.2版本输出的文件夹是 ` .\视频所在文件夹\JAV_output `

**Comment by ddtyjmyjm** [comment]
可以提供一下config吗。在默认配置下，我测试的情况结果仍然在.\JAV_output\。

**Comment by EnnawYang** [comment]
```
[common]
main_mode=1
failed_output_folder=failed
success_output_folder=output
soft_link=0
failed_move=1
auto_exit=0
transalte_to_sc=0

[proxy]
;proxytype: http or socks5 or socks5h switch: 0 1
switch=1
type=http
proxy=127.0.0.1:1085
timeout=3
retry=3

[Name_Rule]
location_rule=actor+'-'+number
naming_rule=number
max_title_len= 50

[update]
update_check=1

[priority]
website=javbus,javdb,fanza,xcity,mgstage,fc2,avsox,jav321,javlib,dlsite

[escape]
literals=\()/
folders=failed,output

[debug_mode]
switch=1

[transalte]
switch=0
values=title,outline
```

**Comment by ddtyjmyjm** [comment]
测试了一下，成功搜刮后是写入`.\output\<location_rule>\`中的呀

**Comment by EnnawYang** [comment]
这就很奇怪了
```
[*]================== AV Data Capture ===================
[*]                    Version 4.2.2
[*]======================================================
[+]Find 1 movies
[+]------------------- DEBUG MODE ON --------------------
[!] - 100.% [1/1] -
[!]Making Data for [D:\Downloads\test\ABW-040\ABW-040.mp4], the number is [ABW-040]
[+]select javbus
[+] ---Debug info---
  ......
[+] ---Debug info---
[+]Image Downloaded! D:\Downloads\test\ABW-040/output/鈴村あいり-ABW-040/ABW-040-fanart.jpg
[+]Image Cutted!     D:\Downloads\test\ABW-040/output/鈴村あいり-ABW-040/ABW-040-poster.jpg
[+]Wrote!            D:\Downloads\test\ABW-040/output/鈴村あいり-ABW-040/ABW-040.nfo
[*]======================================================
[+]All finished!!!
Press enter key exit, you can check the error message before you exit...
```

**Comment by EnnawYang** [comment]
4.2.1正常
```
[*]================== AV Data Capture ===================
[*]                    Version 4.2.1
[*]======================================================
[*]                 * New update 4.2.2 *
[*]                     ↓ Download ↓
[*] https://github.com/yoshiko2/AV_Data_Capture/releases
[*]======================================================
[+]Find 1 movies
[+]------------------- DEBUG MODE ON --------------------
[!] - 100.% [1/1] -
[!]Making Data for [.\ABW-040\ABW-040.mp4], the number is [ABW-040]
[+]select javbus
[+] ---Debug info---
  ......
[+] ---Debug info---
[+]Image Downloaded! output/鈴村あいり-ABW-040/ABW-040-fanart.jpg
[+]Image Cutted!     output/鈴村あいり-ABW-040/ABW-040-poster.jpg
[+]Wrote!            output/鈴村あいり-ABW-040/ABW-040.nfo
[*]======================================================
[+]All finished!!!
Press enter key exit, you can check the error message before you exit...
```

**Comment by ddtyjmyjm** [comment]
不好意思，确认确实是我这个版本修改时出现的错误，会尽快修改

**Comment by EnnawYang** [comment]
> 不好意思，确认确实是我这个版本修改时出现的错误，会尽快修改

好的，谢谢，辛苦了

**Comment by ddtyjmyjm** [comment]
修改 `core.py` 中的[代码](https://github.com/yoshiko2/AV_Data_Capture/blob/master/core.py)
https://github.com/yoshiko2/AV_Data_Capture/blob/2fe23052263158a30a30e657850305ea88e772b0/core.py#L525

改成
```python3
    rootpath = os.getcwd()
```
应该可以解决问题

**Comment by hacker94** [comment]
看起来这个bug还会导致多集视频移动失败，猜测是因为路径不对导致create_folder时候exists判断错误

错误日志：
[*]======================================================
[!] - 54.7% [64/117] -
[!]Making Data for [\\rooT_NAS\home\Downloads\SNIS-850-cd1.mp4], the number is [SNIS-850]
[+]Image Downloaded! rooT_NAS\home\Downloads/JAV_output/三上悠亜_SNIS-850/SNIS-850-cd1-fanart.jpg
[+]Image Cutted!     rooT_NAS\home\Downloads/JAV_output/三上悠亜_SNIS-850/SNIS-850-cd1-poster.jpg
[+]Wrote!            rooT_NAS\home\Downloads/JAV_output/三上悠亜_SNIS-850/SNIS-850-cd1.nfo
[*]======================================================
[!] - 55.5% [65/117] -
[!]Making Data for [\\rooT_NAS\home\Downloads\SNIS-850-cd2.mp4], the number is [SNIS-850]
[-] [\\rooT_NAS\home\Downloads\SNIS-850-cd2.mp4] ERROR:
[-] [WinError 183] 当文件已存在时，无法创建该文件。: 'rooT_NAS\\home\\Downloads/JAV_output/三上悠亜_SNIS-850'
[-]Move [\\rooT_NAS\home\Downloads\SNIS-850-cd2.mp4] to failed folder
[!] - 56.4% [66/117] -
[!]Making Data for [\\rooT_NAS\home\Downloads\SNIS-872.mp4], the number is [SNIS-872]
[+]Image Downloaded! rooT_NAS\home\Downloads/JAV_output/三上悠亜_SNIS-872/SNIS-872-fanart.jpg
[+]Image Cutted!     rooT_NAS\home\Downloads/JAV_output/三上悠亜_SNIS-872/SNIS-872-poster.jpg
[+]Wrote!            rooT_NAS\home\Downloads/JAV_output/三上悠亜_SNIS-872/SNIS-872.nfo
[*]======================================================

**Comment by Csrayz** [comment]
我也遇到了相似的问题
* 多集视频移动失败
* samba文件更加异常，会直接在程序所在地按照上级路径依次创建文件夹，如：.\samba\r18\man\XXX

**Comment by EnnawYang** [comment]
fixed in https://github.com/yoshiko2/AV_Data_Capture/pull/385
