### ISSUE TITLE
一点小疑问

### ISSUE THREAD

**Issue by s0urcelab** [yoshiko2/AV_Data_Capture#4]
之前自己也打算写个生成nfo的脚本，但是似乎不好弄到dmm的api key，不知道你这里是影片信息是怎么查到的呢

**Comment by wenead99** [comment]
直接伪装ua请求网页然后用解析库提取信息就好了

**Comment by s0urcelab** [comment]
还是请求的html再抓取内容？来自同ip的大量请求会不会被限制啊？

**Comment by wenead99** [comment]
@s0urcelab  程序抓取后三秒休眠
