### ISSUE TITLE
可否按设置的规则，直接更改文件名，而不是nfo文件啊

### ISSUE THREAD

**Issue by liubin1027x** [yoshiko2/AV_Data_Capture#410]
因为有的人并不想用emby啥的来管理影片，只是想整理好影片后，直接播放

**Comment by 1004452714** [comment]
https://github.com/yoshiko2/AV_Data_Capture/wiki#%E8%AE%BE%E7%BD%AE%E8%87%AA%E5%AE%9A%E4%B9%89%E7%9B%AE%E5%BD%95%E5%92%8C%E5%BD%B1%E7%89%87%E9%87%8D%E5%91%BD%E5%90%8D%E8%A7%84%E5%88%99%E6%A0%87%E9%A2%98%E6%9C%80%E9%95%BF%E5%AD%97%E7%AC%A6%E6%95%B0%E8%AE%BE%E7%BD%AE

WIKI上写的还不够清楚嘛

> 因为有的人并不想用emby啥的来管理影片，只是想整理好影片后，直接播放
