### ISSUE TITLE
发现了javlib.py的一个Bug！

### ISSUE THREAD

**Issue by getlv** [yoshiko2/AV_Data_Capture#411]
result = get_html(
        "http://www.javlibrary.com/cn/vl_searchbyid.php?keyword={}".format(number),
        cookies=cookies,
        ua=user_agent,
        return_type="object"
    )
    soup = BeautifulSoup(result.text, "html.parser")
    lx = html.fromstring(str(soup))

    if "/?v=jav" in result.url:
        dic = {
            "title": get_title(lx, soup),
            "studio": get_table_el_single_anchor(soup, "video_maker"),
            "year": get_table_el_td(soup, "video_date")[:4],
            "outline": "",
            "director": get_table_el_single_anchor(soup, "video_director"),
            "cover": get_cover(lx),
            "imagecut": 1,
            "actor_photo": "",
            "website": result.url,
            "source": "javlib.py",
            "actor": get_table_el_multi_anchor(soup, "video_cast"),
            "label": get_table_el_td(soup, "video_label"),
            "tag": get_table_el_multi_anchor(soup, "video_genres"),
            "number": get_table_el_td(soup, "video_id"),
            "release": get_table_el_td(soup, "video_date"),
            "runtime": get_from_xpath(lx, '//*[@id="video_length"]/table/tr/td[2]/span/text()'),
            "series":'',
        }
    else:
        dic = {}
javlib.py这段代码应该再加一个条件判断，当页面获取不到以上这些tag时，要判断是否是一个番号搜索出了多个结果，例如ARM-072这个番号在javlib上会搜索出ARM-072，ARM-720，ARM-721等多个结果，此时得到的页面是一个搜索结果页面，自然不会包含titile，studio这些tag，此时应该加一个判断，自动获取第一个结果的链接，然后进入这个链接页面再次获取tag。此类的复现例子还有很多，凡是XXX-0XX的番号都是这种情况，不在少数。

**Comment by pikachullk** [comment]
不是可以 -n指定番号吗?
