### ISSUE TITLE
请问一下这个搜刮出来的剧照能在plex里面用吗？

### ISSUE THREAD

**Issue by kangbeicai** [yoshiko2/AV_Data_Capture#418]
plex好像不支持本地nfo文件还有剧照的识别？  NFO文件时找到个插件可以用了， 剧照有没有相关的插件呢？

**Comment by gihongyuan** [comment]
> plex好像不支持本地nfo文件还有剧照的识别？ NFO文件时找到个插件可以用了， 剧照有没有相关的插件呢？

XBMCnfoMoviesImporter 这个插件勉强可以用

**Comment by kangbeicai** [comment]
> > plex好像不支持本地nfo文件还有剧照的识别？ NFO文件时找到个插件可以用了， 剧照有没有相关的插件呢？
> 
> XBMCnfoMoviesImporter 这个插件勉强可以用

XBM就是用来导入本地NFO的吧。。剧照感觉用不上
