### ISSUE TITLE
不知emby是否支持预告片和剧照功能？

### ISSUE THREAD

**Issue by nrm1587** [yoshiko2/AV_Data_Capture#421]
看更新日志内添加了预告及剧照功能，不知道emby是否支持?如果是的话该如何设置？求大佬解惑。

**Comment by ltlt4** [comment]
请问emby里封面上的中文字幕标签是怎么打上去的。

**Comment by pikachullk** [comment]
1.本质上这是emby的问题～您应该在emby的论坛求助…
2.预告片命名为“片名-trailer.mp4”就能识别到了…
3.剧照只能开启背景等轮显
建议此贴自己close

**Comment by nrm1587** [comment]
我的锅
