### ISSUE TITLE
使用ssr，本地https认证报错

### ISSUE THREAD

**Issue by virtue050** [yoshiko2/AV_Data_Capture#425]
使用版本：4.4.1
报错信息：urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings

ssr正常上网。

**Comment by lxver** [comment]
urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings


同样的问题  还没找到解决方法

**Comment by 1004452714** [comment]
好像只是个警告，不影响正常使用？
在源代码里的 AV_Data_capture.py里加上
import urllib3
urllib3.disable_warnings()
这两行就不显示警告了

> urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> 
> 同样的问题 还没找到解决方法



> 使用版本：4.4.1
> 报错信息：urllib3\connectionpool.py:1013: InsecureRequestWarning: Unverified HTTPS request is being made to host '127.0.0.1'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
> 
> ssr正常上网。

**Comment by 8281529** [comment]
同样情况，但我估计不只是单单警告不影响使用，理由1、不开代理依然可以下载到封面图片和nfo文件；2、开代理且修改设置后依然无法下载预告片，貌似还是ss不兼容的问题

**Comment by biaji** [comment]
如 @1004452714 所说，是个警告。 原始链接有解决方案
