### ISSUE TITLE
不同源刮削出來的姓名不一樣. 而且一個女優可以多於一個姓名. 可以加個對照表解決嗎?

### ISSUE THREAD

**Issue by mcdullmedia** [yoshiko2/AV_Data_Capture#430]
就像現在繁中轉簡中的對照表, 可以做一個女優對照嗎? 最起碼可以把 AIRAV 和 JAVBUS 刮出來弄的一致. 謝謝!

**Comment by yoshiko2** [comment]
调整配置文件网站顺序 javbus优先

**Comment by ifunboy** [comment]
可以修改airav.py 使用javbus获取actor与tag。
将最大化保持AIRAV 和 JAVBUS搜刮后的内容一致（除了中文标题和简介其他全部以javbus为准）。

**Comment by mcdull** [comment]
> 可以修改airav.py 使用javbus获取actor与tag。
> 将最大化保持AIRAV 和 JAVBUS搜刮后的内容一致（除了中文标题和简介其他全部以javbus为准）。

這建議很好, 畢竟女優資源還是以JAVBUS的命名為主. AIRAV 的中文描述亦很有用. 部分tag 甚至可以結合二者

**Comment by mcdullmedia** [comment]
Now name will be extracted from JAVBUS
