### ISSUE TITLE
发issues前，请确保你熟读wiki，调配置和使用renamer等批量重命名文件工具

### ISSUE THREAD

**Issue by yoshiko2** [yoshiko2/AV_Data_Capture#431]

**Comment by lededev** [comment]
批量重命名使用Everything的重命名功能更方便快捷，在Everything中搜索菜单限定搜索目标为视频，然后输入需要批量替换的文件关键字，得到一批文件后，按文件名排序，将具有相同名字规则的一批文件用SHIFT选中，按F2重命名。
重命名支持通配符定义模式和正规表达式定义模式，Everything会根据这批文件的特征自动生成一个模式在第一行，如果对模式满意，直接在第二行替换结果那里删除不想要的文件名部分，下方预览列表会显示更名后的结果。如果模式不适合更名需要，则自己修改一下第一行的模式定义，并复制到第二行，然后修改第二行提取需要的文件名格式。
Everything是免费软件，全部功能都无需付费，如果使用后发现Everything对你的工作帮助很大，可以捐赠以支持作者继续开发。
