### ISSUE TITLE
做了个改动比较大的fork，不知道是否该往回merge了

### ISSUE THREAD

**Issue by yyymess** [yoshiko2/AV_Data_Capture#433]
恩。。故事是这样的
前几天把avdc fork了下来想做几个本地小改动适应下自己的使用习惯
结果一不小心码撸多了，做了一个大重构，现在还在施工中，本体差不多搞完了，但是应该还剩不少小问题
现在不知道我是该继续圈地自萌，还是试图把部分/全部改动merge回主repo里
所以看看大佬这边的意见咯
https://github.com/yoshiko2/AV_Data_Capture/compare/master...yyymess:master?diff=split

主要区别
- NFO从print改成了标准化的xml输出工具 （不过因为用到了新的xml.etree.ElementTree.indent, 需要Python 3.9）
- 信息封装从json抽象出了一个Movie object，把各种文件命名规则全部拖进了这里面
- 增加了一个女优名查重映射，映射关系从隔壁女优头像的gfriends库里拖出来的
- 标签简化被重写了下，现在是读取一个外置csv，方便后续添加个性化映射
- 直接运行程序时从用程序所在目录改为了弹窗询问整理的文件夹
- 添加了评分刮削和nfo写入，现在在fc2，javlib，和mgstage里实现了
- 不少代码被我从core单独拉进了自己的文件

各种已知问题
- 翻译功能完全残废，还没管它
- pyinstaller还没重新配置
- 完全不知道还坏了啥，我自己使用的时候大概只会走到一半左右的codepath

**Comment by mcdull** [comment]
開一個新 branch 吧
