### ISSUE TITLE
一个番号多个视频无法准确识别

### ISSUE THREAD

**Issue by BCccc64** [yoshiko2/AV_Data_Capture#435]
对于一个番号多个视频的情况，会把该番号的第一个文件重命名并移动，第二个留下不动
已翻过之前发布的issue，并未对该问题进行有效解决，希望开发大大看到

**Comment by playmsg** [comment]
所以兄弟我针对这种情况专门写了个软件用来无损快速合并相同格式的视频……[大枣无损合并](https://github.com/playmsg/chinese-date/releases)
