### ISSUE TITLE
总是提示Proxy error! Please check your Proxy

### ISSUE THREAD

**Issue by skypjsfly** [yoshiko2/AV_Data_Capture#449]
我已经关掉了proxy，电脑开了全局模式，还是不行
![image](https://user-images.githubusercontent.com/32484309/113085820-22c06480-9213-11eb-8ba4-c59cf2fb86a9.png)

[-]Proxy error! Please check your Proxy
[-]Proxy error! Please check your Proxy
[-]Proxy error! Please check your Proxy
can only parse strings
[-]Proxy error! Please check your Proxy
[-]Proxy error! Please check your Proxy
[-]Proxy error! Please check your Proxy
![image](https://user-images.githubusercontent.com/32484309/113085833-281daf00-9213-11eb-8037-bfa61e2f267c.png)

**Comment by dXrayb** [comment]
等更新吧，或者尝试一下使用代理，然后手动配置代理设置，不过我用这个方法尝试，然并卵。

**Comment by skypjsfly** [comment]
> 等更新吧，或者尝试一下使用代理，然后手动配置代理设置，不过我用这个方法尝试，然并卵。

只能这样了，我之前上一个版本都没问题，昨天用突然都有这个问题了
