### ISSUE TITLE
无法搜索AOZ

### ISSUE THREAD

**Issue by liehun10086** [yoshiko2/AV_Data_Capture#45]
似乎是因为AOZ的片后缀都会带个Z，比如AOZ-257Z，识别时变成AOZ-257了
在javbus上是可以搜到的
![image](https://user-images.githubusercontent.com/7877770/66708665-94d68c80-ed86-11e9-8f88-66cbd962fadf.png)

**Comment by liehun10086** [comment]
文件名为AOZ-257Z时，捕捉到的番号是AOZ-257，会搜索不到封面信息
把文件名改成AOZ257Z时会捕捉到AOZ-257Z，成功搜索到封面信息
![image](https://user-images.githubusercontent.com/7877770/66709209-07009e80-ed92-11e9-9f80-e9e7d808281b.png)

**Comment by yoshiko2** [comment]
后期版本会考虑加入番号模糊搜索功能
