### ISSUE TITLE
关于kodi命名

### ISSUE THREAD

**Issue by lhiqwj173** [yoshiko2/AV_Data_Capture#47]
感谢大佬的贡献，反馈如下
kodi的数据大概是这样的
![image](https://user-images.githubusercontent.com/51277202/67055945-b49df400-f17c-11e9-88f0-13bafe360a8a.png)

我实验过，如果将.jpg(fanart)和.png(poster)重命名为-fanart.jpg ,-poster.jpg，并相应修改nfo，会显示的很完美，目前的命名fanart不显示。

**Comment by yoshiko2** [comment]
后期会考虑支持
