### ISSUE TITLE
关于Emby添加演员头像信息的可行性

### ISSUE THREAD

**Issue by ifunboy** [yoshiko2/AV_Data_Capture#48]
在目前使用中，Emby里无法显示演员头像。一个一个手工添加十分麻烦。
研究了下Emby添加头像的API
[https://emby.media/community/index.php?/topic/71665-local-actor-thumbnail-in-nfo/](url)
以及Emby 控制面板下的API说明链接。
通过以下方式可以使用API上传演员头像。

### 首先获得演员ID
`curl -X GET "${embyServerURL}/emby/Persons/${personName}?api_key=${apiKey}" -H "accept: application/json"`
其中
`${embyServerURL}代表emby地址`
`${personName}代表演员名字（需转换成URL格式）`
`${apiKey}代表API密钥（在控制面板-专家-高级-安全措施 设置）`

**返回的信息如下**
`{"Name":"ifun","ServerId":"1d4e0879025344b1a2a890af5f1eb463","Id":"1042","Etag":"f3032aa29142a913e5e06d0b57d5fd4d","DateCreated":"2019-10-18T05:04:58.0000000+00:00","CanDelete":false,"CanDownload":false,"PresentationUniqueKey":"a4a96981c2a2411db0c89d141592fafd","SortName":"ifun","ExternalUrls":[],"Taglines":[],"Genres":[],"RemoteTrailers":[],"ProviderIds":{},"Type":"Person","Studios":[],"GenreItems":[],"TagItems":[],"DisplayPreferencesId":"b607178b0ac2f604a458d3d2363fdc83","Tags":[],"ImageTags":{},"BackdropImageTags":[],"LockedFields":[],"LockData":false}
`
### 然后上传图像
1.上传网络图像
`curl -X POST "${embyServerURL}/emby/Items/${actorID}/RemoteImages/Download?Type=${type}&ImageUrl=${imageUrl}&api_key=${apiKey}" -H "accept: */*"`

2.上传本地jpeg
`base64 ${imagePath} | xargs curl -X POST "${embyServerURL}/emby/Items/${actorID}/Images/Type=${type}?api_key=${apiKey}" -H "Content-Type: image/jpeg" --data-binary`

3.上传本地png
`base64 ${imagePath} | xargs curl -X POST "${embyServerURL}/emby/Items/${actorID}/Images/Type=${type}?api_key=${apiKey}" -H "Content-Type: image/png" --data-binary`

其中
`${actorID}为返回信息中的"Id":"1042"项（${actorID}=1042）`
`${type}可以为 Primary, Art, Backdrop, Banner, Logo, Thumb, Disc, Box, Screenshot, Menu, Chapter, BoxRear, Thumbnail之中其一`
`${imageUrl}为网络图片地址（不区分jpg|png）`

**Comment by ifunboy** [comment]
可以考虑增加mode3
遍历提取Nfo文件中的网址信息，然后爬取相应头像信息等。
然后通过脚本去重后批量上传信息到emby

**Comment by yoshiko2** [comment]
感谢反馈，我会考虑适配此功能

**Comment by yoshiko2** [comment]
这样太复杂了，有没有办法直接在NFO调用本地图片，这个我研究很久了

**Comment by junerain123** [comment]
> 在目前使用中，Emby里无法显示演员头像。一个一个手工添加十分麻烦。
> 研究了下Emby添加头像的API
> [https://emby.media/community/index.php?/topic/71665-local-actor-thumbnail-in-nfo/](url)
> 以及Emby 控制面板下的API说明链接。
> 通过以下方式可以使用API上传演员头像。
> 
> ### 首先获得演员ID
> `curl -X GET "${embyServerURL}/emby/Persons/${personName}?api_key=${apiKey}" -H "accept: application/json"`
> 其中
> `${embyServerURL}代表emby地址`
> `${personName}代表演员名字（需转换成URL格式）`
> `${apiKey}代表API密钥（在控制面板-专家-高级-安全措施 设置）`
> 
> **返回的信息如下**
> `{"Name":"ifun","ServerId":"1d4e0879025344b1a2a890af5f1eb463","Id":"1042","Etag":"f3032aa29142a913e5e06d0b57d5fd4d","DateCreated":"2019-10-18T05:04:58.0000000+00:00","CanDelete":false,"CanDownload":false,"PresentationUniqueKey":"a4a96981c2a2411db0c89d141592fafd","SortName":"ifun","ExternalUrls":[],"Taglines":[],"Genres":[],"RemoteTrailers":[],"ProviderIds":{},"Type":"Person","Studios":[],"GenreItems":[],"TagItems":[],"DisplayPreferencesId":"b607178b0ac2f604a458d3d2363fdc83","Tags":[],"ImageTags":{},"BackdropImageTags":[],"LockedFields":[],"LockData":false} `
> 
> ### 然后上传图像
> 1.上传网络图像
> `curl -X POST "${embyServerURL}/emby/Items/${actorID}/RemoteImages/Download?Type=${type}&ImageUrl=${imageUrl}&api_key=${apiKey}" -H "accept: */*"`
> 
> 2.上传本地jpeg
> `base64 ${imagePath} | xargs curl -X POST "${embyServerURL}/emby/Items/${actorID}/Images/Type=${type}?api_key=${apiKey}" -H "Content-Type: image/jpeg" --data-binary`
> 
> 3.上传本地png
> `base64 ${imagePath} | xargs curl -X POST "${embyServerURL}/emby/Items/${actorID}/Images/Type=${type}?api_key=${apiKey}" -H "Content-Type: image/png" --data-binary`
> 
> 其中
> `${actorID}为返回信息中的"Id":"1042"项（${actorID}=1042）`
> `${type}可以为 Primary, Art, Backdrop, Banner, Logo, Thumb, Disc, Box, Screenshot, Menu, Chapter, BoxRear, Thumbnail之中其一`
> `${imageUrl}为网络图片地址（不区分jpg|png）`



> 可以考虑增加mode3
> 遍历提取Nfo文件中的网址信息，然后爬取相应头像信息等。
> 然后通过脚本去重后批量上传信息到emby

你好！我不太懂linux命令，添加本地图片的这几句话“base64 ${imagePath} | xargs curl -X POST "${embyServerURL}/emby/Items/${actorID}/Images/Type=${type}?api_key=${apiKey}" -H "Content-Type: image/jpeg" --data-binary”，我想写成python脚本，${imagePath}应该以什么形式post给emby？

**Comment by junerain123** [comment]
今天花了很大功夫还是一事无成，又在 Ubuntu下试了试“base64 2.jpg | xargs curl -X POST "http://localhost:8096/emby/Items/1648/Images/Primary?api_key=61877972f58d436ea1db1677bb720d35" -H "Content-Type: image/jpeg" --data-binary”，
还是失败“The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.”
