### ISSUE TITLE
文件夹名有中括号不能识别

### ISSUE THREAD

**Issue by chihoutam** [yoshiko2/AV_Data_Capture#49]
影片单独文件夹存放并且影片文件夹带"[" "]" 时无法被识别 ,比如:
[Thz.la]ppt-041\ppt-041.mkv
[88k.me]ssni-561\ssni.561.mp4

**Comment by yoshiko2** [comment]
建议把所有电影提取到和程序当前目录下

**Comment by chihoutam** [comment]
因为下载好一般都有文件夹,所以如果能直接识别就更方便了哈~
