### ISSUE TITLE
Mywife系列

### ISSUE THREAD

**Issue by 384432485** [yoshiko2/AV_Data_Capture#5]
考虑增加Mywife系列的支持吗？

**Comment by wenead99** [comment]
@384432485  可以给个番号格式和资料比较全的网站?

**Comment by 384432485** [comment]
额，这个还真的去好好找找   毕竟我不是老司机

**Comment by Foxgeek36** [comment]
school girl is better

**Comment by Hoshigamifd** [comment]
> @384432485 可以给个番号格式和资料比较全的网站?

www.jav321.com这个网站番号很全

**Comment by Hoshigamifd** [comment]
@yoshiko2 
www.jav321.com   这个网站番号很全
