### ISSUE TITLE
Ver.4.6.6:FileNotFoundError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by nukewarrior** [yoshiko2/AV_Data_Capture#516]
![image](https://user-images.githubusercontent.com/10683831/121629731-6276b880-caae-11eb-80e6-ecfb509c2a2a.png)
![image](https://user-images.githubusercontent.com/10683831/121629749-702c3e00-caae-11eb-8f14-8029c882e0ae.png)

如图，不知道是什么原因造成的，但是会造成FileNotFoundError: [Errno 2] No such file or directory错误
路由器全局翻墙，网络方面应该是没有问题的
看打印出来的路径，似乎多了一个/

**Comment by lededev** [comment]
//会被系统转为/，错误不是这个/造成的。而是Debug info里的Cover路径/pics/cover/85ha_b.jpg，这里缺少http://网址。
应该是airav.py的封面图片路径解析的问题。
