### ISSUE TITLE
建議中文字幕的標籤可以更換成japonX那種風格

### ISSUE THREAD

**Issue by cascadahk** [yoshiko2/AV_Data_Capture#518]
現在版本的中文字幕標示有點小，不夠直接
可以的話改成這種很不錯
![Capture](https://user-images.githubusercontent.com/63991550/121810736-8f84c000-cc94-11eb-89f6-6151b3a01829.JPG)

**Comment by lededev** [comment]
我提交了一个支持本地图片的[PR](https://github.com/yoshiko2/AV_Data_Capture/pull/519)，允许使用用户本地图片，你喜欢那种风格的标签，可以替换掉Img/SUB.png图片，可能还要改一下配置文件让其显示在左上角。
注意你想要的那种斜45度角标png图，要做成红色背景条之外的矩形区域透明。大小也不是问题，把png角标图片做大一些就行了，我看了一下程序能自动适应。

**Comment by cascadahk** [comment]
謝謝提供功能，可惜我研究了一下還不會修改，希望日後有人使用後分享一下教學吧

**Comment by 1458271** [comment]
修改的话需要下载源码自行编译，因为图片已经打包在EXE中了，源码运行的教程指南中应该有
