### ISSUE TITLE
按演员进行分类整理的时候，针对多演员作品可否设置为以第一位演员进行整理？

### ISSUE THREAD

**Issue by jcx70100** [yoshiko2/AV_Data_Capture#520]
开发者您好，首先**感谢如此伟大的工具，给强迫症患者带来极大福音**！

在使用过程中，遇到如下 问题：

比如一个作品有很多个演员，在进行整理的时候，程序会将作品整理到以所有作者名称为命名的文件夹下，导致文件夹的名称特别长，也导致演员文件夹比较混乱。

可否有办法将整理路径设置为：`/演员名称（若为多人，则以第一个演员名称为主进行整理）/作品fan号`

如作品XXX-000由A,B,C,D演员出演，目前的整理结果是`/A,B,C,D/XXX-000`,期望的整理结果为`/A/XXX-000`,这样可以大大简化整理文件的目录，而具体的演员信息在nfo文件里面已经存在，可以在emby等 平台进行查看和管理。

感谢

**Comment by lededev** [comment]
将演员名称暴露给文件系统，对Everything这样的搜索工具非常友好，无需事先搜集全部元数据就可以实现查询。

**Comment by jcx70100** [comment]
主要是由于多演员的作品文件夹名称一长串太不美观，而且通常这样的文件夹里只有少数的几个作品，为 单独的多演员作品单独分配一个长串名称的文件夹觉得 很不舒服，因此才想着能否按照第一个演员的名称进行分类整理。

**Comment by lededev** [comment]
那你就按你的想法写代码吧。
