### ISSUE TITLE
4.6.7 - SIRO番号系列的片子，演员名字刮削有问题

### ISSUE THREAD

**Issue by nukewarrior** [yoshiko2/AV_Data_Capture#521]
![image](https://user-images.githubusercontent.com/10683831/122167775-ff21c780-cead-11eb-8531-487627987e19.png)
![image](https://user-images.githubusercontent.com/10683831/122167786-021cb800-ceae-11eb-9b88-ab80e0369a48.png)
![IMG_5204](https://user-images.githubusercontent.com/10683831/122167888-29738500-ceae-11eb-955d-ed49bd576fcd.PNG)

如图所示

**Comment by lededev** [comment]
https://www.mgstage.com/product/product_detail/SIRO-4373/ 里演员就是上述内容，你用javdb看到的和mgstage的不一样。
如果你想用javdb来削刮SIRO系列，只能去掉mgstage，修改配置文件config.ini就行了。
```
[priority]
website=javbus,javdb,airav,fanza,xcity,mgstage,fc2,avsox,dlsite,carib

```
改为
```
[priority]
website=javbus,javdb,airav,fanza,xcity,fc2,avsox,dlsite,carib

```

**Comment by nukewarrior** [comment]
> https://www.mgstage.com/product/product_detail/SIRO-4373/ 里演员就是上述内容，你用javdb看到的和mgstage的不一样。
> 如果你想用javdb来削刮SIRO系列，只能去掉mgstage，修改配置文件config.ini就行了。
> 
> ```
> [priority]
> website=javbus,javdb,airav,fanza,xcity,mgstage,fc2,avsox,dlsite,carib
> ```
> 
> 改为
> 
> ```
> [priority]
> website=javbus,javdb,airav,fanza,xcity,fc2,avsox,dlsite,carib
> ```

谢谢，解决我的问题了。
不过我config.ini里面原本就把javdb放到第一位了，不知道为啥还是刮削到mgstage那里去了

**Comment by lededev** [comment]
> 谢谢，解决我的问题了。
> 不过我config.ini里面原本就把javdb放到第一位了，不知道为啥还是刮削到mgstage那里去了

因为mgstage是SIRO专用的，信息比较详细，发现是SIRO就会优先使用mgstage，总之你不喜欢就从config.ini去掉好了。

**Comment by nukewarrior** [comment]
> > 谢谢，解决我的问题了。
> > 不过我config.ini里面原本就把javdb放到第一位了，不知道为啥还是刮削到mgstage那里去了
> 
> 因为mgstage是SIRO专用的，信息比较详细，发现是SIRO就会优先使用mgstage，总之你不喜欢就从config.ini去掉好了。

收到，谢谢
