### ISSUE TITLE
main mode3下，core.py中的print_files函数传入参数未更新

### ISSUE THREAD

**Issue by inertia42** [yoshiko2/AV_Data_Capture#522]
https://github.com/yoshiko2/AV_Data_Capture/blob/b13b85c057a42b9f4d49ebbaf9d93fbf9e0d44da/core.py#L862

该行中调用的print_files函数在之前的commit中引入了新的参数，此处未更新传入参数列表，使用mode3时会在此处报错。

**Comment by lededev** [comment]
我还没用模式3，你如果在用，改完跑通了提交PR吧。
