### ISSUE TITLE
windows 当番号无法识别时 移动到failed_output_folder 出错

### ISSUE THREAD

**Issue by Bohe621** [yoshiko2/AV_Data_Capture#526]
windows 设置 failed_move = 1；
当番号无法在刮削网站中找到时候，该视频文件会被重命名为 failed_output_folder设置的值 并不会移动到失败目录内；
多个视频文件无法找到的时候第一个文件会出现相同的情况，后续未找到的文件会移动到失败目录内；
试了几次，和目录里是否存在失败目录无关。
希望能够修复

**Comment by Bohe621** [comment]
![error](https://user-images.githubusercontent.com/51063830/123127839-3af3f880-d47d-11eb-9ac7-07b5b954174c.png)

**Comment by s813082** [comment]
你的config 檔得設定是什麼 failed 的folder name 
以及你可以開 debug mode 讓錯誤訊息更完整

**Comment by lededev** [comment]
我这里用你的这两个番号测试正常，无论是移动到failed目录还是在failed目录建立软连接都是成功的，无法重现你提到的移动失败情况。
而且你提供的信息不完整，你需要贴出带调试信息的输出信息以及你的config.ini文件，方便别人搭建同样的环境测试。
输出调试信息的方法是按如下修改config.ini文件。
```
[debug_mode]
switch=1
```

**Comment by Bohe621** [comment]
> 我这里用你的这两个番号测试正常，无论是移动到failed目录还是在failed目录建立软连接都是成功的，无法重现你提到的移动失败情况。
> 而且你提供的信息不完整，你需要贴出带调试信息的输出信息以及你的config.ini文件，方便别人搭建同样的环境测试。
> 输出调试信息的方法是按如下修改config.ini文件。
> 
> ```
> [debug_mode]
> switch=1
> ```

XD  不好意思没有贴出详细信息，以下是我重新测试的结果；
![failed](https://user-images.githubusercontent.com/51063830/123445329-5e987980-d60a-11eb-83b9-929d5a3e2c2b.png)


这个是我的config.ini，不知道怎么上传ini文件就把后缀改成txt上传了。
开启失败移动；失败目录改为findfailed; 更改了代理；刮削网站只使用javbus；开启了debug；
Windows 操作系统版本是 Windows 10 21H1;
[config.txt](https://github.com/yoshiko2/AV_Data_Capture/files/6717066/config.txt)

**Comment by lededev** [comment]
用你的配置文件，在Windows 10 x64 20H2下运行是正常的，我这里还没有升级21H1。
![image](https://user-images.githubusercontent.com/30518126/123459485-ea190700-d618-11eb-9148-9f321c45a5d8.png)
