### ISSUE TITLE
无码影片Tag识别成“流出”？

### ISSUE THREAD

**Issue by joaquain008** [yoshiko2/AV_Data_Capture#527]
[*]================== AV Data Capture ===================
[*]                        4.6.7
[*]======================================================
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [\\192.168.50.92\Elements\Sky_HD_Pack\新建文件夹\[uncensored]SKYHD-040.avi], the number is [SKYHD-040]
[+]Image Downloaded! JAV_output/【鈴木さとみ】SKYHD-040/SKYHD-040-流出-fanart.jpg
[+]Image Cutted!     JAV_output/【鈴木さとみ】SKYHD-040/SKYHD-040-流出-poster.jpg
[+]Wrote!            JAV_output/【鈴木さとみ】SKYHD-040/SKYHD-040-流出.nfo
[+]Thumb Add Mark:   流出,无码
[+]Poster Add Mark:  流出,无码
[*]======================================================
[+]Deleting empty folder \\192.168.50.92\Elements\Sky_HD_Pack\新建文件夹/failed
[+]Used 189.13s
[+]All finished!!!

**Comment by lededev** [comment]
现在好像是只要文件名里面有uncensored这个关键词的，都被识别为流出了。除非给无码番号的命名规则加白名单，否则不好区分这两种。
所以还是你自己手工重命名文件名吧，去掉uncensored再处理就不会有流出tag了。
