### ISSUE TITLE
用一会JavDB就会ban IP

### ISSUE THREAD

**Issue by ken7ry** [yoshiko2/AV_Data_Capture#539]
如题，已经用export_javdb9_30_from_chrome生成javdb9.json和javdb30.json两个cookies文件了，
也能搜刮到FC系列，用一会就会链接不到 ，用浏览器打开JavDB网页就显示IP异常操作被管理员禁止访问了。。。
不知道是哪里设置出问题了...

还有希望大佬能添加 http://javstore.net/ 网页搜刮支持。

**Comment by yoshiko2** [comment]
javdb没有办法 只能少用
