### ISSUE TITLE
FC2刮不了

### ISSUE THREAD

**Issue by 18E42D38dFA2** [yoshiko2/AV_Data_Capture#544]
![Screenshot 2021-07-14 112102](https://user-images.githubusercontent.com/87431855/125652276-32c3dba7-7872-402b-beab-09226b10ca9a.jpg)
![Screenshot 2021-07-14 111836](https://user-images.githubusercontent.com/87431855/125652283-5d8048df-e554-494a-b92a-076bbc59afdf.jpg)
所有网站都能正常开，一直提示代理错误

**Comment by lededev** [comment]
经测试，此番号削刮没有问题，FC2系列必须有javdb的注册用户，且正确登录并导出有效的cookies，才能成功。
https://github.com/yoshiko2/AV_Data_Capture/issues/504

**Comment by Sneer-Cat** [comment]
> 经测试，此番号削刮没有问题，FC2系列必须有javdb的注册用户，且正确登录并导出有效的cookies，才能成功。
> #504
https://github.com/lededev/AV_Data_Capture/releases/tag/pre-4.6.3
这个项目无法刮削CD2、刮完CD1就不能刮CD2了
`[WinError 183] 当文件已存在时，无法创建该文件。: 'JAV_output/'`
同样配置下，用最新的4.6.8、读取完番号就直接退了··
```
[!]Making Data for [J:\#\FC2\FC2-*****-CD1.mp4], the number is [FC2-*****]
[-]Movie Data not found!
[*]======================================================
[+]Deleting empty folder J:\#\FC2\failed
[+]Used 2.7s
[+]All finished!!!
Press enter key exit, you can check the error message before you exit...
```

**Comment by lededev** [comment]
只有javdb的注册用户才可以访问FC2数据，所以需要登录后导出cookies。

**Comment by Sneer-Cat** [comment]
> 只有javdb的注册用户才可以访问FC2数据，所以需要登录后导出cookies。

就是通过你项目得到的cookies的配置文件啊
用你项目的4.6.3可以刮，但多文件只能刮CD1，之后的刮不了

用官方最新版的就完全不能刮了··

**Comment by lededev** [comment]
最新版的需要导出两个.json文件，javdb9.json和javdb30.json，导出之前需要先分别登录这两个网站，勾选保持7天免登录。
对于还是不能的，你需要提供番号和调试信息，如果可以重现问题，也许能给你建议。

**Comment by Sneer-Cat** [comment]
> 最新版的需要导出两个.json文件，javdb9.json和javdb30.json，导出之前需要先分别登录这两个网站，勾选保持7天免登录。
> 对于还是不能的，你需要提供番号和调试信息，如果可以重现问题，也许能给你建议。

我用官方的4.6.7可以了
同样配置（export_javdb9_30_from_chrome导出的配置文件）、正常刮削CD1 CD2

**Comment by 18E42D38dFA2** [comment]
![1](https://user-images.githubusercontent.com/87431855/125773146-40ad6988-f1fd-4035-8424-02276a9c87ab.jpg)
我是把FC2官方源放第一位的，JAVDB我确实没登录，但是官网都刮不到难道不是有问题？特地开了debug模式来看了一下，和我说搜不到番号，官网我还开着呢，匹配的逻辑去哪了

**Comment by lededev** [comment]
javdb登录后能抓到你这个番号，fc2.py引擎抓不到任何页面，单元测试的番号也是抓不到的，估计是官网页面变更后，脚本没做相应更新吧。javdb抓fc2的功能是我做的，fc2.py我没碰过，不是我写的。
由于我对fc2需求不大，javdb够用的情况下，没打算帮忙修fc2.py。
你一定要用fc.py来抓的话，看看谁有时间修好它吧。

**Comment by 18E42D38dFA2** [comment]
> javdb登录后能抓到你这个番号，fc2.py引擎抓不到任何页面，单元测试的番号也是抓不到的，估计是官网页面变更后，脚本没做相应更新吧。javdb抓fc2的功能是我做的，fc2.py我没碰过，不是我写的。
> 由于我对fc2需求不大，javdb够用的情况下，没打算帮忙修fc2.py。
> 你一定要用fc.py来抓的话，看看谁有时间修好它吧。

一直用官方源来抓的，为了统一就不用其他源了，等哪天有人修再说吧

**Comment by itojito** [comment]
> > javdb登录后能抓到你这个番号，fc2.py引擎抓不到任何页面，单元测试的番号也是抓不到的，估计是官网页面变更后，脚本没做相应更新吧。javdb抓fc2的功能是我做的，fc2.py我没碰过，不是我写的。
> > 由于我对fc2需求不大，javdb够用的情况下，没打算帮忙修fc2.py。
> > 你一定要用fc.py来抓的话，看看谁有时间修好它吧。
> 
> 一直用官方源来抓的，为了统一就不用其他源了，等哪天有人修再说吧

我修好了，顺带加了个fc2club，PR已交，等作者合并。等不及的可以down我的源码自己编译运行

**Comment by Howard750527** [comment]
> > > javdb登录后能抓到你这个番号，fc2.py引擎抓不到任何页面，单元测试的番号也是抓不到的，估计是官网页面变更后，脚本没做相应更新吧。javdb抓fc2的功能是我做的，fc2.py我没碰过，不是我写的。
> > > 由于我对fc2需求不大，javdb够用的情况下，没打算帮忙修fc2.py。
> > > 你一定要用fc.py来抓的话，看看谁有时间修好它吧。
> > 
> > 
> > 一直用官方源来抓的，为了统一就不用其他源了，等哪天有人修再说吧
> 
> 我修好了，顺带加了个fc2club，PR已交，等作者合并。等不及的可以down我的源码自己编译运行

想請問大大有build好的exe可供下載嗎？謝謝您

**Comment by Sneer-Cat** [comment]
> > javdb登录后能抓到你这个番号，fc2.py引擎抓不到任何页面，单元测试的番号也是抓不到的，估计是官网页面变更后，脚本没做相应更新吧。javdb抓fc2的功能是我做的，fc2.py我没碰过，不是我写的。
> > 由于我对fc2需求不大，javdb够用的情况下，没打算帮忙修fc2.py。
> > 你一定要用fc.py来抓的话，看看谁有时间修好它吧。
> 
> 一直用官方源来抓的，为了统一就不用其他源了，等哪天有人修再说吧

官方源能不能抓女友名称？
action抓出来是卖家··
