### ISSUE TITLE
提一个关于演员名字的小建议

### ISSUE THREAD

**Issue by stevenzhang9577** [yoshiko2/AV_Data_Capture#552]
像是有多演员一起的电影，请问有可能在建立文件夹的时候把视频放到第一个演员的文件夹里，然后其他演员的文件夹下面通过软链接定位到视频所在的文件夹。请问这种方法可能实现吗？

**Comment by lededev** [comment]
在Windows下，用Everything可以实现任意的演员快速查找，如果命名规则是按演员名单作为一级文件夹名称。
