### ISSUE TITLE
欧美类带字幕影片刮削异常

### ISSUE THREAD

**Issue by 1458271** [yoshiko2/AV_Data_Capture#553]
例如blacked.17.06.29刮削正常，blacked.17.06.29-C会识别为[29-C]，使用的是今天最新的源码直接测试的。
调试发现是因为number_parser.py内，将带-C的番号识别为了带“-”番号（39和66行的if判断），导致无法进入欧美影片的正则。
不太会用git，哪位大佬有空的话可以改一下= =

**Comment by lededev** [comment]
改个名去掉-C就能通过了吧，带字幕的太少了，似乎没必要专门在程序里处理。
