### ISSUE TITLE
無法抓劇照

### ISSUE THREAD

**Issue by theturtle626** [yoshiko2/AV_Data_Capture#556]
; 剧照
[extrafanart]
switch=1
extrafanart_folder=extrafanart

使用 CLI, 雖然已經設定了 switch=1,  但只有 extrafanart 目錄, 裡面是空的

**Comment by TSUNA2256** [comment]
重新單獨下載core.py取代掉原本的core.py試試
https://github.com/yoshiko2/AV_Data_Capture/blob/master/core.py
我載的Release 4.6.8裡core.py裡第 420 & 437 行的 '/extrafanart-' 應該要是 'extrafanart-' 才對

**Comment by theturtle626** [comment]
我用 Windows exe, 我試試看 script, exe 版應該還沒修正, 會在根目錄產生 extrafanart-1.jpg

**Comment by theturtle626** [comment]
可以下載了, 感謝

**Comment by kervstk** [comment]
> 重新單獨下載core.py取代掉原本的core.py試試
> https://github.com/yoshiko2/AV_Data_Capture/blob/master/core.py
> 我載的Release 4.6.8裡core.py裡第 420 & 437 行的 '/extrafanart-' 應該要是 'extrafanart-' 才對

同样的问题，可惜对你所述的内容不知道怎么取代core.py，没有任何编程类的基础
希望作者看到有时间能抽空更新一下，谢谢

**Comment by theturtle626** [comment]
4.7.1 更新 https://github.com/yoshiko2/AV_Data_Capture/tags
