### ISSUE TITLE
4.71剧照问题

### ISSUE THREAD

**Issue by kervstk** [yoshiko2/AV_Data_Capture#559]
经过测试原来无法削刮剧照的确实已经修复，但是通过FC2CLUB削刮到的剧照文件夹已久为空，去网站看实际是存在剧照的
不知道是未支持还是BUG

**Comment by kervstk** [comment]
另外我发现从JAVDB削刮的文件夹名也不一样了，同时有些之前能削刮的现在会报错
自己去对比了一下，发现“”actor“”识别的不是JAVDB的“演員”，而是变成了“賣家”
导致了名字不一样，同时有些无法削刮
希望能修复

**Comment by kervstk** [comment]
另外FC2CLUB的演员名字识别没错
但是有个同时是好几个名字A/B/C/D/之类的
导致文件夹无限嵌套，并且名字过于长，有的也报错，希望优化一些，感谢

**Comment by kervstk** [comment]
另外FC2CLUB的演员名字识别没错
但是有的演员同时有好几个名字，网站的样式是：A/B/C/D/这样
削刮之后每个名字都建立一个文件夹，导致文件夹无限嵌套，并且有的名字过长会也报错，希望优化一下，感谢

**Comment by Sneer-Cat** [comment]
怎么刮的卖家？我FC2的还一直想刮卖家··

**Comment by lededev** [comment]
> 另外我发现从JAVDB削刮的文件夹名也不一样了，同时有些之前能削刮的现在会报错
> 自己去对比了一下，发现“”actor“”识别的不是JAVDB的“演員”，而是变成了“賣家”
> 导致了名字不一样，同时有些无法削刮
> 希望能修复

你一不提供番号，二不提供打开DEBUG的调试信息，别人连错误都没办法重现，怎么修复？

**Comment by kervstk** [comment]
> > 另外我发现从JAVDB削刮的文件夹名也不一样了，同时有些之前能削刮的现在会报错
> > 自己去对比了一下，发现“”actor“”识别的不是JAVDB的“演員”，而是变成了“賣家”
> > 导致了名字不一样，同时有些无法削刮
> > 希望能修复
> 
> 你一不提供番号，二不提供打开DEBUG的日志信息，别人连错误都没办法重现，怎么修复？

你说的DEBUG怎么提供我不太清楚，你可以告诉我我来提供
至于番号我不提供是因为我更新后刮的所有的FC2都是同样问题，所以我觉得没必要提供了，这应该是普遍问题吧？
但是既然你提了我就随便举个例子：“FC2-1774918”   

演員:白咲花♀
賣家:NIGOO

location_rule=actor+'/'+number+' - '+'['+year+']'  

会变为：“NIGOO\FC2-1774918 - [2021]”   

这样可以了吧

**Comment by kervstk** [comment]
[*]================== AV Data Capture ===================
[*]                        4.7.1
[*]======================================================
[*]严禁在墙内宣传本项目
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for [X:\「5码」\FC2-1774918-CD1.mp4], the number is [FC2-1774918]
[-]Connect retry 1/3
[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=10)
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]HTTPSConnectionPool(host='fc2club.net', port=443): Read timed out. (read timeout=10)
[-]Image Download :  Connect retry 1/3
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/FC2-1774918-CD1-fanart.jpg
[-]Image Download :  Connect retry 1/3
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-1.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-2.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-3.jpg
[-]Image Download :  Connect retry 1/3
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-4.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-5.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-6.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-7.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-8.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-9.jpg
[+]Image Downloaded! JAV_output/NIGOO/FC2-1774918 - [2021]/extrafanart/extrafanart-10.jpg
[+]Image Copyed!     JAV_output/NIGOO/FC2-1774918 - [2021]/FC2-1774918-CD1-poster.jpg
[+]Wrote!            JAV_output/NIGOO/FC2-1774918 - [2021]/FC2-1774918-CD1.nfo
[*]======================================================
[+]Used 257.77s
[+]All finished!!!
Press enter key exit, you can check the error message before you exit...


不知道这个有没有用，也一并附上吧

**Comment by lededev** [comment]
这个日志没有开调试信息，看不到是哪个python脚本文件导致的故障，你需要修改config.ini
```
[debug_mode]
switch=0
```
改为
```
[debug_mode]
switch=1
```
