### ISSUE TITLE
由于目标计算机拒绝，无法连接

### ISSUE THREAD

**Issue by drawAgirl** [yoshiko2/AV_Data_Capture#561]
![image](https://user-images.githubusercontent.com/39159849/129013658-54f29ec4-a64b-485e-9750-64cd06e38a5b.png)

**Comment by theturtle626** [comment]
一樣錯誤

**Comment by theturtle626** [comment]
其中一次
Making Data for [W:\AV\夏希まろん\2021-05-28 [WAAA-063]\WAAA-063-C.mp4], the number is [WAAA-063]

[-]Connect retry 1/3
[-]Connect retry 2/3
[-]Connect retry 3/3
[-]Connect Failed! Please check your Proxy or Network!
[-]HTTPSConnectionPool(host='cn.airav.wiki', port=443): Read timed out. (read timeout=10)

**Comment by lededev** [comment]
可以试试用美国IP或者德国、英国、加拿大、澳大利亚IP，用香港IP会有很多源站点连不上。

**Comment by bravoleexin** [comment]
我也出现这个问题了，换了IP也没效果
