### ISSUE TITLE
刮完后文件都被删了

### ISSUE THREAD

**Issue by 35655a** [yoshiko2/AV_Data_Capture#567]
刮完后我的片都被删了 
![微信截图_20210813140113](https://user-images.githubusercontent.com/52121236/129314232-5d0bdcf1-d06c-4c66-bb5a-4534611f5c87.png)

**Comment by lededev** [comment]
Python os.rmdir() 只能删除空目录，如果目录内有文件不可能执行成功，请不要谎报bug。

**Comment by 35655a** [comment]
刚才又试过了，因为我是挂载阿里盘当本地磁盘，使用完就出现删所有文件的情况。在本地硬盘上测试没有问题

https://user-images.githubusercontent.com/52121236/129476365-abe279e0-152a-4ce1-bcd6-69aecac9e5c5.mp4

**Comment by lededev** [comment]
阿里云盘的挂载程序实现文件系统功能不标准，建议向其上报此bug。
至于此应用的对你适用的暂时解决办法是删除AV_Data_Capture.py中198-200行，然后重新编译。
```
    rm_empty_folder(conf.success_folder())
    rm_empty_folder(conf.failed_folder())
    rm_empty_folder(os.getcwd())
```
建议作者 @yoshiko2 在配置文件中加个关闭此功能的可选项，毕竟删目录是破坏性操作，并不是每个人都需要，做成默认不可关闭也不太合适。
