### ISSUE TITLE
二次刮削问题

### ISSUE THREAD

**Issue by joast888** [yoshiko2/AV_Data_Capture#573]
如果再次进行刮削时，目录内存在-trailer.mp4的预告片，会被当成正片重新刮一遍，并覆盖点正确的文件。希望能排除预告片

**Comment by lededev** [comment]
有番号吗，我试一下

**Comment by joast888** [comment]
所有番号都一一样。比如文件夹中同时存在：ABP-713.mp4 与ABP-713-trailer.mp4  在刮削过程中会刮2次，第二次会用trailer文件覆盖原来的正确文件。

**Comment by lededev** [comment]
你确定ABP-713能得到trailer？我打开config.ini中的[trailer]switch=1，并没有抓到-trailer.mp4，无法重现你描述的bug。

**Comment by joast888** [comment]
abp-713是举个例子。我重新刮了SGKX-007。把结果发上来。您看一下。
第一次刮正常的，会生成-trailer。第二次刮会把trailer也刮一遍。最后覆盖正确文件。能都在识别番号时，排除trailer
[1.txt](https://github.com/yoshiko2/AV_Data_Capture/files/7104770/1.txt)
![Screenshot_20210903_171046_com microsoft skydrive](https://user-images.githubusercontent.com/61902692/131981682-53b33a95-6685-4948-bf13-891ee5e756fd.jpg)

**Comment by joast888** [comment]
感谢。我试下效果

**Comment by joast888** [comment]
新的代码没问题了。感谢
