### ISSUE TITLE
是否有设置参数可以重命名视频文件？

### ISSUE THREAD

**Issue by lihansunbai** [yoshiko2/AV_Data_Capture#577]
按照 WIKI 中的说明，naming_rule 参数为媒体库内标题的命名规则规则，NFO文件内标题<title>命名规则 影片命名规则：默认 naming_rule=number+'-'+title。
请问是否有参数控制可以在刮削时不仅生成NFO文件中的文件名，同时也重新命名本地文件？

**Comment by mastyu** [comment]
的确  我也觉得有必要加入这个参数

**Comment by lededev** [comment]
'-'号同时也是番号匹配识别时的番号组成部分。如果允许随意定义修改后的视频文件名，那么就不能保证再次刮削时提取番号的正确性。

**Comment by lededev** [comment]
我为了方便Everything搜索，也将NFO中的一些元数据暴露给了文件名，但我是利用脚本扫描全部.NFO，在同一目录下另外建了一个.txt空文件，来暴露视频的元数据。
并没有对视频文件重命名。

**Comment by lihansunbai** [comment]
#

**Comment by lihansunbai** [comment]
确实，按照多次刮削的思路，修改文件名会影响二次和后续刮削。

那么，可以把重命名文件名的功能放到“整理模式”下，作为整理模式的一个可选参数。

**Comment by lededev** [comment]
> 确实，按照多次刮削的思路，修改文件名会影响二次和后续刮削。
> 
> 那么，可以把重命名文件名的功能放到“整理模式”下，作为整理模式的一个可选参数。

我反对在整理模式改视频文件名，整理模式目前是无损的，视频文件不仅不移动位置，也没有改变名称。
如果引入改名，整理模式再次运行，就可能出现提取番号错误，无法重新整理的问题，那就不是整理而是破坏了。

也许在模式1的移动文件行为下，规定两三种固定格式重命名，视频文件名中附加一些元数据的文件更名，还是可行的。
但不能太宽泛，随意自定义，那样很容易引入番号歧义。

**Comment by lihansunbai** [comment]
> 我反对在整理模式改视频文件名，整理模式目前是无损的，视频文件不仅不移动位置，也没有改变名称。
> 如果引入改名，整理模式再次运行，就可能出现提取番号错误，无法重新整理的问题，那就不是整理而是破坏了。
> 
> 也许在模式1的移动文件行为下，规定两三种固定格式重命名，视频文件名中附加一些元数据的文件更名，还是可行的。
> 但不能太宽泛，随意自定义，那样很容易引入番号歧义。

同意固定格式重命名的思路，或者是限定重命名的格式中必须保留番号元数据。

**Comment by lededev** [comment]
做一个能比较自由定义文件名的草案吧：
假设原先的视频文件为：番号.mp4
草案提出注释语法#号，应用于视频文件命名规则。
新的视频文件为：番号#注释.mp4
其中注释部分可以是排除番号后的任意命名规则的组合。
程序的番号匹配识别部分的代码，会将文件名中第一个#号到最后一个.号之间的内容视为注释，完全忽略。

**Comment by lihansunbai** [comment]
是否可以将草案限制命名的思路调换为限定番号出现在文件名的开始，即：番号+其他任意命名规则的组合。不接受其他番号不出现在开头的情况。这样get_number函数就只用检查开头，方便正则的匹配。

**Comment by lededev** [comment]
> 是否可以将草案限制命名的思路调换为限定番号出现在文件名的开始，即：番号+其他任意命名规则的组合。不接受其他番号不出现在开头的情况。这样get_number函数就只用检查开头，方便正则的匹配。

那样的话，用户下载的 1pon-abc-123456.mp4就需要改名成abc-123456才能削刮了，所有人的改名工作量都增加了。
我的草案设计了一种特殊语法，只需要对这种语法进行注释过滤，而这种语法是为了实现本issue的功能，重命名时遵循的格式。
原先的番号识别功能完全不变。

**Comment by lededev** [comment]
按草案规则写了代码改名试了试，例如：
```
[Name_Rule]
video_file_rename_rule=title+'['+tag+']'

```
对番号JUL-161得到的文件名结果是：
`JUL-161#永遠に終わらない、中出し輪●の日々。-北条麻妃[高畫質,DMM獨家,數位馬賽克,單體作品,苗條,中出,成熟的女人,已婚婦女].mp4`
但这样单独对视频文件改名，似乎还是不行，Kodi扫描不到，还必须改名.nfo文件，让.mp4视频文件名与.nfo元数据文件名完全一致，才能生效。

**Comment by lededev** [comment]
这样的话，封面封底图片文件也得这么改名，除了按规则修改后的文件，还得追加上-fanart.jpg -poster.jpg -thumb.jpg，文件名更长了。
我认为给视频文件起长文件名代价太大，还是保持原样仅仅番号加视频后缀吧。
需要在文件系统中暴露视频元数据信息的，还是用脚本生成一个文件名包含元数据的.txt空文件好了。
草案实现的这部分功能代码我删掉了。

**Comment by lededev** [comment]
我写的搜索全部.nfo并生成元数据中genre数据列表到.txt空文件的脚本，我贴一份，修改脚本可以导出.nfo中其它元数据信息到文件名。
测试运行环境是Windows10 x64 MSYS2，MSYS2需要安装libxml包支持pacman -S libxml，在ubuntu 20.04 LTS下应该也能运行，不过我没测试过。
执行方法是先切换到JAV_output目录下，运行~/jav_touchall.sh，所有视频子目录下就会导出类似`SSNI-826-C DMM独家 偶像艺人 巨乳 乳液 单体作品 薄马赛克 妓女 中文字幕.txt`这样的空文件，再用Everything输入关键词搜索到.txt文件后，按SHIFT+ENTER能打开视频文件目录。
文件名:jav_touchall.sh
```bash
#!/bin/sh

find . -type f -iname "*.nfo" -exec $HOME/jav_touch_genre.sh '{}' \;

```
文件名:jav_touch_genre.sh
```bash
#!/bin/sh
[ ${#1} -lt 2 ] && exit 1
JVDIR=$(dirname "$1")
NFO=$(basename "$1")
[ -d "$JVDIR" ] || exit 2
cd "$JVDIR"
[ -f "$NFO" ] || exit 3
FANHAO=$(basename "$NFO" .nfo | sed -e 's#^\([^\.| ]\+\).*$#\1#')
[ "${#FANHAO}" -gt 2 ] || exit 4
TT="$FANHAO $(cat "$NFO" | xmllint --xpath "//genre/text()" - | xargs -n 200)"
[ "${#TT}" -gt 2 ] || exit 5
TT=$(echo "${TT}" | sed -e 's# xxx##;s# 多選提交##' -e 's#:#꞉#g' -e 's#/#⧸#g' -e 's#[[:blank:]]*$##' )
touch "$TT.txt"
#mv -f "$NFO" "${TT}.nfo"
#rm -f "${FANHAO}\*.txt"

```

**Comment by lihansunbai** [comment]
感谢大佬~

我自己写一个脚本，提取NFO文件中的文件名重命名文件。

这个参数等未来发展再议吧。

**Comment by lededev** [comment]
你修改这个脚本，也能把.nfo .txt .jpg .mp4全部改名成你想要的形式。
