### ISSUE TITLE
请问可以在vps上吗挂载谷歌盘进行刮削吗

### ISSUE THREAD

**Issue by a13864209110** [yoshiko2/AV_Data_Capture#585]
如题，我使用rclone将谷歌盘挂载到了vps根目录
并且安装了avdc，发现在vps的本地文件夹内avdc可以给到权限并运行，但在挂载的谷歌盘内，vps并不能将.py当做程序使用。
请问有哥哥知道如何解决吗

**Comment by lededev** [comment]
你可以将.py依然保持在vps本地目录，执行时带`-p`参数指定放视频文件的谷歌盘路径。可能还要修改config.ini里的failed_output_folder和success_output_folder到谷歌盘的路径下。
例如:
```
git clone https://github.com/yoshiko2/AV_Data_Capture.git ~/avdc
cd ~/avdc
python3 ./AV_Data_Capture.py -p /mnt/google_drive/video
```
**~/avdc/config.ini**
```
[common]
failed_output_folder=/mnt/google_drive/failed
success_output_folder=/mnt/google_drive/AV_output

```

**Comment by a13864209110** [comment]
哈哈哈哈原来这么简单的吗，我是sb愣是没想到，成功了，谢谢兄弟指点了
