### ISSUE TITLE
可识别的番号被错误映射成了其他影片

### ISSUE THREAD

**Issue by leo-1994** [yoshiko2/AV_Data_Capture#595]
版本号4.7.1，使用docker部署，将SDJ-009 SRSY-001识别为了ADZ335
日志：
[!]Making Data for [/app/data/1/SDJ-009.mp4], the number is [SDJ-009]
[+]Image Downloaded! data/output/本橋実来/ADZ335/ADZ335-fanart.jpg
[+]Image Cutted!     data/output/本橋実来/ADZ335/ADZ335-poster.jpg
[+]Wrote!            data/output/本橋実来/ADZ335/ADZ335.nfo

[!]Making Data for [/app/data/1/SRSY-011.mp4], the number is [SRSY-011]
[+]Image Downloaded! data/output/本橋実来/ADZ335/ADZ335-fanart.jpg
[+]Image Cutted!     data/output/本橋実来/ADZ335/ADZ335-poster.jpg
[+]Wrote!            data/output/本橋実来/ADZ335/ADZ335.nfo
![image](https://user-images.githubusercontent.com/24997121/134613878-ccfbd65c-fc50-429c-ae4d-90303f7d98c3.png)

**Comment by lededev** [comment]
PR https://github.com/yoshiko2/AV_Data_Capture/pull/591 已经修了，不要重复发，你可以到Active页面下载自动编译好的对应版本的程序，或者按 https://github.com/yoshiko2/AV_Data_Capture/issues/587 的配置中去掉xcity的临时解决办法。
