### ISSUE TITLE
关于添加其他系列影片元数据抓取的适配

### ISSUE THREAD

**Issue by yoshiko2** [yoshiko2/AV_Data_Capture#6]
## 请提供以下
* 番号的格式
* 元数据全面的网站

**Comment by wbzdtmp** [comment]
不清楚元数据怎么看，不过网络片商那边的数据比较全面，其中
无码片商 www.aventertainments.com，　有码片商　www.dmm.co.jp (需日本代理)

我之前就从aventertainments抓了好多系列的数据，　图片已经各种信息挺丰富全面的.
