### ISSUE TITLE
建议优化FC2的多分集导入

### ISSUE THREAD

**Issue by Locri666** [yoshiko2/AV_Data_Capture#60]
很多FC2的片子会有很多集（特典），片源以_1 _2等结尾。
在修改成-cd1，-cd2后，也无法将分集正常分类至Emby，会提示文件已存在。猜测是共用同一个番号的原因。还请求作者优化 ：)

**Comment by yoshiko2** [comment]
没这个问题吧。。。是不是文件重复了
