### ISSUE TITLE
win下路径斜杠显示

### ISSUE THREAD

**Issue by sino1641** [yoshiko2/AV_Data_Capture#603]
CLI会直接输出斜杠路径，而win使用反斜杠代表路径，请问能否根据系统匹配对应的斜杠与反斜杠，感谢。
![image](https://user-images.githubusercontent.com/13870295/135595951-0847e707-1029-4b55-8a9a-16d28d884eb5.png)

**Comment by lededev** [comment]
我也觉得可以，不过我在外面玩不方便用git，你也是contributor你自己提交吧。
core.py:def create_folder()的最后一行`return path`改成`return os.path.normcase(path)`就行了。
结果输出里的正斜杠是配置文件中的location_rule引入的，配置里那么写才通用。
