### ISSUE TITLE
遇到文件名重复就退出

### ISSUE THREAD

**Issue by yjd** [yoshiko2/AV_Data_Capture#61]
试用完，
把一些没匹配到的，全给移到一个目录下，举例原本某个视频有文件夹可以说明这个视频来自xx或者xxx介绍，或者一些国外的自拍视频下载时是在一个目录下。现在目录结构全打乱了。

逻辑应该改改，匹配到的自动归类JAV_output下。
没匹配到的就不要处理。留给后期人工手动去处理，自行该移哪就移哪。
不应该一股脑遍历所有文件移动到软件目录。再开始匹配和下载。

**Comment by Leonyan938** [comment]
你打开config.ini 把failed_output_folder=后面的“failed”删掉就好了啊     删掉后就不自动移动了

**Comment by yjd** [comment]
多谢！我试试。之前看主页介绍。没说到你这样的配置方法。

**Comment by yjd** [comment]
根据测试。模式1，2都无效。
