### ISSUE TITLE
1.7版本 素人系列总是失败

### ISSUE THREAD

**Issue by Swiftfrog** [yoshiko2/AV_Data_Capture#62]
1.7版本，素人系列搜索失败。

**Comment by Swiftfrog** [comment]
比如300MAAN，259LUXU等，JAVBUS上面没有此类元数据。记得之前1.2是可以的。很久不用了，不知道哪里的问题。

**Comment by yoshiko2** [comment]
试一下使用日本代理。

Swiftfrog <notifications@github.com> 于 2019年12月10日周二 下午4:54写道：

**Comment by Swiftfrog** [comment]
> 试一下使用日本代理。 Swiftfrog <notifications@github.com> 于 2019年12月10日周二 下午4:54写道：
> […](#)

依旧失败，FC，素人这类就失败，其他正常。

**Comment by Leonyan938** [comment]
新版本可以搜到素人系列了
