### ISSUE TITLE
建议增加手动精确刮削的功能 

### ISSUE THREAD

**Issue by lqxx2005** [yoshiko2/AV_Data_Capture#63]
建议增加手动精确刮削的功能 在终端输入javbus影片相应的网址 直接刮削相应信息

**Comment by Leonyan938** [comment]
是的 这个功能如果可以加上就太好了  有些番号重复的软件没法识别  比如NTRD-010   这个片子在JAVBUS上有重复番号，我命名番号为NTRD-010-2，和JAVBUS一样的，但是软件也还无法识别，会把-2给忽略掉只搜索NTRD-010

**Comment by yoshiko2** [comment]
下个版本考虑一下。。
