### ISSUE TITLE
最新版本无法刮削&求刮削硬链接文件

### ISSUE THREAD

**Issue by lbcz-tian** [yoshiko2/AV_Data_Capture#635]
大佬好🥺
我使用最新的命令行版本和CLI版本都无法刮削，命令行debug报错如下图，求大佬帮忙看看
![](https://s3.bmp.ovh/imgs/2021/11/f0908fe244ac5f83.png)

还有就是能不能原生支持硬链接文件的刮削呀？我按issue自己改的老版本可以刮削硬链接文件，但还是希望原生支持🥺

**Comment by lbcz-tian** [comment]
> PS F:\AV_Data_Capture-master-5.0.3> python .\AV_Data_Capture.py
[*]================== AV Data Capture ===================
[*]                        5.0.3
[*]======================================================
[*]严禁在墙内宣传本项目
[+]Start at 2021-11-13 15:58:32
[+]Load Config file 'F:\AV_Data_Capture-master-5.0.3\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             15:58:33
[!] [IPX-742] As Number making data for 'F:\AV_Data_Capture-master-5.0.3\ipx-742-C.mp4'
[+]select airav
[+]Find movie [IPX-742] metadata on website 'airav'
Traceback (most recent call last):
  File "F:\AV_Data_Capture-master-5.0.3\WebCrawler\__init__.py", line 293, in get_data_from_json
    json_data[cc] = actor_mapping_data.xpath('a[contains(@keyword, $name)]/@zh_cn', name=json_data[cc])[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\AV_Data_Capture-master-5.0.3\AV_Data_Capture.py", line 576, in <module>
    main()
  File "F:\AV_Data_Capture-master-5.0.3\AV_Data_Capture.py", line 548, in main
    create_data_and_move(movie_path, zero_op, oCC)
  File "F:\AV_Data_Capture-master-5.0.3\AV_Data_Capture.py", line 393, in create_data_and_move
    core_main(file_path, n_number, oCC)
  File "F:\AV_Data_Capture-master-5.0.3\core.py", line 596, in core_main
    json_data = get_data_from_json(number, oCC)  # 定义番号
  File "F:\AV_Data_Capture-master-5.0.3\WebCrawler\__init__.py", line 302, in get_data_from_json
    json_data[cc] = oCC.convert(json_data[cc])
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\opencc\__init__.py", line 87, in convert
    retv_i = libopencc.opencc_convert_utf8(self._od, text, len(text))
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF
Exception ignored in: <function OpenCC.__del__ at 0x0000027BF6D66B00>
Traceback (most recent call last):
  File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\site-packages\opencc\__init__.py", line 99, in __del__
    libopencc.opencc_close(self._od)
OSError: exception: access violation reading 0xFFFFFFFFFFFFFFFF

**Comment by yoshiko2** [comment]
硬链接你可以pull requests, 建议使用二进制版本，我测试没问题

**Comment by lededev** [comment]
避免刮削软/硬链接是我在几个月前加上的。
为了避免重复刮削做种的电影，当做种电影以软连接方式刮削过后，确认与番号对应无误，我会批量转为硬链接，然后将之移出output目录，放到最终保存位置。
而继续做种的文件就不应该被再次刮削了，由于这些做种文件都因为上一步批量转换硬链接，变成了对等的硬链接文件，它们是不该被再次刮削的。而且做种完成后，我会搜索做种目录中的全部硬链接并将之删除。

你既然将之转换为了硬链接，想必至少有两份吧，也许你有其他用途，这个我就不得而知了。不过欢迎提交PR，增加支持刮削硬链接的配置可选项，让我们各自的需求都可以满足。而你也不必单独维护一个版本。

**Comment by lbcz-tian** [comment]
> 硬链接你可以pull requests, 建议使用二进制版本，我测试没问题

我这个报错是下载的源码，然后刮削普通文件报的错😳，下载release的程序刮削普通文件也一样会报错，不知道为什么

**Comment by lbcz-tian** [comment]
> 避免刮削软/硬链接是我在几个月前加上的。 为了避免重复刮削做种的电影，当做种电影以软连接方式刮削过后，确认与番号对应无误，我会批量转为硬链接，然后将之移出output目录，放到最终保存位置。 而继续做种的文件就不应该被再次刮削了，由于这些做种文件都因为上一步批量转换硬链接，变成了对等的硬链接文件，它们是不该被再次刮削的。而且做种完成后，我会搜索做种目录中的全部硬链接并将之删除。
> 
> 你既然将之转换为了硬链接，想必至少有两份吧，也许你有其他用途，这个我就不得而知了。不过欢迎提交PR，增加支持刮削硬链接的配置可选项，让我们各自的需求都可以满足。而你也不必单独维护一个版本。

我就是按照大佬你的方法把判断的代码注释掉了，就可以刮削硬链接了，不过大佬能告知下怎么批量软转硬吗？( •̀ ω •́ )

**Comment by lbcz-tian** [comment]
我在另一台主机上配置好了环境，用源码刮削，又报了下面的错：

> [*]================== AV Data Capture ===================
[*]                        5.0.3
[*]======================================================
[*]严禁在墙内宣传本项目
[+]Start at 2021-11-14 08:41:16
[+]Load Config file 'C:\Users\15361\Downloads\AV_Data_Capture-master\config.ini'.
[+]Enable debug
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             08:41:17
[!] [IPX-177] As Number making data for 'C:\Users\15361\Downloads\AV_Data_Capture-master\ipx-177.mp4'
[+]select javbus
[!]MP 进程[airavwiki]运行1.417秒，结束于08:41:19返回结果: ミニスカートとニーハイから覗くきれいな素肌、ニーソの太ももへの食い込み…全てを兼ね
備えた「絶対領域」！ピチピチの肌感、ぷにぷにハミもも思わず触りたくなること間違いなし！さらに絶対領域を眺めながら足コキ、股コキ、尻コキ！完全着衣で堪能！！ニーハイを履いた小悪魔に罵られながらイク！！「マヂきもいんだけど！触り方が！！」「完璧すぎる、、絶対領域はぁはぁ」
[-]MP getOutline_xcity Error: list index out of range, number [IPX-177].
[!]MP 进程[xcity]运行1.826秒，结束于08:41:19返回结果: [空]
[!]MP 进程[airav]运行2.436秒，结束于08:41:20返回结果: 迷你裙與過膝襪間的絕對領域！讓人忍不住想摸的Q彈肌膚、肉感大腿！邊看這絕對領域邊足交、
股交、臀交！享受著衣幹砲快感，讓身穿過膝襪的小惡魔罵到高潮！
[!]MP 进程[avno1]运行2.960秒，结束于08:41:21返回结果: 迷你裙与过膝袜间的绝对领域！让人忍不住想摸的Q弹肌肤、肉感大腿！边看这绝对领域边足交、
股交、臀交！享受着衣幹砲快感，让身穿过膝袜的小恶魔骂到高潮！
[-]MP getOutline_amazon Error: title and number not found, number [IPX-177], title: 生意気な妹にニーハイを履かせ僕だけの「絶対領域」を誕生させ僕好みに痴女らせた。 相沢みなみ
[!]MP 进程[amazon]运行1.980秒，结束于08:41:21返回结果: [空]
[!]Storyline线程池模式运行5个任务共耗时(含启动开销)3.401秒，结束于08:41:21，[选中avno1字数:73]，airav字数:73，airavwiki字数:175，xcity:空，amazon:空
[+]Find movie [IPX-177] metadata on website 'javbus'
Traceback (most recent call last):
  File "C:\Users\15361\Downloads\AV_Data_Capture-master\AV_Data_Capture.py", line 576, in <module>
    main()
  File "C:\Users\15361\Downloads\AV_Data_Capture-master\AV_Data_Capture.py", line 548, in main
    create_data_and_move(movie_path, zero_op, oCC)
  File "C:\Users\15361\Downloads\AV_Data_Capture-master\AV_Data_Capture.py", line 393, in create_data_and_move
    core_main(file_path, n_number, oCC)
  File "C:\Users\15361\Downloads\AV_Data_Capture-master\core.py", line 596, in core_main
    json_data = get_data_from_json(number, oCC)  # 定义番号
  File "C:\Users\15361\Downloads\AV_Data_Capture-master\WebCrawler\__init__.py", line 241, in get_data_from_json
    open(str(Path.home() / '.local' / 'share' / 'avdc' / 'c_number.json'), 'r', encoding="utf-8"))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\15361\\.local\\share\\avdc\\c_number.json'

**Comment by lededev** [comment]
> 我在另一台主机上配置好了环境，用源码刮削，又报了下面的错：
> > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\15361\.local\share\avdc\c_number.json'

今天才有时间试试5.0.3，这个错误我也遇到了，已经修复。
你是源码执行，直接把[PR](https://github.com/yoshiko2/AV_Data_Capture/pull/636)拉过来应该就行了。

```python
git pull origin pull/636/head --no-edit
python3 ./AV_Data_Capture.py --help
```

**Comment by lbcz-tian** [comment]
当我把机器翻译关了之后就可以刮削了，但是这样的话标题就没有翻译额(⊙﹏⊙)

**Comment by lbcz-tian** [comment]
> > 我在另一台主机上配置好了环境，用源码刮削，又报了下面的错：
> > > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\15361.local\share\avdc\c_number.json'
> 
> 今天才有时间试试5.0.3，这个错误我也遇到了，已经修复。 你是源码执行，直接把[PR](https://github.com/yoshiko2/AV_Data_Capture/pull/636)拉过来应该就行了。
> 
> ```python
> git pull origin pull/636/head --no-edit
> python3 ./AV_Data_Capture.py --help
> ```
感谢大佬，确实可以了🤤

**Comment by lbcz-tian** [comment]
> > 我在另一台主机上配置好了环境，用源码刮削，又报了下面的错：
> > > FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\15361.local\share\avdc\c_number.json'
> 
> 今天才有时间试试5.0.3，这个错误我也遇到了，已经修复。 你是源码执行，直接把[PR](https://github.com/yoshiko2/AV_Data_Capture/pull/636)拉过来应该就行了。
> 
> ```python
> git pull origin pull/636/head --no-edit
> python3 ./AV_Data_Capture.py --help
> ```

对了大佬，能分享下软转硬的方法吗？这样比按之前的方法改方便些😳

**Comment by lededev** [comment]
> 对了大佬，能分享下软转硬的方法吗？这样比按之前的方法改方便些😳

我写了一个Windows 10下面的PowerShell脚本完成批量软转硬，以及批量删硬链接。只能用Windows 10自带的Powershell，最新跨平台的下载版本Powershell可能不支持。
先启动一个Powershell目录窗口，注意用普通用户权限，不要用管理员权限，用管理员权限可能无法执行，可以将这个脚本放在PATH路径下面，方便任意地点执行，我放在%USERPROFILE%\.avdc\目录下面的，和avdc.exe放一起，然后将这个目录加入了PATH环境变量。
用法： 
* 显示目标目录内的所有软硬链接
`winlinks.ps1 目标目录`
* 软链接转硬链接
`winlinks.ps1 目标目录  -Action s2h`
* 硬链接转软链接(未经过详细测试)
`winlinks.ps1 目标目录  -Action h2s`
* 删除目标目录内**全部软硬链接**(危险操作，需确认一次)
`winlinks.ps1 目标目录  -Action DELETE`
不支持脚本附件上传，贴源代码吧。
```powershell
<#
.SYNOPSIS

List or change links. BSD LICENSE by lededev @ github

.DESCRIPTION

List all links.
Change Hard Links to Symbolic Links, or change Symbolic Links to Hard Links.
Delete Links.

.PARAMETER TargetDir

Any valid Windows PATH

.PARAMETER Action

list: list all links. Default action.
h2s: convert Hard Links to Symbolic Links.
s2h: convert Symbolic Links to Hard Links.
DELETE: Delete links.

.EXAMPLE

PS> .\thisprogram.ps1 .
[h] Z:\mh.c
[h] Z:\t\m.c

PS> .\thisprogram.ps1 Z:\t -Action h2s
[s] Z:\t\m.c [h->s]

PS> .\thisprogram.ps1 Z:\t -Action DELETE
[s] Z:\t\m.c [DELETED]
#>
param($TargetDir, $Action)

#ps win10 20H1 create relpath symlink has bug, ps v7.2.0-pv2 get hard link target has bug
# dont use $cmd_create_symlink = $false
$cmd_create_symlink = $true

if($TargetDir -eq $null) {
    Get-Help $MyInvocation.MyCommand.Path -Detailed
    exit 0
}
if((Get-Item $TargetDir) -is [System.IO.DirectoryInfo]){
    $target = "$TargetDir"
}else{
    Write-Output "ERROR: TargetDir $TargetDir is not found!"
    exit 1
}
function fn_list($f, $tp) {
    $ostr = $f.FullName
    Write-Output "[$tp]$ostr"
}
function fn_delete($f, $tp) {
#    $f.Delete()
    $ostr = $f.FullName
    Remove-Item -LiteralPath "$ostr" -Force
    Write-Output("[$tp]$ostr[DELETED]");
}
function fn_h2s($f, $tp) {
    if( $tp -eq "s" ) {return}
    $file_fullname = $f.FullName
    $fullpath = Split-Path -Path $file_fullname
    $hardlink_target = $f.Target | select -Last 1
    if( $hardlink_target -eq $null ) {return}
    $targetobj = Get-Item $hardlink_target
    $target_fullname = $targetobj.FullName
    $target_fullpath = Split-Path -Path $target_fullname
    if( $target_fullpath.contains("$fullpath") ) {
        Write-Output "Warning: This Hard link [$file_fullname] point to a target [$target_fullname] in same directory or it's subdirectory, recurse change hardlink to symlink in same directory tree may cause problem such as symlink -> symlink, skip this one."
        return
    }
#Write-Output("DBG: $fullpath $hardlink_target", $f.Target)
    Do {
        $RandomFileName = "$fullpath\" + [System.IO.Path]::GetRandomFileName()
    }
    Until(!(Test-Path $RandomFileName))
    
    $target_fullpath = Split-Path -Path $hardlink_target
    Push-Location $fullpath
    $target_relpath = Resolve-Path -relative $target_fullpath
    $target_relfile = "$target_relpath\" + (Split-Path -Leaf $hardlink_target)
    Pop-Location
    if( $cmd_create_symlink )
    {
        cmd /C mklink "$RandomFileName" "$target_relfile" | out-null
    }
    else
    {
        try {
        #Write-Output "DBG: New-Item -ItemType SymbolicLink -Path $RandomFileName -Target $target_relfile"
        Push-Location $fullpath
            $random_nameonly = Split-Path -Leaf $RandomFileName
            New-Item -ItemType SymbolicLink -Name "$random_nameonly" -Target "$target_relfile"
        }
        catch {
            Write-Output "ERROR: Create Symbolic link failed."
            exit 3
        }
        finally {
            Pop-Location
        }
    }
    $testfile = Get-Item "$RandomFileName"
    if( $testfile.LinkType -ne "SymbolicLink" ){
        $testfile.Delete()
        Write-Output "ERROR: Create symbolic link type check failed!"
        exit 4
    }
    $test_target = $testfile.Target
    $tarobj = Get-Item "$test_target"
    if( $tarobj.LinkType -eq "SymbolicLink" ){
        Write-Output "ERROR: find problem, symlink's $RandomFileName target become symlink $test_target !"
        exit 5
    }
    $f.Delete()
    Rename-Item -Path "$RandomFileName" -NewName "$file_fullname"
    $ostr = $f.FullName
    Write-Output "[s]$ostr[h->s]$test_target"
}

Function Log {
    [CmdletBinding()]
    Param(
    [Parameter(Mandatory=$False)]
    [ValidateSet("INFO","WARN","ERROR","FATAL","DEBUG")]
    [String]
    $Level = "INFO",

    [Parameter(Mandatory=$True)]
    [string]
    $Message,

    [Parameter(Mandatory=$False)]
    [string]
    $logfile = "D:\Logs\$Env:computername.log"
    )

    $Stamp = (Get-Date).toString("yyyy/MM/dd HH:mm:ss")
    $Line = "$Stamp $Level $Message"
    If($logfile) {
        Add-Content $logfile -Value $Line
    }
    Else {
        Write-Output $Line
    }
}

function fn_s2h($f, $tp) {
    if( $tp -eq "h" ) {return}
    $fnm = $f.FullName
    $symlink_target = $f.Target
    $sDrv = $f.PSDrive.Name
    $fullpath = Split-Path -LiteralPath "$fnm"
    $saveCD = Get-Location
    try {
        Set-Location -LiteralPath "$fullpath"
        If( -Not (Test-Path -LiteralPath "$symlink_target") ) {
            Log -Verbose WARN "sym target:$symlink_target invalid."
            return
        }
        try {
            $abspath = Resolve-Path -LiteralPath "$symlink_target"
            if( (Get-Item -LiteralPath "$abspath").PSDrive.Name -ne $sDrv ) {
                Log -Verbose WARN "target:$symlink_target and symlink:$fnm not in same Drive."
                return
            }
        }
        catch {
            Log -Verbose WARN "$symlink_target path ERROR, $fnm"
            return
        }
        $targetobj = Get-Item -LiteralPath "$symlink_target"
        if( -Not $targetobj -is [System.IO.FileInfo] -Or $targetobj.LinkType -eq "SymbolicLink" ) {
            Log -Verbose WARN "This Symbolic link $fnm is not point to a regular file -> $symlink_target, can not be changed to Hard link!"
            return
        }
        Do {
            $RandomFileName = ".\" + [System.IO.Path]::GetRandomFileName()
        }
        Until(!(Test-Path -LiteralPath $RandomFileName))
        try {
    #Write-Output("DBG: b4new-i $RandomFileName $symlink_target")
            #$escpath = ([WildcardPattern]::Escape([WildcardPattern]::Escape("$abspath")))
            #New-Item -ItemType HardLink -Path "$RandomFileName" -Value "$escpath" #| out-null
            cmd /C mklink /H "$RandomFileName" "$abspath" | out-null
            $testfile = Get-Item -Path "$RandomFileName"
            if( $testfile.LinkType -ne "HardLink" ){
    #Write-Output("DBG: enter del", $testfile.LinkType, $file_fullname)
                $testfile.Delete()
                throw "Error: Create hard link type check failed!"
            }
            $test_target = $testfile.Target
    #Write-Output("DBG: $test_target $file_fullname")
            $f.Delete()
            Rename-Item -Path "$RandomFileName" -NewName "$fnm"
        }
        catch {
             Log -Verbose ERROR "Create Hard link failed: $abspath"
             exit 3
        }
        Write-Output "[h]$fnm[s->h]$test_target"
    }
    catch {
    }
    finally {
        Set-Location -LiteralPath "$saveCD"
    }
}

if( $Action -eq $null ) { $Action = "list" }
switch -Exact -CaseSensitive ($Action){
    "list" {
        Write-Output "List all Links"
        set-alias -name do_action -value fn_list
    }
    "DELETE" {
        $comfirm = (Read-Host "Please comfirm you are going to *DELETE* all links! [y/N]:").ToLower()
        if($comfirm -ne 'y' -And $comfirm -ne 'yes') {
            exit 0
        }
        set-alias -name do_action -value fn_delete
    }
    "h2s" {
        Write-Output "convert Hard Links to Symbolic Links"
        if( $false ){
        #if( -Not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator") ){
            try{
                Do {
                    $RandomFileName = "$ENV:TEMP\" + [System.IO.Path]::GetRandomFileName()
                }
                Until(!(Test-Path $RandomFileName))
                New-Item -ItemType SymbolicLink -Path "$RandomFileName" -Target "$PWD" 2> $null
                $testfile = Get-Item $RandomFileName 2> $null
                $ttp = $testfile.LinkType | out-null
                $testfile.Delete() | out-null
                if( $ttp -ne "SymbolicLink" ) { throw "Error: symboliclink create failed!" }
            }
            catch{
                Write-Output "WARNING: Powershell need administrator privilege to create symbolic links, now we are try CMD way."
                $cmd_create_symlink = $true
            }
        }
        set-alias -name do_action -value fn_h2s
    }
    "s2h" {
        Write-Output "convert Symbolic Links to Hard Links"
        set-alias -name do_action -value fn_s2h
    }
    Default {
        Write-Output "unknown action: $Action"
        exit 1
    }
}

$abstarget = Resolve-Path $target 
Get-ChildItem -Recurse $abstarget | ForEach-Object -Process{
    if($_ -is [System.IO.FileInfo])
    {
        if($_.LinkType -eq "HardLink"){
            do_action $_ "h"
            #Write-Output("[h]", $_.FullName);
        }
        elseif($_.LinkType -eq "SymbolicLink"){
            do_action $_ "s"
            #Write-Output("[s]", $_.FullName);
        }
    }
}
Write-Output "TargetDir: '$abstarget' Action: '$Action'"

```

**Comment by lbcz-tian** [comment]
> > 对了大佬，能分享下软转硬的方法吗？这样比按之前的方法改方便些😳
> 
> 我写了一个Windows 10下面的PowerShell脚本完成批量软转硬，以及批量删硬链接。只能用Windows 10自带的Powershell，最新跨平台的下载版本Powershell可能不支持。 先启动一个Powershell目录窗口，注意用普通用户权限，不要用管理员权限，用管理员权限可能无法执行，可以将这个脚本放在PATH路径下面，方便任意地点执行，我放在%USERPROFILE%.avdc\目录下面的，和avdc.exe放一起，然后将这个目录加入了PATH环境变量。 用法：
> 
> * 显示目标目录内的所有软硬链接
>   `winlinks.ps1 目标目录`
> * 软链接转硬链接
>   `winlinks.ps1 目标目录  -Action s2h`
> * 硬链接转软链接(未经过详细测试)
>   `winlinks.ps1 目标目录  -Action h2s`
> * 删除目标目录内**全部软硬链接**(危险操作，需确认一次)
>   `winlinks.ps1 目标目录  -Action DELETE`
>   不支持脚本附件上传，贴源代码吧。
> 
> ```powershell
> <#
> .SYNOPSIS
> 
> List or change links. BSD LICENSE by lededev @ github
> 
> .DESCRIPTION
> 
> List all links.
> Change Hard Links to Symbolic Links, or change Symbolic Links to Hard Links.
> Delete Links.
> 
> .PARAMETER TargetDir
> 
> Any valid Windows PATH
> 
> .PARAMETER Action
> 
> list: list all links. Default action.
> h2s: convert Hard Links to Symbolic Links.
> s2h: convert Symbolic Links to Hard Links.
> DELETE: Delete links.
> 
> .EXAMPLE
> 
> PS> .\thisprogram.ps1 .
> [h] Z:\mh.c
> [h] Z:\t\m.c
> 
> PS> .\thisprogram.ps1 Z:\t -Action h2s
> [s] Z:\t\m.c [h->s]
> 
> PS> .\thisprogram.ps1 Z:\t -Action DELETE
> [s] Z:\t\m.c [DELETED]
> #>
> param($TargetDir, $Action)
> 
> #ps win10 20H1 create relpath symlink has bug, ps v7.2.0-pv2 get hard link target has bug
> # dont use $cmd_create_symlink = $false
> $cmd_create_symlink = $true
> 
> if($TargetDir -eq $null) {
>     Get-Help $MyInvocation.MyCommand.Path -Detailed
>     exit 0
> }
> if((Get-Item $TargetDir) -is [System.IO.DirectoryInfo]){
>     $target = "$TargetDir"
> }else{
>     Write-Output "ERROR: TargetDir $TargetDir is not found!"
>     exit 1
> }
> function fn_list($f, $tp) {
>     $ostr = $f.FullName
>     Write-Output "[$tp]$ostr"
> }
> function fn_delete($f, $tp) {
> #    $f.Delete()
>     $ostr = $f.FullName
>     Remove-Item -LiteralPath "$ostr" -Force
>     Write-Output("[$tp]$ostr[DELETED]");
> }
> function fn_h2s($f, $tp) {
>     if( $tp -eq "s" ) {return}
>     $file_fullname = $f.FullName
>     $fullpath = Split-Path -Path $file_fullname
>     $hardlink_target = $f.Target | select -Last 1
>     if( $hardlink_target -eq $null ) {return}
>     $targetobj = Get-Item $hardlink_target
>     $target_fullname = $targetobj.FullName
>     $target_fullpath = Split-Path -Path $target_fullname
>     if( $target_fullpath.contains("$fullpath") ) {
>         Write-Output "Warning: This Hard link [$file_fullname] point to a target [$target_fullname] in same directory or it's subdirectory, recurse change hardlink to symlink in same directory tree may cause problem such as symlink -> symlink, skip this one."
>         return
>     }
> #Write-Output("DBG: $fullpath $hardlink_target", $f.Target)
>     Do {
>         $RandomFileName = "$fullpath\" + [System.IO.Path]::GetRandomFileName()
>     }
>     Until(!(Test-Path $RandomFileName))
>     
>     $target_fullpath = Split-Path -Path $hardlink_target
>     Push-Location $fullpath
>     $target_relpath = Resolve-Path -relative $target_fullpath
>     $target_relfile = "$target_relpath\" + (Split-Path -Leaf $hardlink_target)
>     Pop-Location
>     if( $cmd_create_symlink )
>     {
>         cmd /C mklink "$RandomFileName" "$target_relfile" | out-null
>     }
>     else
>     {
>         try {
>         #Write-Output "DBG: New-Item -ItemType SymbolicLink -Path $RandomFileName -Target $target_relfile"
>         Push-Location $fullpath
>             $random_nameonly = Split-Path -Leaf $RandomFileName
>             New-Item -ItemType SymbolicLink -Name "$random_nameonly" -Target "$target_relfile"
>         }
>         catch {
>             Write-Output "ERROR: Create Symbolic link failed."
>             exit 3
>         }
>         finally {
>             Pop-Location
>         }
>     }
>     $testfile = Get-Item "$RandomFileName"
>     if( $testfile.LinkType -ne "SymbolicLink" ){
>         $testfile.Delete()
>         Write-Output "ERROR: Create symbolic link type check failed!"
>         exit 4
>     }
>     $test_target = $testfile.Target
>     $tarobj = Get-Item "$test_target"
>     if( $tarobj.LinkType -eq "SymbolicLink" ){
>         Write-Output "ERROR: find problem, symlink's $RandomFileName target become symlink $test_target !"
>         exit 5
>     }
>     $f.Delete()
>     Rename-Item -Path "$RandomFileName" -NewName "$file_fullname"
>     $ostr = $f.FullName
>     Write-Output "[s]$ostr[h->s]$test_target"
> }
> 
> Function Log {
>     [CmdletBinding()]
>     Param(
>     [Parameter(Mandatory=$False)]
>     [ValidateSet("INFO","WARN","ERROR","FATAL","DEBUG")]
>     [String]
>     $Level = "INFO",
> 
>     [Parameter(Mandatory=$True)]
>     [string]
>     $Message,
> 
>     [Parameter(Mandatory=$False)]
>     [string]
>     $logfile = "D:\Logs\$Env:computername.log"
>     )
> 
>     $Stamp = (Get-Date).toString("yyyy/MM/dd HH:mm:ss")
>     $Line = "$Stamp $Level $Message"
>     If($logfile) {
>         Add-Content $logfile -Value $Line
>     }
>     Else {
>         Write-Output $Line
>     }
> }
> 
> function fn_s2h($f, $tp) {
>     if( $tp -eq "h" ) {return}
>     $fnm = $f.FullName
>     $symlink_target = $f.Target
>     $sDrv = $f.PSDrive.Name
>     $fullpath = Split-Path -LiteralPath "$fnm"
>     $saveCD = Get-Location
>     try {
>         Set-Location -LiteralPath "$fullpath"
>         If( -Not (Test-Path -LiteralPath "$symlink_target") ) {
>             Log -Verbose WARN "sym target:$symlink_target invalid."
>             return
>         }
>         try {
>             $abspath = Resolve-Path -LiteralPath "$symlink_target"
>             if( (Get-Item -LiteralPath "$abspath").PSDrive.Name -ne $sDrv ) {
>                 Log -Verbose WARN "target:$symlink_target and symlink:$fnm not in same Drive."
>                 return
>             }
>         }
>         catch {
>             Log -Verbose WARN "$symlink_target path ERROR, $fnm"
>             return
>         }
>         $targetobj = Get-Item -LiteralPath "$symlink_target"
>         if( -Not $targetobj -is [System.IO.FileInfo] -Or $targetobj.LinkType -eq "SymbolicLink" ) {
>             Log -Verbose WARN "This Symbolic link $fnm is not point to a regular file -> $symlink_target, can not be changed to Hard link!"
>             return
>         }
>         Do {
>             $RandomFileName = ".\" + [System.IO.Path]::GetRandomFileName()
>         }
>         Until(!(Test-Path -LiteralPath $RandomFileName))
>         try {
>     #Write-Output("DBG: b4new-i $RandomFileName $symlink_target")
>             #$escpath = ([WildcardPattern]::Escape([WildcardPattern]::Escape("$abspath")))
>             #New-Item -ItemType HardLink -Path "$RandomFileName" -Value "$escpath" #| out-null
>             cmd /C mklink /H "$RandomFileName" "$abspath" | out-null
>             $testfile = Get-Item -Path "$RandomFileName"
>             if( $testfile.LinkType -ne "HardLink" ){
>     #Write-Output("DBG: enter del", $testfile.LinkType, $file_fullname)
>                 $testfile.Delete()
>                 throw "Error: Create hard link type check failed!"
>             }
>             $test_target = $testfile.Target
>     #Write-Output("DBG: $test_target $file_fullname")
>             $f.Delete()
>             Rename-Item -Path "$RandomFileName" -NewName "$fnm"
>         }
>         catch {
>              Log -Verbose ERROR "Create Hard link failed: $abspath"
>              exit 3
>         }
>         Write-Output "[h]$fnm[s->h]$test_target"
>     }
>     catch {
>     }
>     finally {
>         Set-Location -LiteralPath "$saveCD"
>     }
> }
> 
> if( $Action -eq $null ) { $Action = "list" }
> switch -Exact -CaseSensitive ($Action){
>     "list" {
>         Write-Output "List all Links"
>         set-alias -name do_action -value fn_list
>     }
>     "DELETE" {
>         $comfirm = (Read-Host "Please comfirm you are going to *DELETE* all links! [y/N]:").ToLower()
>         if($comfirm -ne 'y' -And $comfirm -ne 'yes') {
>             exit 0
>         }
>         set-alias -name do_action -value fn_delete
>     }
>     "h2s" {
>         Write-Output "convert Hard Links to Symbolic Links"
>         if( $false ){
>         #if( -Not ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole] "Administrator") ){
>             try{
>                 Do {
>                     $RandomFileName = "$ENV:TEMP\" + [System.IO.Path]::GetRandomFileName()
>                 }
>                 Until(!(Test-Path $RandomFileName))
>                 New-Item -ItemType SymbolicLink -Path "$RandomFileName" -Target "$PWD" 2> $null
>                 $testfile = Get-Item $RandomFileName 2> $null
>                 $ttp = $testfile.LinkType | out-null
>                 $testfile.Delete() | out-null
>                 if( $ttp -ne "SymbolicLink" ) { throw "Error: symboliclink create failed!" }
>             }
>             catch{
>                 Write-Output "WARNING: Powershell need administrator privilege to create symbolic links, now we are try CMD way."
>                 $cmd_create_symlink = $true
>             }
>         }
>         set-alias -name do_action -value fn_h2s
>     }
>     "s2h" {
>         Write-Output "convert Symbolic Links to Hard Links"
>         set-alias -name do_action -value fn_s2h
>     }
>     Default {
>         Write-Output "unknown action: $Action"
>         exit 1
>     }
> }
> 
> $abstarget = Resolve-Path $target 
> Get-ChildItem -Recurse $abstarget | ForEach-Object -Process{
>     if($_ -is [System.IO.FileInfo])
>     {
>         if($_.LinkType -eq "HardLink"){
>             do_action $_ "h"
>             #Write-Output("[h]", $_.FullName);
>         }
>         elseif($_.LinkType -eq "SymbolicLink"){
>             do_action $_ "s"
>             #Write-Output("[s]", $_.FullName);
>         }
>     }
> }
> Write-Output "TargetDir: '$abstarget' Action: '$Action'"
> ```

感谢大佬！！😍

**Comment by sino1641** [comment]
@lededev 
虽然有点偏题
但还是请问 为什么要在`c_number.json`里放进一批预先翻译好的影片名称

**Comment by sino1641** [comment]
> @lededev 虽然有点偏题 但还是请问 为什么要在`c_number.json`里放进一批预先翻译好的影片名称

963320a14e9a38b23a26b5602c0bea81d3137082

既然色花堂每天都在更新 
那么是否有必要写个爬虫（github actions 定期fetch）之类的

**Comment by lededev** [comment]
@sino1641 c_number.json不是我加进来的，我只是修了一下没下载c_number.json导致Error 2的bug而已，所以你问我问什么，问错人了。

**Comment by sino1641** [comment]
> @sino1641 c_number.json不是我加进来的，我只是修了一下没下载c_number.json导致Error 2的bug而已，所以你问我问什么，问错人了。

所以应该@yoshiko2 对吗
（感觉开issue不太合适 就直接评论区问了）
