### ISSUE TITLE
nfo里很多翻译有一个“@YOU”

### ISSUE THREAD

**Issue by lbcz-tian** [yoshiko2/AV_Data_Capture#637]
因为更新了剧情介绍，我在全部重新刮削，但是我发现偶尔会把演员名识别为`@YOU`，后来检查发现不止演员名，很多地方都有这个，我随便贴一个nfo：
![](https://s3.bmp.ovh/imgs/2021/11/a44f5f0299eb69a9.png)
![](https://s3.bmp.ovh/imgs/2021/11/7a94e94843624df5.png)

我打开了translate_to_sc、机器翻译、简繁转换这些功能，不知道是啥子问题额

**Comment by theturtle626** [comment]
一樣問題

**Comment by supsupsuperstar** [comment]
+1

**Comment by yoshiko2** [comment]
5.0.4已修复

**Comment by lbcz-tian** [comment]
> 5.0.4已修复

赞美大佬！
不过我想问一下，为了避免再全盘刮削一遍，有没有办法只修改nfo，不变动图片啥的(ಥ_ಥ) ， 我这文件太多了，全盘刮削差不多得一天。。。

**Comment by lbcz-tian** [comment]
> 5.0.4已修复

赞美大佬！
不过我想问一下，为了避免再全盘刮削一遍，有没有办法只修改nfo，不变动图片啥的(ಥ_ಥ) ， 我这文件太多了，全盘刮削差不多得一天。。。

**Comment by supsupsuperstar** [comment]
> 5.0.4已修复

![搜狗截图20211120222918](https://user-images.githubusercontent.com/43098395/142730181-0c1ef0b3-283b-4677-abac-2e633de91fa2.jpg)
![搜狗截图20211120222956](https://user-images.githubusercontent.com/43098395/142730182-797f2716-3a05-4900-97ae-b4fd79c9ff2f.jpg)

debug没显示了，但是nfo还是写入了

**Comment by lbcz-tian** [comment]
> 5.0.4已修复

nfo里确实还是有'@YOU‘，而且如果原来演员名字是’@YOU‘，现在就直接没有名字了额😳😳
![Snipaste_2021-11-20_22-42-18](https://user-images.githubusercontent.com/62131027/142730471-4757e4bf-dec7-4cb8-8abc-2cf6d7517214.png)

**Comment by yoshiko2** [comment]
删除家目录下 .local/share/avdc/ 再次运行程序

**Comment by yoshiko2** [comment]
> > 5.0.4已修复
> 
> nfo里确实还是有'@you‘，而且如果原来演员名字是’@you‘，现在就直接没有名字了额😳😳 ![Snipaste_2021-11-20_22-44-03](https://user-images.githubusercontent.com/62131027/142730523-c3df8f7e-9491-4f3d-ae13-2f206ca7c7c0.png)

删除家目录下 .local/share/avdc/ 再次运行程序

**Comment by lbcz-tian** [comment]
> > > 5.0.4已修复
> > 
> > 
> > nfo里确实还是有'@you‘，而且如果原来演员名字是’@you‘，现在就直接没有名字了额😳😳 ![Snipaste_2021-11-20_22-44-03](https://user-images.githubusercontent.com/62131027/142730523-c3df8f7e-9491-4f3d-ae13-2f206ca7c7c0.png)
> 
> 删除家目录下 .local/share/avdc/ 再次运行程序

尝试操作了一遍，`@YOU`没了，但是全部变成了`AIKA`😳
![Snipaste_2021-11-20_23-13-43](https://user-images.githubusercontent.com/62131027/142731609-d4569b98-7ce0-45d2-8d50-24aeea5bf0d1.png)

**Comment by yoshiko2** [comment]
> > > > 5.0.4已修复
> > > 
> > > 
> > > nfo里确实还是有'@you‘，而且如果原来演员名字是’@you‘，现在就直接没有名字了额😳😳 ![Snipaste_2021-11-20_22-44-03](https://user-images.githubusercontent.com/62131027/142730523-c3df8f7e-9491-4f3d-ae13-2f206ca7c7c0.png)
> > 
> > 
> > 删除家目录下 .local/share/avdc/ 再次运行程序
> 
> 尝试操作了一遍，`@YOU`没了，但是全部变成了`AIKA`😳 ![Snipaste_2021-11-20_23-13-43](https://user-images.githubusercontent.com/62131027/142731609-d4569b98-7ce0-45d2-8d50-24aeea5bf0d1.png)

pull最新源码运行看看还有没有

**Comment by supsupsuperstar** [comment]
win10 下了action最新的版本可以了

**Comment by lbcz-tian** [comment]
源码也可以了，赞美大佬！
