### ISSUE TITLE
字幕和流出的标志只能二选一

### ISSUE THREAD

**Issue by lbcz-tian** [yoshiko2/AV_Data_Capture#640]
后缀为`-C-流出`时也只能打上`流出`的标志，字幕标志就没了额(⊙﹏⊙)

**Comment by theturtle626** [comment]
我以前都是用 -流出-C，新版本還沒測試過

**Comment by lbcz-tian** [comment]
> 我以前都是用 -流出-C，新版本還沒測試過

啊这，确实调换顺序就可以。。。

**Comment by 0x11901** [comment]
感觉这确实是个bug，如果我不看这一个issue，永远也不知道流出和中文两个标签怎么共存
