### ISSUE TITLE
windows 下naming_rule无法输出title

### ISSUE THREAD

**Issue by ne7erland** [yoshiko2/AV_Data_Capture#641]
比如用SIVR-137
location_rule=actor+'/'+number+' '+title
naming_rule=number+' '+title
目录是：JAV_output\三上悠亚\SIVR-137 【VR】相部屋ほろ酔い逆NTR 巨乳で可爱い新入社员の无防备なおっぱい诱惑に负けて狂ったようにハメま
文件名却是：SIVR-137.mkv
用的是5.0.3，之前几个版本也都试过都不行

**Comment by alanqq0624** [comment]
我自己嘗試的結果是
naming_rule的字串中不能包含有空白
不然他的title會怪怪的
你改成
naming_rule=number+'-'+title
嘗試看看
