### ISSUE TITLE
关于翻译失效

### ISSUE THREAD

**Issue by Dantezcx** [yoshiko2/AV_Data_Capture#644]
; 机器翻译
[transalte]
switch=1
;可选项 google-free,azure
engine=google-free
; azure翻译密钥
key=
; 翻译延迟
delay=1
values=title,outline
service_site=translate.google.cn

当机器翻译开了之后直接无法搜刮
[*]================== AV Data Capture ===================
[*]                        5.0.3                         
[*]======================================================
[*]严禁在墙内宣传本项目
[+]Start at 2021-11-16 16:17:04
[+]Load Config file 'E:\Download\迅雷下载\H\config.ini'.
[+]Main Working mode ## 1: Scraping ## , nfo_skip_days=30
[+]Find 1 movies.
[*]======================================================
[!]                - 100.% [1/1] -             16:17:04
[!] [STARS-407] As Number making data for 'E:\Download\迅雷下载\H\STARS-407-C.mp4'
[+]Find movie [STARS-407] metadata on website 'javbus'
[-] [E:\Download\迅雷下载\H\STARS-407-C.mp4] ERROR:
[-] [Errno 2] No such file or directory: 'C:\\Users\\dante\\.local\\share\\avdc\\c_number.json'
'[-]Move to Failed output folder, see 'E:\Download\迅雷下载\H\failed\where_was_i_before_being_moved.txt'
[+]Running time 0:00:04.183  End at 2021-11-16 16:17:08
[+]All finished!!!

关掉之后正常

**Comment by Dantezcx** [comment]
现在无法打开了- -
Traceback (most recent call last):
  File "AV_Data_Capture.py", line 547, in <module>
  File "AV_Data_Capture.py", line 473, in main
  File "AV_Data_Capture.py", line 29, in check_update
KeyError: 'tag_name'

**Comment by lbcz-tian** [comment]
#635

**Comment by lbcz-tian** [comment]
源码已经合并了对应PR，下载源码刮削就行
