### ISSUE TITLE
大佬们！我更新到5.0.X之后几十添加了Javdb9.json仍然不能刮削FC2的内容！

### ISSUE THREAD

**Issue by icedrain0611** [yoshiko2/AV_Data_Capture#647]
现在使用4.7.2和5.0.4共存，你们有这么个情况过么？是不是我需要额外配置？

**Comment by lededev** [comment]
因为javdb9这个站点不能用了，目前支持的是javdb31或者32，只能选一个，因为登陆另一个时，前一个会被踢下线。
下载我的导出工具可以加参数，31导出javdb31.json，32导出javdb32.json。

**Comment by lededev** [comment]
具体改动见[PR607](https://github.com/yoshiko2/AV_Data_Capture/pull/607#issuecomment-939281638)

**Comment by lededev** [comment]
在[ISSUE504](https://github.com/yoshiko2/AV_Data_Capture/issues/504#issuecomment-939224081)则提供了工具

**Comment by icedrain0611** [comment]
3
q




------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;; 
Date: 2021年11月21日(星期天) 晚上11:45
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; ***@***.***&gt;; 
Subject: Re: [yoshiko2/AV_Data_Capture] 大佬们！我更新到5.0.X之后几十添加了Javdb9.json仍然不能刮削FC2的内容！ (Issue #647)





 
在ISSUE-504则提供了工具
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by lededev** [comment]
只能导出最新登录的那个站点，其余cookie是无效的，原因见https://github.com/yoshiko2/AV_Data_Capture/issues/504#issuecomment-939281846
