### ISSUE TITLE
使用源码编译后无法连接网络

### ISSUE THREAD

**Issue by kglife** [yoshiko2/AV_Data_Capture#650]
使用源码编译后无法连接网络，请问是否需安装特殊的包？编译时正常，运行时提示无法联网（4.7.2编译后正常运行）。
![QQ图片20211125114613](https://user-images.githubusercontent.com/82629056/143377636-c33c3ef4-cc87-4519-9ce1-5713e84f3867.png)

**Comment by yoshiko2** [comment]
打包命令
pyinstaller \
            --onefile AV_Data_Capture.py \
            --hidden-import ADC_function.py \
            --hidden-import core.py \
            --add-data "$(python -c 'import cloudscraper as _; print(_.__path__[0])' | tail -n 1);cloudscraper" \
            --add-data "$(python -c 'import opencc as _; print(_.__path__[0])' | tail -n 1);opencc" \
            --add-data "Img;Img" \
            --add-data "config.ini;."
