### ISSUE TITLE
建议在文件夹创建增加系列命名参数！

### ISSUE THREAD

**Issue by doubao07** [yoshiko2/AV_Data_Capture#66]
我在配置里面把创建文件夹的设置改成了location_rule = number+' '+actor ，这样创建的电影文件夹名字就是番号+演员，好处就是可以通过everything直接搜索演员来整理文件。如果能添加系列命名参数，就能通过搜索系列关键字整理成系列作品。

**Comment by yangj570** [comment]
想不通重命名这种小事儿还要麻烦作者？完全可以自己写批处理脚本或者用renamer等软件改掉啊。

像我就是自己写了一个rename.py放在JAV_output里，程序运行完了后再跑一边自己的脚本就行了，主要是把几个文件名和nfo里的<poster>、<thumb>、<fanart>标签改掉。
