### ISSUE TITLE
请问为何封面和大图要分别创建两个不同命名的重复文件

### ISSUE THREAD

**Issue by Mosney** [yoshiko2/AV_Data_Capture#69]
![image](https://user-images.githubusercontent.com/22477230/71595366-3a272280-2b76-11ea-9083-02310cdef9f7.png)
plex中backdrop和fanart是同一张横板完整海报，poster和thumb是同一张竖版海报
emby中backdrop和*.jpg是同一张横板完整海报，*.png是竖版海报
看的我一头雾水，plex的话可能是图片分类较多为了适配不同类别下的图片？
但是目前在用的emby，实际元数据只识别出了两张，分别是`封面图`和`背景`。

![image](https://user-images.githubusercontent.com/22477230/71595558-1a442e80-2b77-11ea-9cbe-503c912be0e8.png)

**Comment by doubao07** [comment]
有一张大图是给缩略图显示用的
