### ISSUE TITLE
部分在javbus中存在的番号无法正常提取数据，版本2.0

### ISSUE THREAD

**Issue by ChenKuiHan** [yoshiko2/AV_Data_Capture#75]
例如番号012717_472，此番号在javbus上存在，url：https://www.javbus.com/012717_472 
文件名为012717_472.mp4，软件可以正常识别番号，但接下来会输出一个html，然后提示连接失败，请检查网络代理，但是其他番号可以正常提取说明我本地的代理是没问题的。
直接将视频文件拖到core.exe结果一样。
莫非这种番号不在javbus上进行数据采集？

以下为软件部分输出
1.  src="https://api.qrserver.com/v1/create-qr-code/?size=800x800&data=https%3A%2F%2Favsox.host" class=
2. "qrcode"> </a> </div> </div> </div> </div>  <body> </html>
3. [-]Connect retry 1/5
4. [-]Connect retry 2/5
5. [-]Connect retry 3/5
6. [-]Connect retry 4/5
7. [-]Connect retry 5/5
8. [-]Connect Failed! Please check your Proxy or Network!
9. Traceback (most recent call last):
10.   File "core.py", line 650, in <module>
11.   File "core.py", line 119, in getDataFromJSON
12.   File "avsox.py", line 88, in main
13.   File "site-packages\bs4\__init__.py", line 275, in __init__
14. TypeError: object of type 'NoneType' has no len()
15. [10468] Failed to execute script core
16. [*]======================================================
17. [+]All finished!!!
18. [+][+]Press enter key exit, you can check the error messge before you exit.

1.

**Comment by ChenKuiHan** [comment]
而且失败的文件并没有被移动到failed目录中

**Comment by yoshiko2** [comment]
抓取模块的逻辑问题，等修复
