### ISSUE TITLE
正常解析50部后 余下40部无法解析 提示什么：列表索引超出范围

### ISSUE THREAD

**Issue by RITIAN666** [yoshiko2/AV_Data_Capture#79]
我是路由器代理
下面是配置文件：
====================================
[common]
main_mode=1
failed_output_folder=failed
success_output_folder=FBI-WARNING_output
soft_link=0

[proxy]
proxy=
timeout=10
retry=3

[Name_Rule]
location_rule=actor+'/'+number
naming_rule=number+'-'+title

[update]
update_check=1

[media]
media_warehouse=plex
#emby or plex or kodi ,emby=jellyfin

[escape]
literals=[7sht.me]

[debug_mode]
switch=0

====================================
下面是出错的提示
====================================

[*]================== AV Data Capture ===================
[*]                     Version 2.3
[*]======================================================
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for   [.\SSNI331.mp4], the number is [SSNI331]
Traceback (most recent call last):
  File "fanza.py", line 53, in getRelease
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "core.py", line 702, in <module>
  File "core.py", line 140, in getDataFromJSON
  File "fanza.py", line 92, in main
  File "fanza.py", line 55, in getRelease
IndexError: list index out of range
[26724] Failed to execute script core
[*]======================================================
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.

**Comment by yoshiko2** [comment]
请重新下载新版本~
