### ISSUE TITLE
合集还有影片重名的问题

### ISSUE THREAD

**Issue by bbingz** [yoshiko2/AV_Data_Capture#8]
给作者点赞！
使用中碰到一些问题，不知道还能不能进一步优化一下。
1、合集ABC等多部分不能正确识别，会提示已经存在；
2、有部分影片是存在重名的，JAVBUS的办法是后面再加一段，例如AKA-008-2；
3、能不能加个生成log文件，这样方便被操作去了什么位置。

**Comment by icedrain0611** [comment]
我也是用户，1
的问题javhelper也有出现，我这边找了一个很好的解决办法：手动改

**Comment by wenead99** [comment]
log文件和分集在研究，下个10.7版本会添加emby里中文字幕标识，不过要求文件名为"-C.后缀"或者"-c.后缀"，才会被程序识别为中文字幕影片
