### ISSUE TITLE
程序将同文件夹下论坛宣传文件也扫描进去了

### ISSUE THREAD

**Issue by chyaww** [yoshiko2/AV_Data_Capture#80]
[!]Making Data for   [.\ABP-627\uuv79.mp4], the number is [ABP-627]
如上，这个UUV79是论坛的宣传文件~如果先扫描到了论坛文件，真的视频还挪不进去了。。。

**Comment by NJCCJohnWason** [comment]
@chyaww

**Comment by NJCCJohnWason** [comment]
@chyaww 就我个人来说，下载的时候就会把不必要的文件排除，勾选掉，只留下视频文件。色花的宣传文件文件名时常会变，指望开发大佬们一直改不现实。
建议自己把垃圾文件删除之后再使用程序。

**Comment by chyaww** [comment]
@NJCCJohnWason 嗯，这是一种办法。但是可以从文件名处理上着手，现在这个程序的逻辑是按照文件夹的编号更改文件夹内所有视频的文件名，是否按照文件名来处理更合理点？
