### ISSUE TITLE
socks代理问题

### ISSUE THREAD

**Issue by mmujohn** [yoshiko2/AV_Data_Capture#81]
装在docker里，主机地址192.168.10.42，
在docker里curl -x socks5h://192.168.10.42:1080 www.google.com  有返回，
config.ini里写proxy=192.168.10.42:1080 , 连接不了。

是哪里设置不对么

**Comment by mmujohn** [comment]
解决了，pip install -U requests[socks]
建议ADC_function.py 100行
`proxies = {"http": "http://" + proxy,"https": "https://" + proxy}
`
改成
`proxies = {"http": proxy,"https": proxy}
`
增加灵活性
改了以后config.ini里写
`proxy=socks5h://192.168.10.42:1080
`

**Comment by helieting** [comment]
还有core.py 228

**Comment by tanpengsccd** [comment]
接楼上的 就是 改为 ` proxies={"http": str(proxy), "https": str(proxy)})`
而且可能要再安装` pip install pysocks`
