### ISSUE TITLE
多級目錄掃描問題

### ISSUE THREAD

**Issue by xperiazu21** [yoshiko2/AV_Data_Capture#82]
現在2.3版程序會自動抓取程式所在目錄下的所有影片，包含底下資料夾內的，但我只希望程序能只掃描我要的目錄。
請問能再加個指定掃描目錄的功能，或是排除掃描指定目錄的功能嗎?

**Comment by bacanhsu** [comment]
排除指定字符和目录
[escape]
literals=\
folders=failed,JAV_output
literals= 标题指定字符删除，例如iterals=\()，删除标题中\()字符
folders= 排指定目录，例如folders=failed,JAV_output，多目录刮削时跳过failed,JAV_output
