### ISSUE TITLE
Tokyo Hot系列抓不到

### ISSUE THREAD

**Issue by delphius81** [yoshiko2/AV_Data_Capture#88]
大神新年快乐！
过年无聊在家整理AV，有这款软件真的很方便。
提交一个问题，无码的东京热系列抓不到资讯。
例如n0635在avsox有页面（[n0635](http://avsox.host/ja/movie/f4ed2961c1be69e5)）但会出现下面的错误。
好像是从fanza抓的？不知道是不是调整一下刮的顺序可以解决。

[*]================== AV Data Capture ===================
[*]                     Version 2.3
[*]======================================================
[+]Find 1 movies
[!] - 100.% [1/1] -
[!]Making Data for   [.\n0635.wmv], the number is [n0635]
Active code page: 936
Traceback (most recent call last):
  File "core.py", line 702, in <module>
  File "core.py", line 140, in getDataFromJSON
  File "fanza.py", line 86, in main
  File "fanza.py", line 13, in getTitle
IndexError: list index out of range
[11336] Failed to execute script core
[*]======================================================
[+]All finished!!!
[+][+]Press enter key exit, you can check the error messge before you exit.

**Comment by NJCCJohnWason** [comment]
有人之前反映过这个问题，貌似用2.2版本就可以了。
你可以先试一下2.2，不行等大神之后更新。

**Comment by delphius81** [comment]
好的，谢谢。我用2.2来处理看看
