### ISSUE TITLE
Windows下naming_rule无效

### ISSUE THREAD

**Issue by EmbleXue** [yoshiko2/AV_Data_Capture#9]
以下建议均基于我在刮削无码影片时的体验

无论如何修改 **naming_rule** ，都不能正确作用在输出的文档上。
下载了源代码，觉得可能是这几个地方有待商榷。
首先是
PrintFiles方法中的
>print(" <title>" + naming_rule + "</title>", file=code)

这里naming_rule是否应为title?否则的话nfo信息中的title一栏就变成了我们自定义的文件名
例：
><title>[020216-087] - アナル初体験を奪ってみました [2016-02-02]</title>

然后是 **pasteFileToFolder** 
>os.rename(filepath, number + houzhui)
    shutil.move(number + houzhui, path)

这里number改成naming_rule是否就能实现用户自定义输出文件名的效果？

最后是一点小建议，在刮削无码影片时，所有影片的背景图都叫backdrop.jpg。
是否可以根据naming_rule来重命名？
这样格式就会与EverAver统一起来，产生两张图，一张为naming_rule.png，一张为naming_rule.jpg。

**感谢你的工作，期待你在下一次更新中能够考虑我的建议并改进，希望这款软件能变得更好！谢谢！**

**Comment by wenead99** [comment]
number应该可以改成naming_rule，你试试，具体功能因学业我周末再试；只有命名backdrop.jpg EMBY才能认出是背景图。最晚我周一出新版本，会解决很多问题，也包括你的。

**Comment by changyipai** [comment]
作者如果願意，我願意贊助您，但前提是您如果願意修改這個軟體讓他變得強大，我相信這種軟體未來一定是必要的商機。
我建議如下：
1. 建議加入 
259LUXU 完整品番：259LUXU-1046
300MAAN  完整品番：300MAAN-423
300MIUM  完整品番：300MIUM-424
2. 命名問題
   A. 狼友(就是使用者)可自定義的取名，不用去預設他們要怎麼命名，多長。像是我就只是單存的 [品番]名稱
3. 一本道、FC2 這種，我發現命名後 Ipon 這種字眼都會消失，但我命名就是需要他

**Comment by yoshiko2** [comment]
品番缺失是网站的问题，软件本来就可以自定义命名，如果没发现麻烦大声朗读软件文档 @changyipai

**Comment by changyipai** [comment]
我有自定義，影片命名不會正常，但是資料夾可以

**Comment by EmbleXue** [comment]
突然发现我的邮箱里多了几封邮件，他说的没错。
你在beta11.5把number改成了naming_rule，但是不知道为什么到了最新的11.6又变成number了。
>try:
        os.rename(filepath, number + houzhui)

这也就造成了无法命名文件的问题。
另外一个小小的提醒，write的过去式并不是writeed，而是wrote。
> print("[+]Writeed!          " + path + "/" + number + ".nfo")
