### ISSUE TITLE
影片抓取失败但在JAV_output中建立了文件夹

### ISSUE THREAD

**Issue by gatalon** [yoshiko2/AV_Data_Capture#90]
如影片FC2-PPV-1252953.mp4抓取不到信息但在JAV_output中建立了文件夹“JAV_output\FC2系列\FC2-1252953"并且里面有个1kb的FC2-1252953.jpg图片文件，打开提示是损坏的。
正常情况下不应该有文件夹被建立才对。

**Comment by yoshiko2** [comment]
要图

**Comment by gatalon** [comment]
> 
> 
> 要图
这上面好像不太好传图，此问题可通过如下的步骤重现：
1. 建立一个FC2-PPV-1252953.mp4的空文件模拟这个影片需要被抓取元数据信息，把它放到主程序所在的目录。
2. 运行主程序，会提示抓取失败，同时程序会崩溃，正常应该是等待用户查看输出信息后并点击任意键程序才正常退出。
3. FC2-PPV-1252953.mp4会被移动到failed目录下，但是JAV_output文件夹下会被建立如下的目录及文件"JAV_output\FC2系列\FC2-1252953\FC2-1252953.jpg"，且FC2-1252953.jpg大小为1kb，用照片查看器打开会提示打开失败。

**Comment by moyy996** [comment]
这个番号在fc2club找不到，至于为啥提示找不到之后，还有大小为1kb的FC2-1252953.jpg 是代码逻辑问题。

**Comment by gatalon** [comment]
之前的FC2-1252953已经没有问题了，但是112114_01、080114_01还有同样的问题，可以自己建两个空的MP4文件用这两个番号试试，用的最新的2.5版。
