### ISSUE TITLE
2.4 Release 闪退

### ISSUE THREAD

**Issue by leozhu1120** [yoshiko2/AV_Data_Capture#92]
如题 2.4的exe程序在打开后开始制作第一个文件封面后闪退

**Comment by yoshiko2** [comment]
no image say jb

**Comment by leozhu1120** [comment]
![WechatIMG1369](https://user-images.githubusercontent.com/59215468/73591691-d0ab8280-452c-11ea-8740-686bb36b129f.png)
就到这然后就闪退了

**Comment by max-sun-hongyi** [comment]
> ![WechatIMG1369](https://user-images.githubusercontent.com/59215468/73591691-d0ab8280-452c-11ea-8740-686bb36b129f.png)
> 就到这然后就闪退了

老哥你这是没有车牌号的车

**Comment by leozhu1120** [comment]
跟这没关系 之前的版本顶多识别不了 但是不会闪退

**Comment by yoshiko2** [comment]
不要在磁盘根目录下运行软件

**Comment by leozhu1120** [comment]
> 不要在磁盘根目录下运行软件

我刚刚移到下级目录试了两次 运行到10%之后的时候退了 之前的版本（不能多目录扫描的版本）我也是直接在根目录下运行的都没事 那是我windows磁盘映射的nas的盘

**Comment by siyiye** [comment]
是的，我用2.4也是闪退（番号出现无法识别就会如此，就直接终止程序了），以前都会自动跳过继续扫描后续的。

现在退回2.3了，等待bug修复

**Comment by leozhu1120** [comment]
> 是的，我用2.4也是闪退（番号出现无法识别就会如此，就直接终止程序了），以前都会自动跳过继续扫描后续的。
> 
> 现在退回2.3了，等待bug修复

嗯 等更新吧 
现在有了多目录扫描之后我突然不愿意再手动把视频文件都拖到一个目录下了 :-P
