### ISSUE TITLE
作者是否介意在其他论坛、社区分享你的工具？

### ISSUE THREAD

**Issue by ChenKuiHan** [yoshiko2/AV_Data_Capture#94]
如题，我可能会获得一些积分之类的收益，但绝不收费；
如果可以分享，作者希望我使用度盘一类的渠道直接分享软件本体，还是直接指向github仓库？

**Comment by yoshiko2** [comment]
欢迎分享，要指向GITHUB仓库，如果要在大陆的论坛分享，最好低调些

**Comment by ChenKuiHan** [comment]
好的

**Comment by yoshiko2** [comment]
请问你在哪个论坛分享？

**Comment by ChenKuiHan** [comment]
色花堂，看名字就应该知道不是啥正经网站~兄弟需要帖子链接么？
