### ISSUE TITLE
如果数据库中有同名的就不会判断了....

### ISSUE THREAD

**Issue by siyiye** [yoshiko2/AV_Data_Capture#96]
比如“AKA-008“，就匹配不上

**Comment by siyiye** [comment]
正确的应该识别为红框的这个：
![111](https://user-images.githubusercontent.com/35824760/73654406-9249cb00-46c6-11ea-95f9-0d1629dcdc17.png)

**Comment by moyy996** [comment]
这个失败是太巧了，https://www.javbus.com/AKA-008 页面不存在，番号所在的网址是https://www.javbus.com/AKA-008_2015-06-26 ，而且javdb搜到的第一个也不是AKA-008，千古奇番。
可以试试GUI版，可以刮削到。

**Comment by moyy996** [comment]
https://github.com/moyy996/AVDC/releases
