### ISSUE TITLE
一直提示can not catch the number，不知什么原因。需要翻墙吗

### ISSUE THREAD

**Issue by jxmlingyun** [yoshiko2/AV_Data_Capture#97]
![image](https://user-images.githubusercontent.com/3866004/73655903-fc17a400-46c9-11ea-8149-a26979ff936b.png)

![image](https://user-images.githubusercontent.com/3866004/73655682-7f84c580-46c9-11ea-9a1a-ae4c31f41218.png)

**Comment by moyy996** [comment]
需要翻墙
