### ISSUE TITLE
目录层级中使用其他符号提示无法抓到番号

### ISSUE THREAD

**Issue by bwskyer** [yoshiko2/AV_Data_Capture#98]
想在二级目录中使用中括号，如下格式，我看Pockies的博客也是用的这个方式，但版本不是采用最新版用如下格式提示：Cannot catch the number

location_rule = actor+'/'+'['+year+'] '+title+' ['+number+']'

希望能恢复这样的自定义目录功能，采用默认可以找到并顺利执行。

**Comment by yoshiko2** [comment]
不行的话先用2.3版本

**Comment by yoshiko2** [comment]
下个版本修复这BUG
